### ISSUE TITLE
딜 환경 통일성 유지

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#101]
https://github.com/oleneyl/maplestory_dpm_calc/issues/95

## 허수아비 타격을 기준으로 반영된 스킬들

* 듀얼블레이드 - 블레이드 토네이도
  * 1+8타까지 가능하나, 허수아비 기준인 1+5타로 적용중
  * ...이라고 주석엔 써져있는데 로그를 보면 1+6타로 동작하고 있음
* 아크메이지불/독 - 포이즌 노바
  * 최대 히트는 모르겠지만 허수아비 기준인 4히트로 적용중
  * 그와 별개로 퍼뎀에 오류가 있고, 3개 초과시 데미지 반감이 단순 타수로 적용되어 맥뎀시 약간의 오차생김
* 키네시스 - 싸이킥 샷
  * 히트율 80%로 적용중

## 최대 타격을 기준으로 반영된 스킬들

* 캐논슈터 - BFG 캐논볼
  * 허수아비 기준 27회 충돌, 최대치인 50회 충돌로 적용중
* 아크메이지썬/콜 - 썬더 브레이크
  * 허수아비 기준 2타만 들어가나, 최대치인 8타로 적용중
  * 이는 기존에 공유되던 dpm표에서도 8타로 되어있었는데, 이유는 불명

## 확인이 필요한 스킬들

* 보우마스터 - 애로우 레인
* 키네시스 - 무빙 매터
* 비숍 - 피스메이커
  * 1회 타격 후 즉시 폭발로 설정되어 있는데, 실전 솔플에서는 3회 타격 이후 폭발시킨다고 알려져 있습니다.
  * 그와 별개로, 최종 버프가 남은 접촉 횟수 12회로 되어있는데, 일단 데미지 1틱은 넣으니 11회가 됩니다.
  * 그리고 사용시 자기 자신이 회복되는 것도 접촉 횟수에 포함되는지 확인해야 합니다. 그렇다면 1회가 더 까입니다.

지금까지 발견한 조건에 따라 타수가 달라지는 스킬은 이정도가 있습니다.

커뮤니티 등에서 추가적으로 제보를 받아가면서 허수아비 타격 기준으로 통일해나갈 필요가 있습니다.

**Comment by cheese98** [comment]
무릉도장 연습용 뒷마당의 중앙에 설치된 캐릭터의 레벨과 동일한 허수아비를 최적의 컨트롤로 무한히 타격하는 것을 기준으로 삼는 것이 좋을 것 같다고 생각합니다. DPM 측정대상의 레벨 정도면 펫 3마리를 충분히 가동할 수 있을거라고 생각이 되니 딜레이가 큰 버프 3개를 펫버프화 시키는 것도 괜찮아 보입니다.

**Comment by icepeng** [comment]
그렇다면 딜 조건을 문서화하고, 사이트에도 표기하는게 좋겠습니다.

**Comment by cheese98** [comment]
좋은 생각입니다. 하지만 측정 기준은 저희가 정한다고 사람들이 따라오는 것이 아니기 때문에 커뮤니티에서 일반 유저들의 의견을 충분히 수렴하고 정해야 한다고 생각합니다.

**Comment by cheese98** [comment]
이전 DPM표에서도 펫버프 3개를 반영했다고 합니다. ([링크](https://blog.naver.com/oe135/221244140599))

우리도 펫버프의 딜레이를 0으로 하되 앞에 주석을 달아서 펫버프임을 알리고 원래 딜레이값을 써놓으면 좋을 것 같습니다.

**Comment by icepeng** [comment]
본문에 명시된 모든 스킬 타수 확인 완료.

캐슈, 썬콜은 타수를 상수로 분리해 숫자만 바꾸면 조건별 dpm 뽑을 수 있게 해둠.
