### ISSUE TITLE
나로 피드백

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#106]
- [x] 스프레드 스로우 도중에 풍마수리검 사용하지 않는다고 되어있는데, 사용중임
  * MutualRule이 아닌 InactiveRule으로 바꿔야 할 것 같음
  * MutualRule의 설명이 둘이 함께 사용될 수 없도록 강제한다고 되어있는데, 실제 동작은 A, B간의 사용 우선순위만 잡아주는 정도라 설명이 변경되어야 할 것 같음
- [x] 마크 오브 나이트로드의 사출 확률이 60%가 아닌 37.5%임
  * http://www.inven.co.kr/board/maple/2297/49114
  * 표식을 새길 확률이 60%, 표식을 터트리는 공격은 표식을 새기지 않기 때문
- [x] 페이탈 베놈 도트뎀 적용되지 않고 있음
- [x] 퍼지 에이리어 - 보스 킬러 하이퍼가 적용되지 않고 있음
- [x] 다크로드의 비전서 막타 퍼뎀이 레벨당 36%씩 올라야 하는게 18%로 되어있음
- [x] 다크로드의 비전서에는 마크 오브 나이트로드가 사출되지 않음
- [x] 스프레드의 추가 줄기는 각 타수 하나하나가 별개의 사용판정으로 취급됨. 즉, `1*(5+5) + 15*1`로 계산되어 스프레드때 쿼드 한번에 16번의 마크 사출 판정이 들어감

**Comment by icepeng** [comment]
스프레드 스로우 도중에 풍마수리검 사용 안하게 적용하니 딜이 더 내려가는 것을 확인함. Rule 삭제

**Comment by oleneyl** [comment]
말씀하신대로 MutualRule이 아닌 InActiveRule로 적용되고 있었어야 하는게 맞을 것 같습니다.
