### ISSUE TITLE
신궁 피드백

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#112]
- [x] 크리티컬 리인포스에 있는 정체불명의 보정치

```
# 보마 = 20
# 메르 = 0
# 패파 = 20
# 신궁 = 20+6.6
# 와헌 = 20
# 윈브 = 55
# bonus = 직업별 보정 수치. 정확한 원리는 모름.
```

이렇게 되어있던데, @cheese98 님이 어떤 이유로 기입한 수치인지 확인하고 판단할 것.

- [x] 파이널 어택 미구현
  * 파이널 어택 코강 순위는 어떻게 되는가?
  * 파이널 어택은 스플릿 애로우 추가타에 발동되는가? -> 아마 안되는듯
- [x] 극딜버프 맞춰쓰기
- [x] 라스트맨 스탠딩, 디스턴싱 센스, 위크니스 파인딩은 공용 5차와 소환수에는 적용되지 않아야함
  * 패시브에서 빼고, 그냥 신궁 스킬들 퍼뎀에 다 곱하는게 맞을듯

**Comment by cheese98** [comment]
저도 그냥 받아쓴겁니다. 공용스킬 코드 통합 이전의 원래 소스코드에 직접 기록되어있던 수치들이예요.

**Comment by icepeng** [comment]
@cheese98 원래 소스코드라 함은 각 직업별로 따로 작성되어있던 크리인 수치를 말씀하시는게 맞나요? 확인해보겠습니다.

**Comment by cheese98** [comment]
네, 맞습니다. 수정할 때 값들의 출처를 확인할 시간이 없어서 그대로 올렸던 것 같습니다.

**Comment by icepeng** [comment]
514977c 커밋을 보고있는데 이유를 잘 모르겠네요... 확실해지기 전까진 그대로 두겠습니다.

**Comment by icepeng** [comment]
일단 왜 그런지는 알아냈습니다.

`self.char.get_modifier().crit`을 평가하면 버프가 적용되지 않은, 패시브만 적용된 크리티컬 확률이 나옵니다. 그래서 직업별로 버프로 증가하는 크리티컬 확률을 더해주는 것이네요.

하지만 신궁의 경우 `20+6.6`인 이유가 샤프 아이즈 20에다가 불스아이의 20을 가동률을 곱해서 적용한 것인데... 부정확할 수 밖에 없습니다.

**Comment by oleneyl** [comment]
크리인을 제외하고는 전부 반영된것이 맞나요?

**Comment by icepeng** [comment]
네 크리인은 일단 merge한 다음에 해당 직업들 일괄적으로 수정할거라 merge 부탁드립니다.

**Comment by icepeng** [comment]
아, 신궁 pr 이미 머지했군요

**Comment by icepeng** [comment]
그러면 크리인 관련 이슈는 따로 열도록 하겠습니다. close하겠습니다.
