### ISSUE TITLE
스킬 딜레이 질문

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#114]
* 스킬 딜레이는 풀공속 기준으로 기입하나요? 아니면, 스킬 데이터에 있는 값 그대로 기입하나요?
* 펫버프에 등록하는 버프 3개는 딜레이를 0으로 기입하면 되나요?

**Comment by cheese98** [comment]
* #39 를 참고하시면 될 것 같습니다.
* 현재 펫 버프는 가정하고 있지 않은 것 같습니다. DPM표 측정 기준을 정할 때 펫 개수에 대해서 논의할 필요가 있다고 생각합니다.

**Comment by icepeng** [comment]
감사합니다. 펫버프는 한번 쭉 돌면서 검토하겠습니다.
