### ISSUE TITLE
직업별 링크 스킬 별도 적용

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#115]
* 3모법 등 미하일 링크를 필수로 사용하는 직업은 다른 링크 하나를 빼고, 빛의 수호 버프와 사용 딜레이를 추가해야 합니다.
* 카데나 링크는 데미지 6%로 되어있는데, 12%로 할지 검토가 필요합니다.
* 신직업인 호영, 아델 링크를 추가해야 합니다.
* 크리티컬 확률이 필요없는 직업은 팬텀 링크를 사용하지 않습니다.
* 방어력 무시가 필요없는 직업은 루미너스, 제로, 호영 링크를 사용하지 않습니다.
* 모험가 해적 직업군에는 링크스킬 파이렛 블레스가 적용되지 않고 있습니다.
* 모험가 궁수 직업군에는 링크스킬 어드벤처러 큐리어스가 적용되지 않고 있습니다.

링크 스킬을 package로 해두지 않고, 링크 스킬들의 wrapper만 생성해두고 직업별로 get_passive_skill_list와 generate에 알아서 사용하도록 해두는게 나아보입니다.

스펙 수준에 따라 사용 링크가 조금씩 달라질 수는 있으나, 링크스킬 자동 최적화를 구현하지 않는 이상 위 방식으로 변경하는 것을 제안합니다.

**Comment by oleneyl** [comment]
네 이부분은 작업이 확실히 필요하겠네요.

**Comment by icepeng** [comment]
이 부분 작업 draft가 있습니다. pr 올려두겠습니다.

**Comment by icepeng** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/pull/125
