### ISSUE TITLE
팬텀 피드백

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#116]
- [x] 파이널 컷 벞지 적용 안되는중 (듀블과 마찬가지)
- [x] 조커에 추가 사출되는 느와르가 안들어가는중
  * 조커 구현 자체가 좀...이상함
- [x] 느와르 카르트의 타수가 크확 비례로 되어있는데, 쓸샾 실시간 적용이 안되어 0.9타로 계산되는 중
  * 쓸샾만 쓴다 가정하고 +0.1 해두면 될까요?
  * 느와르 카르트 적중시 쌓이는 저지먼트 스택도 0.9씩 되고 있었음
- [x] 템오카를 딜사이클에서 빼는게 dpm이 더 높게 찍히는데, 빼는게 맞는가?
  * 일단 빼고 생각
- [x] 블랙잭, 조커(시전), 마크 오브 팬텀 딜레이 정확한가? 위컴알 딜레이 그대로 박혀있는데 확인 필요
  * 블랙잭 투척 모션은 공속 적용되고, 나머지 둘은 안된다고 함
- [x] 로카피 쓰면 더 센지 확인 필요
- [ ] 얼드 선후딜 정확하게 넣어야 함

**Comment by cheese98** [comment]
2번의 경우는 `Joker.onTick(CarteNoir)`가 주석처리 되어있던걸 패치되면서 풀었네요. (671ac19) 제가 당시 사지방에서 올린거라 확인할 여력이 없었습니다...

**Comment by icepeng** [comment]
`Joker`, `JokerInit`, `JokerBuff`, `JokerDamage` 관계가 이상한 것 같습니다. 다른 키다운 속사 스킬 코드 참고해서 수정하겠습니다.

그리고, 조커 버프로 최종뎀을 뽑을 확률은 2/5가 맞나요?

**Comment by cheese98** [comment]
모든 카드의 확률이 동의하다는 가정 하에 맞습니다. (날카로운 검, 조커)

그런데 모래시계(스킬의 재사용 대기시간이 더 빠르게 감소)는 어떻게 해야 될지 모르겠네요. 지금으로서는 언스처럼 그냥 미구현하는게 나을 것 같네요.

**Comment by icepeng** [comment]
모래시계가 적용된다 해도 크게 달라질 것 같진 않습니다. 일단 주석에 모래시계 미적용 명시하겠습니다.

**Comment by icepeng** [comment]
로카피는 장판이 6개가 깔리는데, 1개만 맞으면 차이가 없다고 합니다.

허수아비 기준으로는 1개만 맞으므로 그대로 두겠습니다.
