### ISSUE TITLE
아델 제보 (오더)

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#119]
> 고생하십니다.
혹시 아델관련해서 아델의 오더 타격딜레이가 1140ms은 맞으나소환수로되있는거루 알고있습니다.
게더링 블로섬의 경우 아델이 타격을하는게아니라 '오더' 가 움직여 스킬을 사용하는 스킬이므로 게더링 블로섬 간에는 오더타격이 없어야 정상이고
오더를 재 소환 할 시에는 아델등에있는 크리에이션에서 나오기때문에 1140ms가 리셋되어 다시 공격주기가 들어가야합니다.
게더링 블로섬의경우도 오더의위치가 어쨋든 게더링으로 1회모으고나면 오더가 펼쳐진 후 다시치기에 1140ms의 딜레이가 리셋되어 적용되어야하는데 이것들이 적용이 되고있는건지 궁금합니다

**Comment by oleneyl** [comment]
- 들어가기에 앞서, 아델의 경우 현재 대규모의 피드백을 받아서 대대적인 변경이 있을 예정입니다.

해당사항은 아직 적용되고 있지 않습니다. 현재의 아델 계산안은 초기의 버전으로, 해당 부분을 반영하여 업데이트하도록 하겠습니다.

**Comment by icepeng** [comment]
> 아델 수정사항
1. 게더링 선 후딜 반영이 안되어있음
2. 블로섬 퍼템이 좀 다릅니다. 8명의적을 650으로 8번공격 블로섬이 겹칠시 최종뎀 25퍼 상실이라
(650×8)+(650×8×5×0.75)=24700
이 나와야합니다
3. 레조넌스 퍼뎀오류 (120+125+265)×6타 입니다
4. 스콜이 빠져있습니다 (아델바인드) 1000× 12타
5. 오더 퍼뎀 340%로 변경

> 블로섬은 오더 8개기준 32500%가 나와야합니다
오더 타격수가 10으로 되있는데 이게 혹시 타수는 아니죠?

추가 제보받은 내용입니다. 반영하는 데 참고해주세요.

**Comment by icepeng** [comment]
https://upload3.inven.co.kr/upload/2020/08/05/bbs/i13935219477.png

> 어빌이 재사용이라 테리토리나 엔버링크는 조절 가능한데 크리에이션은 어떻게 안되네요 참고만 해주세요
극딜시 그여축x 웨펖4 / 레조넌스,마커, 5차 다 만렙 / 레이스오브갓 극딜에서만 사용 / 엔버링크 2분 돌고 3번째 루인에 같이 씀 / 트리거 리인포스,보스킬러 대신 노빌리티,어트리뷰트 사용 / 첫 극딜 이후 오더3자루 크리에이션3쌍 쭉 적용

**Comment by icepeng** [comment]
* 게더링 선후딜 없는게 맞음
* 블로섬 적용함
* 레조넌스 적용함
* 스콜 있으나 안씀
* 오더 360%가 맞음
