### ISSUE TITLE
maplestats 홈페이지의 '유효 스공'이 어떤 값인가요?

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#120]
질문이 들어와서 여기 대신 올립니다. ([원문](https://gall.dcinside.com/mgallery/board/view/?id=danpoong&no=20391))

**Comment by oleneyl** [comment]
실스공 * (숙련도로 인한 보정치 (ex. 숙련도95%이면 *0.975) * (속성반감 보정치) 입니다.

**Comment by cheese98** [comment]
답변 감사드립니다. 실스공에 패시브 버프 스킬도 적용되나요?

**Comment by oleneyl** [comment]
네 모든게 적용된 스공입니다.

**Comment by cheese98** [comment]
답변 감사드립니다. 그런데 홈페이지 관련 문의를 여기서 계속 드리기가 좀 그런 것 같은데 혹시 홈페이지 문의 전용 공간을 만들어주실 수 있으신가요?

**Comment by cheese98** [comment]
죄송하지만 질문 하나만 더 드려도 될까요? 데미지%도 스공에 반영되는지 궁금합니다.

**Comment by icepeng** [comment]
일단 반영되는게 맞다고 생각하는데... 지금 굉장히 많은 버프/패시브들이 pdamage, boss_pdamage가 섞여서 사용되고 있습니다.

**Comment by oleneyl** [comment]
됩니다.

**Comment by oleneyl** [comment]
홈페이지 관련 문의 이슈를 하나 열어주시면 될 것 같습니다
