### ISSUE TITLE
캐릭터 스탯이 실시간 반영되는 스킬의 처리

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#123]
몇몇 스킬은 사용하는 순간의 캐릭터 스탯을 반영해 효과가 달라집니다.

하지만 지금 `chtr.get_modifier()`은 시뮬레이션 시작 전의 캐릭터 스탯만을 가져옵니다.

그렇기 때문에 시뮬레이션 도중에 사용된 메용, 쓸샾 등의 수치가 적용하기 위해서는 추가적인 보정을 해주거나, 아예 불가능할 수도 있습니다.

* 크리티컬 리인포스
  * 지속시간 동안 캐릭터의 크리티컬 확률에 따라 크뎀 상승량이 달라집니다.
  * 신궁은 불스아이를 사용하면 크확 20%가 늘어나므로, 크리인에 영향을 줍니다.
* 느와르 카르트
  * 크리티컬이 터지면 사출되므로, 크확에 비례해 타수가 달라집니다.
  * 어지간하면 100%를 맞추고, 도중에 크확이 변하는 요인은 거의 없으므로 괜찮습니다.
* 프레이, 리브라
  * 지속시간 동안 캐릭터의 주스탯에 따라 데미지, 최종데미지 상승량이 달라집니다.
  * 메용2, 웨폰퍼프를 고려하는 것은 지금 구조로는 불가능합니다.

이런 스킬들을 정확하게 구현하려면 스킬의 효과를 Lazy하게 처리할 방법이 필요합니다.

**Comment by oleneyl** [comment]
모든 요소의 실행과 결과의 리턴은 ```dpmModule.kernel.core.GraphElement._use()```메서드를 호출함으로서 이루어집니다.
그러므로 현존하는 모든 GraphElement의 _use메서드에 추가적인 인자를 제공하면 이 issue를 해결할 수 있습니다.

이를 달성하기 위해, 즉 스킬들의 효과가 Lazy하게 구현이 되고자 한다면 다음의 선택지가 존재합니다.

- _use() 메서드가 현재 실행 컨텍스트의 Character를 인자로 받는 것. (불가능)
  - 실행 컨텍스트의 상태는 Simulator가 가지고 있으며, Character는 시뮬레이션 동안 static하므로 거의 무의미합니다.

- _use() 메서드가 현재 실행의 컨텍스트 전체에 접근할 수 있는 Simulator 객체를 인자로 받는 것. 
  - 이 경우 _use()메서드의 호출로 인해 시뮬레이션 환경이 훼손당할 수 있습니다.

- _use() 메서드가 현재 실행 컨텍스트의 ```modifier```를 인자로 받는 것.
  - 이 경우 다른 실행 컨텍스트에는 Lazy한 접근이 불가능합니다.
  - 이후 이와 같은 사안이 있을때, 전체 GraphElement의 _use() 메서드를 다시 재정의해야 합니다.

어떤 구현안이 제일 최선의 선택인지 여쭙고 싶습니다.

**Comment by icepeng** [comment]
하나같이... 두려운 선택지인데, 지금 당장은 마지막 구현안이 괜찮다고 생각합니다.

**Comment by oleneyl** [comment]
#127 구현완료, merge했습니다.
context에 접근하고자 하는 경우, 해당 GraphElement에서
- `self.enable_referring_runtime_context()` 를 호출하고
- _use() 메서드를 _use(self, rem=0, red=0, **kwargs) 꼴로 override해주시면 됩니다.

- 예시

  ```python
  class CriticalReinforceWrapper(core.BuffSkillWrapper):
    def __init__(self, vEhc, character : ck.AbstractCharacter, num1, num2, bonus):
        skill = core.BuffSkill("크리티컬 리인포스", 780, 30 * 1000, cooltime = 120 * 1000).isV(vEhc, num1, num2)
        super(CriticalReinforceWrapper, self).__init__(skill)
        self.char = character
        self.inhancer = (20 + vEhc.getV(num1, num2))*0.01
        self.bonus = bonus
        self.enable_referring_runtime_context()

    def _use(self, rem=False, red=True, **kwargs):
        print('크리인 작동 확인', kwargs)
        x = super(CriticalReinforceWrapper, self)._use(rem=rem, red=red)
        return x
        
    def get_modifier(self):
        if self.onoff:
            return core.CharacterModifier(crit_damage = self.inhancer * max(0,self.char.get_modifier().crit+self.bonus))
        else:
            return self.disabledModifier

  ```

```bash
>>> 크리인 작동 확인 {'runtime_context_modifier': crit rate : 100.0, crit damage 91.5
pdamage : 147.2, pdamage_indep -21.3
stat_main : 4896.8, stat_sub 2198.0
pstat_main : 226.0, pstat_sub 10.0
boss_pdamage : 324.0, armor_ignore 93.9
att : 1625.0, patt 74.0
Fixed stat : main 7890.0, sub 30.0
damageFactor : 23040746.0}
```
