### ISSUE TITLE
키네시스 피드백

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#130]
- [x] 싸이킥 오버 지속중에는 pp가 3칸 이하가 될 때 까지 메테리얼 사용하는게 더 세다고 함
- [x] '정신강화' 스킬이 '감정강화'로 되어 있습니다. (단순오타)
- [x] 싸이킥 드레인 시전딜레이가 690ms로 표기되어 있는데 풀공속 기준으로는 510ms입니다.
  * 드레인은 이 외에도 공격 간격 (틱 간격)이 클라이언트 상으로는 500ms이고 실측 기준으로는 지속시간 내 19틱이 들어가는데(클라와 실측이 다름) 틱 간격이 660ms로 되어 있습니다.
- [x] 텔레키네시스 5차 강화로 최종데미지 2%씩 증가로 표기되어 있는데 3%입니다.
- [x] 얼티메이트 bpm 공격 간격이 660ms로 표기되어 있는데 클라이언트상 600ms고 실제로도 3초당 5번씩 들어갑니다.
- [x] 싸이킥 그랩은 싸이킥 그랩과 싸이킥 스매싱으로 이루어져 있으며, 싸이킥 그랩은 물체를 들어올리는 동작, 싸이킥 스매싱은 들어올린 물체로 공격하는 동작입니다.
  * 물체를 그랩으로 한 번 들어올린 후 스매싱을 5번 사용하거나 샷을 1번 사용하면 물체를 다시 들어올려야 합니다. 즉 (구현이 어떻게 될진 모르겠지만) 최종적으로는 싸이킥 그랩의 시전 수가 [(싸이킥 샷의 시전수) + ((싸이킥 스매싱의 시전수/5)의 올림)]만큼 나와야 합니다.
  (스매싱을 4번 쓴 뒤 샷을 쓰면 그랩 시전 수를 줄일 수 있지만, 스매싱 직후 샷을 쓰면 샷의 타점이 변경되어 타수가 낮아지는 현상이 있음)
  * 다만 kinesis.py 에서는 싸이킥 그랩의 딜레이와 관련된 부분을 찾을 수 없었습니다.
  스매싱, 그랩, 샷의 딜레이는 전부 계산상으로 널리 알려진 것과 달랐습니다. 이 부분은 다음 번에 제대로 측정할 예정입니다
- [x] 토네이도의 시전딜레이가 풀공속 기준 540ms인데 720ms로 되어 있습니다.
  * 토네이도 마지막 폭발 (코드상 "싸이킥 토네이도(2)")의 타격 횟수가 10번씩 3회 발생인데 6번씩 3회 발생으로 표기되어 있습니다.
- [x] 무빙매터의 시전딜레이가 풀공속 기준 480ms인데 630ms로 되어 있습니다.
- [x] 싸이킥 불릿 또한 시전하기 위해선 그랩으로 물체를 든 상태여야 합니다. (5번설명참조)
  * 또한 불릿의 시전 딜레이가 풀공속 기준 420ms인데 570ms로 되어 있습니다.
- [x] 싸이킥오버의 pp회복이 초당 1로 표기되어 있는데 750ms당 1입니다. (30초 지속 중 최소 40 회복, 실제로는 서버렉을 받아 더 회복한 적도 있음)
- [x] 매태리얼과 트레인의 시전 딜레이도 정확한 측정이 필요합니다.
- [x] 트레인의 공격 횟수가 틱당 6번인데 4번으로 표기되어 있습니다.
- [x] 싸이킥 토네이도의 폭발 데미지가 20초 후에 들어가야 함
- [x] 싸이킥 차지의 증가량이 근사치로 되어있음
- [x] 싸이킥 오버 상태에서도 얼티메이트 스킬의 사용 제한이 그대로임
- [x] pp는 발동 딜레이가 끝난 후가 아닌 시전 시점에 변동됨

[4분 딜사이클 영상](https://www.youtube.com/watch?v=KsBTqtza3QI&feature=youtu.be)

[전분1](https://user-images.githubusercontent.com/12782606/89271163-4a0c6500-d677-11ea-9544-ff976a6d8c54.jpg)
[전분2](https://user-images.githubusercontent.com/12782606/89271170-4bd62880-d677-11ea-915e-813221b7e400.jpg)
[전분3](https://user-images.githubusercontent.com/12782606/89271175-4c6ebf00-d677-11ea-8a63-870b637e6ebe.jpg)
[전분4](https://user-images.githubusercontent.com/12782606/89271178-4d075580-d677-11ea-8f41-c900750d0bde.jpg)
[전분5](https://user-images.githubusercontent.com/12782606/89271184-4e388280-d677-11ea-8363-63ea654897de.jpg)

점유율은 코강 상태 생각해서 봐야함

**Comment by icepeng** [comment]
(딜점유율1)[https://media.discordapp.net/attachments/740249103404892202/740249221017370754/MapleStory_2020-08-05_1_34_32.png?width=880&height=495]
(딜점유율2)[https://media.discordapp.net/attachments/740249103404892202/740249239543611392/MapleStory_2020-08-05_1_34_36.png?width=880&height=495]
(딜점유율3)[https://media.discordapp.net/attachments/740249103404892202/740249243763343480/MapleStory_2020-08-05_1_34_39.png?width=880&height=495]
(딜점유율4)[https://media.discordapp.net/attachments/740249103404892202/740249247298879628/MapleStory_2020-08-05_1_34_44.png?width=880&height=495]

**Comment by icepeng** [comment]
1.무빙매터 + 엔버링크
2.토네이도 + 이계 여신의 축복

묶어서 사용, 트레인은 싸이킥 오버 도중 2번정도 사용 가능

맥뎀 막히는 스펙에선 샷>메테리얼, 안막히면 메테리얼>샷

무빙매터, 토네이도 얼마 안남았는데 싸이킥 오버 얼마 안남았으면 기다렸다가 사용

**Comment by djaphics** [comment]
안녕하세요. 인벤에서 보고 도움이 되고자 글 남깁니다. 
코드를 읽을 줄은 모르지만 최대한 유추해서 제가 알고 있는 것과 다른 부분을 알려드리려고 합니다 .

1. '정신강화' 스킬이 '감정강화'로 되어 있습니다. (단순오타)

2. 싸이킥 드레인 시전딜레이가 690ms로 표기되어 있는데 풀공속 기준으로는 510ms입니다. 
드레인은 이 외에도 공격 간격 (틱 간격)이 클라이언트 상으로는 500ms이고 실측 기준으로는 지속시간 내 19틱이 들어가는데(클라와 실측이 다름) 틱 간격이 660ms로 되어 있습니다. 

3. 텔레키네시스 5차 강화로 최종데미지 2%씩 증가로 표기되어 있는데 3%입니다. 

4. 얼티메이트 bpm 공격 간격이 660ms로 표기되어 있는데 클라이언트상 600ms고 실제로도 3초당 5번씩 들어갑니다. 

5. 싸이킥 그랩은 싸이킥 그랩과 싸이킥 스매싱으로 이루어져 있으며, 싸이킥 그랩은 물체를 들어올리는 동작, 싸이킥 스매싱은 들어올린 물체로 공격하는 동작입니다.
물체를 그랩으로 한 번 들어올린 후 스매싱을 5번 사용하거나 샷을 1번 사용하면 물체를 다시 들어올려야 합니다. 즉 (구현이 어떻게 될진 모르겠지만) 최종적으로는 싸이킥 그랩의 시전 수가 [(싸이킥 샷의 시전수) + ((싸이킥 스매싱의 시전수/5)의 올림)]만큼 나와야 합니다. 
(스매싱을 4번 쓴 뒤 샷을 쓰면 그랩 시전 수를 줄일 수 있지만, 스매싱 직후 샷을 쓰면 샷의 타점이 변경되어 타수가 낮아지는 현상이 있음) 
다만 kinesis.py 에서는 싸이킥 그랩의 딜레이와 관련된 부분을 찾을 수 없었습니다. 
스매싱, 그랩, 샷의 딜레이는 전부 계산상으로 널리 알려진 것과 달랐습니다. 이 부분은 다음 번에 제대로 측정할 예정입니다

6. 토네이도의 시전딜레이가 풀공속 기준 540ms인데 720ms로 되어 있습니다. 
토네이도 마지막 폭발 (코드상 "싸이킥 토네이도(2)")의 타격 횟수가 10번씩 3회 발생인데 6번씩 3회 발생으로 표기되어 있습니다. 

7. 무빙매터의 시전딜레이가 풀공속 기준 480ms인데 630ms로 되어 있습니다. 

8. 싸이킥 불릿 또한 시전하기 위해선 그랩으로 물체를 든 상태여야 합니다. (5번설명참조) 또한 불릿의 시전 딜레이가 풀공속 기준 420ms인데 570ms로 되어 있습니다. 

9. 싸이킥오버의 pp회복이 초당 1로 표기되어 있는데 750ms당 1입니다. (30초 지속 중 최소 40 회복, 실제로는 서버렉을 받아 더 회복한 적도 있음) 

10. 매태리얼과 트레인의 시전 딜레이도 정확한 측정이 필요합니다. 

11. 트레인의 공격 횟수가 틱당 6번인데 4번으로 표기되어 있습니다.
 
12. pp최대 포인트와 관련하여, pp최대치가 40으로 변경되었는데 에버싸이킥 설명에는 30포인트가 증가한다고 쓰여 있습니다. 이것이 실적용도 +30인지 +40인지 잘 모르겠습니다. 

[https://www.youtube.com/watch?v=JlykfOB1XdY](url)
간단하게 관련 영상 찍어봤습니다. 이외에 제가 또 도움이 될만한 게 있으면 좋겠습니다.

**Comment by icepeng** [comment]
제보 감사합니다. 잠시 후 해당 내용들 적용해보겠습니다.

**Comment by djaphics** [comment]
아 12번 표현을 애매하게 했네요. 하이퍼스탯으로 pp 최대치를 찍을 경우 pp 최대치가 40이 되는데, 코딩상에서 pp 최대치는 30+10이라고 적혀 있는데 에버사이킥 옆 설명에는 pp 30 회복이라고 적혀 있어서 실제 시뮬레이션이 될 때 30 회복인지 40 회복인지를 여쭙는 것이었습니다. 

실제로는 사용 즉시 pp가 최대치까지 찹니다.

**Comment by icepeng** [comment]
아, 40으로 적용되고 있습니다. 코드 고칠때 주석도 동기화를 잘 해줘야 하는데 까먹기가 쉬워서...

**Comment by icepeng** [comment]
얼티메이트 - 트레인의 퍼뎀이 180%로 되어있는데, 실제로는 220%인것 같습니다.

**Comment by icepeng** [comment]
싸이킥 스매싱2의 기본 딜레이는 600ms로 풀공속 적용하면 450ms가 되는데, 데이터에는 540ms로 되어있습니다. 이미 그랩으로 인한 지연을 반영한 것 같은데, 그래도 실제 동작에 맞게 그랩-스매싱으로 바꿔보겠습니다.

**Comment by icepeng** [comment]
생각보다 들어올리고-5회타격 반복하는게 간단하지가 않네요.

간단하게 하면 들어올리고-5회타격을 강제로 연계해서 사용하는건데, 이러면 중간에 끊고 다른 스킬을 쓸 수 없어서 오차가 생깁니다.

하려면 할 수는 있겠는데 일단 평균치 딜레이로 적용해두고, 나중에 다시 보겠습니다.

**Comment by icepeng** [comment]
아 트레인 데미지가 틱마다 5%씩 감소하는거였군요. 퍼뎀 부분은 롤백하겠습니다.

**Comment by icepeng** [comment]
영상을 뒤늦게 확인했습니다. 영상에 있는 딜레이로 일괄 수정하겠습니다.

**Comment by djaphics** [comment]
딜레이 부분은 제가 내일 다시 한 번 녹화해서 프레임 단위로 세보겠습니다.

**Comment by icepeng** [comment]
감사합니다. 제가 수정된 딜레이 기준으로 했을때 샷 봉인하고 메테리얼만 쓰는게 더 강했는데, 원래 이런가요? 10초마다 방깎 디버프용으로 샷 쓰는것조차 딜이 떨어졌습니다.

**Comment by icepeng** [comment]
```
SKILL 싸이킥 그라운드2(공격) share is 9626884991.948708,  0.0608 percent
SKILL 텔레키네시스 share is 448848914834.508484,  2.8330 percent
SKILL 싸이코 브레이크(공격) share is 76909263504.214859,  0.4854 percent
SKILL 싸이킥 드레인 share is 705523687250.719360,  4.4531 percent
SKILL 싸이킥 포스3 share is 42848388645.177406,  0.2704 percent
SKILL 얼티메이트-B.P.M. share is 2740812767957.971680,  17.2994 percent
SKILL 싸이킥 토네이도 share is 431332464784.383728,  2.7225 percent
SKILL 싸이킥 토네이도(1) share is 8503302608.848441,  0.0537 percent
SKILL 싸이킥 토네이도(2) share is 285886898056.111328,  1.8045 percent
SKILL 얼티메이트-무빙 매터 share is 2254249424994.941895,  14.2283 percent
SKILL 얼티메이트-무빙 매터(최종) share is 110035290167.152206,  0.6945 percent
SKILL 얼티메이트-트레인 share is 207988395284.413086,  1.3128 percent
SKILL 에버 싸이킥 share is 31445821633.090508,  0.1985 percent
SKILL 에버 싸이킥(최종) share is 8132266423.718197,  0.0513 percent
SKILL 얼티메이트-메테리얼 share is 5271703862284.656250,  33.2738 percent
SKILL 싸이킥 그랩 share is 3209543050920.365234,  20.2579 percent
키네시스 528113022811.3655
```

일단 유니온 6000 기준으로 점유율은 이렇게 나옵니다.

샷은 어떤 식으로 써도 더 약해서 아예 사용하지 않습니다.

**Comment by djaphics** [comment]
허수아비 기준 (샷 히트율 80%) 일때는 매태리얼이 더 센게 맞습니다. 
제가 예전에 허수아비 때렸을 때는 매태리얼 사이클이 샷 히트율 87% 정도랑 비슷한 딜이 나왔던걸로 기억합니다.

**Comment by icepeng** [comment]
트레인 점유율이 전분 자료들에 비해 좀 적은데, 혹시 싸이킥 오버 상태가 아니더라도 계속 사용하는게 좋은가요?

**Comment by djaphics** [comment]
네 제가 허수아비 칠때는 계속 유지하는게 더 좋았었습니다. 


아 그리고 그랩, 스매싱, 샷 딜레이 문제 원인 찾았습니다. 
그 스킬들이 2d스켈레톤 기반인가 뭔가 하는거 때문에 (저도 뭔진 모름)
사용한 구체가 완전히 사라져야 다음 그랩을 집을 수 있게 됩니다. 
그래서 샷 이후 다른 스킬을 쓰면 정상적으로 660ms 딜레이가 적용되는데
샷 이후 다시 그랩을 들 때는 샷 구체가 완전히 사라져야 다시 그랩이 들려서 샷 딜레이 660ms + 멍때리는시간 240ms 이런식으로 찍힙니다. 
(구체가 사라지는 게 서버렉을 받아서 사용할 때마다 딜레이가 달라짐)
스매싱 또한 한대 때린 후 물체가 다시 원위치가 되어야 다음 스매싱이 나가서 
이론상 값인 450ms가 아닌 540ms로 적용되고 있었습니다. 
요약하자면 그랩 구현 문제까지 고려하여 스매싱의 딜레이를 540 + (180/5) ms, 샷의 딜레이를 900 + 180 ms로 하는 것이 좋을 것 같습니다. 

매태리얼 또한 연사에 제약이 있는 것 같았습니다. 620ms가 찍히는데, 이 부분은 저도 원인을 모르겠습니다. 
(이론상 딜레이 600ms)

나머지 스킬들은 전부 이론상 값이 잘 적용되고 있습니다. (오차범위가 3ms 미만)

다만 포스, 그라운드, 그랩 등 딜레이가 엄청 짧은 스킬의 경우
딜레이가 30ms씩 높게 나왔는데 그 이유가
스킬을 시전하자마자 매태리얼을 써서 스킬 시전 시작~매태리얼 시전 직전까지 프레임을 세는 방식으로 딜레이를 재다보니
딜레이가 너무 짧으면 입력지연때문에 매태리얼이 바로 시전이 되지 않아서 그런 것 같습니다. 
이 셋은 이론상 딜레이 (포스 그라운드 270ms, 그랩 180ms) 가 맞는 것 같습니다.

**Comment by icepeng** [comment]
감사합니다. 말씀해주신 부분 최대한 반영해 보았습니다.

```
SKILL 싸이킥 그라운드2(공격) share is 9613657938.026857,  0.0614 percent
SKILL 텔레키네시스 share is 443297133434.136536,  2.8293 percent
SKILL 싸이코 브레이크(공격) share is 76909263504.214859,  0.4909 percent
SKILL 싸이킥 드레인 share is 701268676571.786743,  4.4757 percent
SKILL 싸이킥 포스3 share is 42996584557.317841,  0.2744 percent
SKILL 얼티메이트-B.P.M. share is 2741266804237.297363,  17.4956 percent
SKILL 싸이킥 토네이도 share is 431448862858.896179,  2.7536 percent
SKILL 싸이킥 토네이도(1) share is 8503302608.848441,  0.0543 percent
SKILL 싸이킥 토네이도(2) share is 285886898056.111328,  1.8246 percent
SKILL 얼티메이트-무빙 매터 share is 2117720116960.375000,  13.5159 percent
SKILL 얼티메이트-무빙 매터(최종) share is 102645719607.381180,  0.6551 percent
SKILL 얼티메이트-트레인 share is 661244818276.653564,  4.2203 percent
SKILL 에버 싸이킥 share is 31445821633.090508,  0.2007 percent
SKILL 에버 싸이킥(최종) share is 8132266423.718197,  0.0519 percent
SKILL 얼티메이트-메테리얼 share is 4838908834270.868164,  30.8834 percent
SKILL 싸이킥 그랩 share is 3167037715738.205566,  20.2130 percent
```

변경 후 점유율은 이정도로 나옵니다.

그랩 점유율이 대부분의 전분보다 많이 나오는 점이 좀 걸리네요.

**Comment by djaphics** [comment]
그랩하고 트레인의 비율이 이상하긴 하네요. 예전에 제가 3분 측정했을때는 (오버가 210초라 3분 측정이 부정확한 것을 감안하더라도) 트레인이 4%대가 나오진 않았었습니다. 
https://www.youtube.com/watch?v=uM5pnDNrlhs (테스트서버 영상으로 로 오브 그라비티가 지금보다 약할 때입니다. 제외하고 보시면 됩니다.)

**Comment by icepeng** [comment]
음 제가 다른 분께 부탁드려서 받은 전분(첫 댓글)에는 트레인 비율이 4%대가 나오긴 했습니다.  아무래도 차징과 에버싸이킥을 어떻게 배분하냐에 따라서 그랩/트레인/메테리얼 딜점유율이 많이 바뀌는거 같네요.

**Comment by djaphics** [comment]
어 저건.. 4분동안 쳤는데 제가 3분동안 친거보다 트레인을 적게 쓰셨네요. 
제가 3분동안 186틱이 나왔는데 저분은 4분동안 111틱이 나오셨어요.

다시 볼수록 위에 점유율이 이해가 안 가긴 하네요. 트레인을 12초마다 칼같이 리필한다면 3분에 최대 255틱까지 가능한데, 코딩상에서는 오히려 제가 허수아비 친 것의 반밖에 나오지 않아서요.

**Comment by icepeng** [comment]
틱 수는 적은데 점유율이 오히려 높다는건 어디 한군데는 잘못되었을 확률이 크다는 뜻이네요. 눈물이 납니다.

**Comment by icepeng** [comment]
아마 pp가 7이 찰때마다 메테리얼을 계속 쓰다보니 pp 수급기가 돌지 않고 있을때는 트레인 리필이 잘 되지 않는거 같습니다. 잠시 하던거 정리하고 트레인 틱 수 뽑아오겠습니다.

**Comment by icepeng** [comment]
30분간 816틱이 들어가고 있네요. 3분이라 치면 81~82니까 낮긴 하네요. 이건 치는 방식의 차이 정도로 받아들일수 있을까요, 아니면 무조건 수정해야 하는 부분일까요? 키네시스는 pp때문인지 사람마다 얼티메이트 점유율이 다 다르게 찍히네요...

**Comment by djaphics** [comment]
사실 저도 이 부분이 궁금해서 이번 프로젝트를 기대하던 중이었습니다. 
제가 허수아비 칠 때는 트레인 비중을 높이면 높일수록 세졌는데, 이게 제 체감 때문인지 아니면 기계가 해도 트레인 비중이 높아질수록 세지는지..

혹시 수고스럽겠지만 사이클을 바꾸는 방안이 있을까요? 예를 들면 트레인도 포스처럼 지속시간이 끝나면 최우선으로 써준다던지.. 이게 아무래도 pp제약이랑 시간제약이 두 개가 걸리다 보니까 구현이 어려울 것 같긴 한데, 여유가 되신다면 한번 해주신다면 감사하겠습니다.

**Comment by icepeng** [comment]
"예를 들면 트레인도 포스처럼 지속시간이 끝나면 최우선으로 써준다" 이 부분이 구현이 참 애매합니다... 소모 자원이 MP면 간단한데 PP다보니 미래를 예측해서 미리 여유분을 남겨두는게 쉽질 않겠네요. 그래도 가능한 시도해보겠습니다.

**Comment by icepeng** [comment]
러프하게 "트레인 틱뎀이 들어가는 중에만 메테리얼을 사용" 이라는 조건을 추가했습니다.

```
SKILL 싸이킥 그라운드2(공격) share is 9613657938.026857,  0.0587 percent
SKILL 텔레키네시스 share is 461074021638.024048,  2.8165 percent
SKILL 싸이코 브레이크(공격) share is 76909263504.214859,  0.4698 percent
SKILL 싸이킥 드레인 share is 703337375329.037842,  4.2963 percent
SKILL 싸이킥 포스3 share is 42654100859.137283,  0.2606 percent
SKILL 얼티메이트-B.P.M. share is 2740590039405.250000,  16.7409 percent
SKILL 싸이킥 토네이도 share is 432030853231.457825,  2.6391 percent
SKILL 싸이킥 토네이도(1) share is 8411242313.552355,  0.0514 percent
SKILL 싸이킥 토네이도(2) share is 282791767438.398071,  1.7274 percent
SKILL 얼티메이트-무빙 매터 share is 2495680557715.773438,  15.2449 percent
SKILL 얼티메이트-무빙 매터(최종) share is 120903455983.081268,  0.7385 percent
SKILL 얼티메이트-트레인 share is 1600717271857.809326,  9.7780 percent
SKILL 에버 싸이킥 share is 31445821633.090508,  0.1921 percent
SKILL 에버 싸이킥(최종) share is 8132266423.718197,  0.0497 percent
SKILL 얼티메이트-메테리얼 share is 4050283540674.923340,  24.7412 percent
SKILL 싸이킥 그랩 share is 3306044575200.046875,  20.1950 percent
```

6000 기준 5223억 -> 5457억으로 유의미한 증가가 보입니다. 이정도면 체감이 들어맞았다고 생각할 수 있겠네요.

이것도 트레인을 12초마다 리필하지는 않아 30분 2550틱까진 가지 않고, 1984틱으로 찍히고 있습니다.

여기서 더 늘리면 딜량이 더 증가하는지도 실험해 보겠습니다.

**Comment by icepeng** [comment]
| 전분 | 보정 | 시뮬 | delta
-- | -- | -- | -- | --
메테 | 23.08% | 26.31% | 24.13% | -2.18%
bpm | 15.76% | 17.96% | 17.89% | -0.07%
매터 | 13.88% | 15.82% | 15.59% | -0.24%
그랩 | 13.78% | 15.71% | 19.69% | 3.99%
트레인 | 9.09% | 10.36% | 10.45% | 0.09%
토네이도 | 5.04% | 5.74% | 4.31% | -1.44%
텔레키네 | 3.15% | 3.59% | 2.75% | -0.84%
드레인 | 3.01% | 3.43% | 4.19% | 0.76%
브레이크 | 0.53% | 0.60% | 0.46% | -0.15%
에버싸이킥 | 0.28% | 0.32% | 0.24% | -0.08%
포스3 | 0.08% | 0.09% | 0.25% | 0.16%
그라운드2 | 0.05% | 0.06% | 0.06% | 0.00%

"트레인 틱뎀이 들어가는 중에만 메테리얼을 사용" 적용시 전분과 시뮬 점유율 정리입니다.

시뮬에서 쓰지 않은 스인미, 이계축복, 로오그 점유율을 제외하고 보정한 점유율과의 비교입니다.

**Comment by icepeng** [comment]
| 전분 | 보정 | 시뮬 | delta
-- | -- | -- | -- | --
메테 | 23.08% | 26.31% | 23.13% | -3.18%
bpm | 15.76% | 17.96% | 17.83% | -0.13%
매터 | 13.88% | 15.82% | 15.21% | -0.61%
그랩 | 13.78% | 15.71% | 19.76% | 4.05%
트레인 | 9.09% | 10.36% | 11.85% | 1.49%
토네이도 | 5.04% | 5.74% | 4.76% | -0.98%
텔레키네 | 3.15% | 3.59% | 2.75% | -0.84%
드레인 | 3.01% | 3.43% | 4.17% | 0.74%
브레이크 | 0.53% | 0.60% | 0.46% | -0.15%
에버싸이킥 | 0.28% | 0.32% | 0.23% | -0.08%
포스3 | 0.08% | 0.09% | 0.26% | 0.16%
그라운드2 | 0.05% | 0.06% | 0.06% | 0.00%

"트레인 틱뎀이 들어가는 중이며, 2초 이상 남았을 시 메테리얼을 사용" 적용시 전분과 시뮬 점유율 정리입니다.

전분에 비해 트레인 사용 횟수가 더 늘어났고, 이에 따라 트레인 점유율이 좀 높게 찍힙니다.

이쪽이 딜량은 미세하게 더 높습니다.

**Comment by djaphics** [comment]
정말 고생 많으셨습니다. 감사합니다.  트레인 발동중에만 매태 사용은 생각지도 못했네요. 
정말 안정화가 잘 된 것 같네요. 

이계축복 30렙에 pp최대치 40 기준으로 이계축복 한번의 pp회복 기댓값이 19.2나 되다보니 
이계축복을 넣는 것만으로도 그랩 비중이 유의미하게 떨어지긴 합니다. 
그걸 생각해 보면 그랩 비중도 정상인 것 같습니다.

**Comment by icepeng** [comment]
아 이계 축복 영향을 생각하지 못했네요. 그랩 점유율은 추후 메용2류가 적용된 후에 다시 살펴보기로 하고, 여기서 코드 머지하겠습니다.

상세한 피드백 감사합니다. 정말 많은 도움 되었습니다.
