### ISSUE TITLE
데슬 문의 (인벤)

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#131]
![dpm](https://upload3.inven.co.kr/upload/2020/08/03/bbs/i14442236588.png)

데슬 DPM 제작자입니다(엑셀 기반 제작).

DPM 절댓값 자체는 스탯창 데미지% 등이 부정확한 관계로 직접 비교가 어려우나(기준스펙을 상세하게 알려주신다면 대입가능), 딜점유율을 대충 비교하다가 일부 추정되는 문제점들이 생겨서 알려드립니다. 보뎀합은 비슷하나 스펙 격차에 의해 생겼을 수도 있으니 제가 잘못 생각했을 수도 있는 점은 양해 부탁드립니다!

1) 어웨슬래시에 리메인이 적용되고 있습니까? 혹시라도 최종뎀 10%가 적용되고 있다면, 어웨슬래시에는 미적용되어야 합니다.
2) 어웨 OFF 타임에 슬래시 1타가 미적용되고 있는 것 같은데, 사이클을 1슬래 1서버 6~7임팩으로 고친다면 리메인 풀유지를 통해 딜상승을 조금이라도 더 이끌어낼 수 있습니다.
3) 메타모포시스가 V코어 미강화인가요? 풀힛 기준 딜점유율이 비정상적으로 낮습니다. 비율이 2.3이 나오는 것으로 보아 미강화를 의도하셨을 가능성도 있는 것 같기는 하네요.
4) 메용2 계열 스킬들이 모두 미반영되어 있는지는 모르겠으나, 분명 터져야 할 이계의 공허 딜이 0입니다.
5) 크라이 점유율이 비정상적으로 높아 보입니다. 혹시 비-어웨 타임에도 크라이가 사용되나요? 데슬은 임팩트만으로도 이블 토쳐를 발동시킬 수 있습니다.
6) 오라웨폰에 블블이 안 터지고 있나요? 오라웨폰은 블블 효과를 받습니다(데미지 비율도 188%로 거의 타당함).

**Comment by icepeng** [comment]
* 리메인타임 리인포스 자체가 제대로 적용이 안되는 것 같습니다
* 메타모포시스 강화 (4,2)로 되어있는데 이러면 6000에선 강화가 안되나요?
* 비-어웨 타임에 크라이 사용 안하도록 Constraint 걸어야겠습니다.
* 오라 웨폰에 블블은 생각도 못하고 있었는데... `create_auxilary_attack`으로 구현 가능할까요?

@oleneyl

**Comment by oleneyl** [comment]
- [ ] 리메인타임 리인포스 : 아예 미적용중. 적용 필요
- [ ] 비-어웨상태 딜사이클 정정 필요
- [ ] 메타모포시스 강화 필요
- [ ] 메용2 현재미반영중
- [ ] 크라이 딜 사이클을 알아야 함
- [ ] 오라웨폰 블블 미반영중

**Comment by oleneyl** [comment]
`create_auxilary_attack` 구현체를 보아야 알 것 같습니다

**Comment by icepeng** [comment]
메용2는 전직업 스킬 검토 이후 일괄 적용 할 예정이라고 답변했습니다.

크라이는 이블 토쳐 패시브 발동을 위해 섞어주는데, 데몬 임팩트에 슬로우가 달려있기 때문에 비-어웨 타임에는 크라이가 필요 없는것 같습니다.

**Comment by icepeng** [comment]
추가 제보

내용을 살짝만 더 추가하자면

3) 유니온 7천 기준이라 아마 강화대상은 맞는 것 같은데.. 소환이 찍혀있어서 한줄 더 적어드리자면 메타는 소환수가 아닌 "캐릭터 공격"취급이라 역시 블블이 발동됩니다(그래서 실제로 인핸스 미사용 시 공반몹 옆에만 가도 알아서 사망하는 흥미로운 현상이 발생하지요). 얼추 2배 언저리면 블블 미적용도 가정이 가능해지기에..

5) 대신 크라이 미사용 시 방무 15% 한 줄이 날아갑니다(임팩 슬로우에는 방깎이 없습니다).

**Comment by icepeng** [comment]
크라이를 계속 사용하는것과 어웨OFF시 미사용 중 dpm이 높은 쪽으로 적용하면 될거 같습니다.

메타모포시스(소환)에 블블 미적용은 수정해야 합니다.

**Comment by cheese98** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/pull/108

오라웨폰 블블은 공용스킬 클래스를 상속받아서 쉐파코드를 끼워넣는 식으로 구현해봤습니다. 점유율로 계산한 예상수치와 거의 일치합니다.
