### ISSUE TITLE
유니온 7천 및 8천 무기류 에디

### ISSUE THREAD

**Issue by sumin-kim-crypto** [oleneyl/maplestory_dpm_calc#132]
maplestats 사이트에서 설명을 보니
7천은 무기류 에디공21, 8천은 무기류 에디공15로 적혀있습니다. 단순 오타인가요? 아니면 실제 적용에도 문제가 있는건가요?

**Comment by icepeng** [comment]
확인해보니 정말 8천 무기류 에디공 15로 적용되어있네요. 수정하겠습니다.
