### ISSUE TITLE
은월 로디드 다이스 관련 질문

### ISSUE THREAD

**Issue by kmsiapps** [oleneyl/maplestory_dpm_calc#133]
https://github.com/oleneyl/maplestory_dpm_calc/blob/f6b47fcf29a5b1544a1e330d0587246e75bbaded/dpmModule/jobs/eunwol.py#L96 에서 pdamage가 20 * 4 / 3으로 되어 있는 이유가 뭔지 궁금합니다.

아마 더블 럭키 다이스를 고려한 확률 계산으로 추측했는데(정확히 왜 4/3이 나오는지는 모르겠지만),
이게 맞다면 은월의 경우 한 개의 주사위만 던질 수 있고 보통 로디드 다이스를 통해 데미지로 고정하므로 20으로 두는 게 맞을 것 같습니다.

수정: 숙련도 관련해서 질문이 더 있었는데, 코드를 더 읽어봐야할 것 같네요..ㅎㅎ

**Comment by icepeng** [comment]
오류가 맞는 것 같습니다.
럭키 다이스 관련해서 코드 한번 정리하겠습니다.
제보 감사합니다.
