### ISSUE TITLE
윈브 질문

### ISSUE THREAD

**Issue by OniOniOn-** [oleneyl/maplestory_dpm_calc#134]
1. 천공의 노래 속사기 시작 딜레이 300ms 가 적용되고 있나요?
2. 핀포인트 피어스 onAfter에 TriflingWhim, StormBringer가 전달되지 않는데 인게임에서는 둘 다 발동됩니다.
3. 주석의 '오더스 적용 필요'는 쓸오더 사용 시 퍼뎀을 알아야 하는 것인가요? 클라 상에서 확인이 가능한데 어떻게 추가하는지 궁금합니다.
4. PhisicalTraining -> PhysicalTraining 로 오타 있습니다.

**Comment by icepeng** [comment]
* 속사기 시작 딜레이 적용되지 않고 있습니다.
* 핀포인트 피어스에 윔, 스톰브링어 적용되지 않고 있습니다.
* 천공의 노래에 `345 +combat*3` 이렇게 퍼뎀이 되어있는데, 이게 오더스 적용한것입니다. combat은 0~2 사이의 값이 들어옵니다. 
* 변수명 오타는 코드 전체적으로 많은데, 정말 읽을수도 없는 오타가 아니면 고쳐도 안고쳐도 그만이긴 합니다.

**Comment by icepeng** [comment]
제보 감사합니다. 내일 중에 수정하겠습니다.

**Comment by cheese98** [comment]
`combat`의 경우 0 또는 1입니다. 팔라딘은 쓸컴뱃 없이 찐컴뱃을 코드에 바로 적용하고 있습니다.

**Comment by icepeng** [comment]
combat 부분은 0~1이 맞습니다. 제가 잘못 생각했네요.

**Comment by OniOniOn-** [comment]
패시브 스킬에는 컴뱃 적용이 불가능한가요?

**Comment by icepeng** [comment]
가능합니다. self.combat * 1 과 같이 할 수 있습니다.

**Comment by icepeng** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/pull/207
