### ISSUE TITLE
팔랑크스 데미지스킬에서 소환스킬로 변경 필요

### ISSUE THREAD

**Issue by oleneyl** [oleneyl/maplestory_dpm_calc#136]
팔랑크스 데미지스킬에서 소환스킬로 변경 필요

**Comment by cheese98** [comment]
두가지만 해결되면 바로 수정 가능할 것 같습니다.

지금 팔랑크스가 소환수로 구현된 직업이 윈브랑 스커인데, 둘이 데미지가 같지만 왜 공격주기가 윈브는 600ms (5타)이고 스커는 120ms (1타)인지랑,

스트라이커 팔랑크스는 2/3만 적용하는 이유를 알면 다른 시그 직업들까지 해결할 수 있을 것 같습니다.

**Comment by icepeng** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/pull/231
