### ISSUE TITLE
maplestats 홈페이지 관련 질문용 issue

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#137]
홈페이지 관련 질문을 위한 issue

**Comment by cheese98** [comment]
https://gall.dcinside.com/mgallery/board/view/?id=danpoong&no=20421

홈페이지에서 제공하는 스펙에서 듀블이 팬텀보다 공격력이 낮음 (블레이드 때문에 높아야하는데)

**Comment by icepeng** [comment]
질문 들어오면 그때 따로 여는게 좋겠습니다.
