### ISSUE TITLE
calculate_damage 관련 질문

### ISSUE THREAD

**Issue by kmsiapps** [oleneyl/maplestory_dpm_calc#138]
https://github.com/oleneyl/maplestory_dpm_calc/blob/5d58eed9e41934da193cba7262f39995e1e07e09/dpmModule/kernel/core.py#L130-L131
에서 (100/95), (90/95)를 곱하는 이유가 궁금합니다. 직업별 코드를 확인해 보니 최초 숙련도를 95라고 가정하고 그렇지 않은 직업의 경우 최종뎀을 증감시키는 형태로 보정해 주는 것 같은데(은월같은 경우 숙련도가 90이라, 최종뎀 -5%를 곱하게 되어있는 것 같습니다) 최대 데미지를 1로 두었을 때 최소 데미지가 0.95여야 하니 각각 1, 95/100 을 곱해주어야 하는 게 아닌가요? 또 최종뎀 형태로 숙련도를 보정해 주는 게 오차가 있지 않나... 생각합니다. 가령 데미지 계산이 평균 97.5만큼 곱해졌다고 가정하고 진행되는 것 같은데, 여기에 0.95를 곱하면 92.625가 되지만 90% 숙련도 직업은 평균 92.5가 나와야 할 것 같아서요. 숙련도를 각 직업에서 가져와서 데미지 계산을 해야 하지 않나 생각이 듭니다.

https://github.com/oleneyl/maplestory_dpm_calc/blob/5d58eed9e41934da193cba7262f39995e1e07e09/dpmModule/kernel/core.py#L149
이 부분도 맥뎀이 막히는 구간 확률 X 맥뎀, 맥뎀이 막히지 않는 구간 확률 X 해당 구간의 평균 데미지를 통해 실제 맥뎀이 막힌 데미지를 계산하는 코드로 이해했습니다. 다만 이 경우에 `(res_damage - min_damage) * (res_damage - min_damage)` 부분이 의미하는 바를 잘 모르겠습니다. `(res_damage - min_damage) * (res_damage + min_damage) / 2` 가 맞지 않나요?

항상 수고 많으십니다. 깃헙 레포 처음 공개하셨을 때부터 계속 기여해야지... 생각만 하고 있었는데 조금씩이라도 도움 드리게 되서 기쁩니다.

**Comment by oleneyl** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/blob/5d58eed9e41934da193cba7262f39995e1e07e09/dpmModule/kernel/core.py#L118-L119

숙련도를 90으로 가정한 결과물입니다. 숙련도를 반영해서 계산하도록 하는것이 더 정확하긴 합니다만, 그경우 로직이 약간 복잡해집니다.

최대데미지 반영부분은 말씀주신 대로 계산하는게 맞는 것 같습니다. 크리티컬한 이슈네요.

**Comment by oleneyl** [comment]
급하게 merge해두었습니다. 혹시나 문제가 있다면 revert하겠습니다.

**Comment by kmsiapps** [comment]
혹시 (100/95), (90/95) 를 곱하는 이유를 설명해주실 수 있을까요?
[나무위키](https://namu.wiki/w/%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC/%EC%8A%A4%ED%83%AF#s-1.1) 에서는 앞스공(min_crit_factor 부분?)이 뒷스공(factor_aggregated 부분?)에 숙련도를 곱한 값으로 나오는데, 제 생각에는 min_crit_factor에만 (90 / 100)을 곱해줘야 하지 않나 싶어서요...ㅎㅎ

**Comment by oleneyl** [comment]
100/95, 90/95를 곱하는 이유는 연산 로직 내에서 숙련도(100-n)인 경우를 최종뎀 (100-n/2)로 간주하기 때문에, 이를 원상복구하는 과정입니다.

현재 Slack Channel에서의 discussion을 바탕으로, Uniform distribution을 가정해서 변경했습니다. Review 부탁드립니다.

#140 

숙련도 90이 기준이라는 말은, 숙련도 90을 기준으로 *최대 데미지 보정* 을 하는 과정일 뿐, 숙련도가 실제로 이 과정에서 반영되는 것이 아닙니다.

**Comment by oleneyl** [comment]
따라서 해당 부분은 유지하는게 맞다고 생각합니다.

**Comment by oleneyl** [comment]
+ 숙련도는 즉, 최종뎀 형태로 반영이 되어 있으며, 최대 데미지 고려를 위해 다시 풀어헤친다고 보시면 됩니다.

**Comment by icepeng** [comment]
숙련도를 최종뎀 평균 형태로 not_implied쪽에 넣어두는 이유가 있을까요?

지금처럼 맥뎀을 고려해 연산할 때는 숙련도는 최종뎀의 일부로 치는게 아닌 다른 factor으로 취급해야 한다고 생각합니다.

**Comment by oleneyl** [comment]
숙련도 또한 공격력에 영향을 미치는 요인이고, 따라서 분리해서 처리할 필요가 없다고 여겼습니다.
분리할 경우, 숙련도 항을 처리할 다른 오브젝트가 마땅히 없다고 생각했습니다. 아니면 Character 오브젝트가 해당 수치를 들고 있고, 계산시에 이를 참조하게 하는 것도 가능하겠네요.

**Comment by icepeng** [comment]
숙련도가 다른 항과 다른 점은 `number -> number`가 아닌 `number -> [number, number]`으로 변환하는 요소라는 점입니다. 이 점에서 최종뎀과 유사하지만 type 자체가 다르다고 여겼습니다.

**Comment by oleneyl** [comment]
화력을 특정한 Range로 보내느 수치이긴 하죠.
분리한다면
- JobGenerator() 의 class instance로 정의하고
- Graph.Build() 과정에서 Character에게 넘겨주고
- calculate_damage()과정에서 인자로 패스해주면 되겠네요

**Comment by kmsiapps** [comment]
숙련도 관련 부분 확인했습니다. 직업 코드에서 최종데미지 형태로 빼 주는 게 그런 의미였군요...! Merge해도 괜찮을 것 같습니다

**Comment by oleneyl** [comment]
넵 확인 감사합니다.
