### ISSUE TITLE
GraphElement onAfters 질문

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#144]
https://github.com/oleneyl/maplestory_dpm_calc/blob/717e07aa18d21f7c3145cc84f456e128d3d6caa5/dpmModule/kernel/core.py#L785-L795

여기서 `onAfters`의 이어붙이는 순서가 올바른가요?

제 생각에는 `ellist + self._after`가 맞는 것 같은데, 의도한 사항인가요?

**Comment by oleneyl** [comment]
순서를 바꾸는게 맞을 것 같습니다

**Comment by icepeng** [comment]
onAfters를 사용하고 있는 직업이 상당히 많은데, 적용 전 후 full_test 돌려보고 크게 이상한 직업은 수정 후 적용해야겠습니다.

**Comment by oleneyl** [comment]
잠시 좀만 더 확인을 해보겠습니다

**Comment by oleneyl** [comment]
`onAfters` 를 말씀하신 대로 바꿀 경우 예상되는 행동 양식은 다음과 같습니다.
- `A.onAfter(B), A.onAfter(C)`  --> 실행순서 A,C,B
- `A.onBefore(B), A.onBefore(C)`  --> 실행순서 B,C,A

이렇게 적용하는게 나을까요?

**Comment by icepeng** [comment]
아, `self._after  + ellist` 다시 생각하니 문제 없는것 같습니다.
오히려 onAfter의 `self._after = [el] + self._after`가 이미 A,C,B로 동작하고 있지 않나 싶습니다.

**Comment by oleneyl** [comment]
예 그래서, 그부분을 고쳐야 할지 고민중입니다.

**Comment by icepeng** [comment]
그 부분을 고쳤을 때 여파가 얼마나 될지 감이 안와서 답변하기가 힘드네요. 일단 고치는게 맞다고는 생각합니다.

**Comment by oleneyl** [comment]
일단은 수정하는걸로 하겠습니다.
