### ISSUE TITLE
직업별 공용 스킬을 코드로 분리

### ISSUE THREAD

**Issue by oleneyl** [oleneyl/maplestory_dpm_calc#15]
여러 직업이 공유하는 스킬을 분리하여 모아놓도록 한다.
- graph를 생성하는 코드의 특성상 함수로 분리해서 놓는 것이 좋을듯

**Comment by cheese98** [comment]
제 포크에서는 jobs/jobbranch에 직업 계열(전사, 마법사, 궁수, 도적 해적)을 넣었고 jobs/jobtype에 직업군(모험가, 시그너스, 레지스탕스 등등)을 넣었습니다.
