### ISSUE TITLE
도핑 관련 질문

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#153]
https://github.com/oleneyl/maplestory_dpm_calc/blob/066793f968bb67d3fdff135014bd643511c77b09/dpmModule/character/characterKernel.py#L796-L801

* 노블은 크뎀>뎀퍼>보공>방무 순으로 찍는게 일반적이며, 많은 길드는 44포인트를 15/15/14로 배분합니다.
  * 이때 수치는 크뎀30 뎀퍼30 보공28입니다. 만약 최대치를 가정해 60포인트로 하면 전부 30씩입니다.
* 고보킬과 고관비는 동시에 사용할 수 없습니다. 고보킬+반파별이 맞겠습니다.
* 길축도 길드 패치로 더 큰 길드의 축복 공마 30입니다.
* 붕뿌, 유니온의 힘으로 공마 30 도핑을 두개 더 할 수 있습니다.
* 향상된 10단계 ~~의 물약으로 주스탯 30 도핑이 가능합니다.

**Comment by icepeng** [comment]
@oleneyl @cheese98

**Comment by cheese98** [comment]
그러고보니 도핑이 많이 바뀌었는데 수정이 안되고 있었네요. 간단한 수치 조정은 지금 해도 괜찮을 것 같습니다...

그런데 링크스킬 쪽에도 오류가 있네요

데슬이 뎀퍼로돼있고 시그너스 공마 증가가 반영이 안돼있습니다

**Comment by icepeng** [comment]
뎀퍼 <-> 보공은 코드 여기저기에 오류가 엄청 많이 보이는데 일단 딜량은 똑같으니 냅두고 있었습니다.

링크스킬은 https://github.com/oleneyl/maplestory_dpm_calc/pull/125 이쪽 pr에서 의논 후 적용해야 할 것 같습니다.

시그너스 공마 증가는 아마 장착을 안한거 같습니다.

모법 모도 일리움 카데나 아크 데벤 데슬 제논 루미 제로 레지 키네 엔버

이렇게 총 13개에서 카데나만 전부 사용하고 나머지 직업은 카데나를 뺀 12개를 사용하는 기준입니다.

물론 이렇게 적용하면 안되기 때문에 제가 수정안을 올렸던 것입니다.

**Comment by sumin-kim-crypto** [comment]
일리움 링크가 이동을 해야만 풀스택이 유지되는 구조입니다. 강제로 이동되는 직업들은 괜찮은데, 그렇지 않은 직업들은 스택 유지를 위해 일부러 이동해야하는 시간이 생길텐데요.
이동 시간을 딱히 반영하고 계신것 같진 않아보였는데요.

**Comment by icepeng** [comment]
네 그래서 https://github.com/oleneyl/maplestory_dpm_calc/pull/125 이쪽 pr에서 직업별로 일리움링크 적용 여부를 다르게 할 것입니다. 소마, 카데나 등 이동이 강제되는 직업만 사용하도록 할 것입니다.

**Comment by cheese98** [comment]
그러고 보니까 카데나 링크스킬 추뎀 적용여부도 결정을 해야 되네요.

허수아비 레벨을 캐릭터 레벨이랑 동일하게 설정한다면 현행 유지해도 되는데 캐릭터 레벨이 더 높다면 데미지 6%를 더 줘야합니다.

**Comment by icepeng** [comment]
지금은 6%로 적용중인데 전 그냥 12%가 맞다고 생각합니다. 어차피 큰 상관은 없긴 합니다.

**Comment by sumin-kim-crypto** [comment]
허수아비 레벨을 고정시키는건 어떨까 건의드리고 싶습니다. 230(루시드)이나 250(윌, 진힐라)이 적절하지 않을까 싶네요.
이러면 캐릭 레벨에 따라 카데나링크/렙뎀뻥이 달라져서 작업이 너무 어려우려나요?

**Comment by icepeng** [comment]
이상적으로는 캐릭터레벨도 get_dpm에 인자로 넘기고 있으니 허수아비 레벨도 못넣을건 없긴 한데... 코드가 좀 복잡해지기도 하고, 어차피 dpm 배율이 전혀 안달라져서 진행하지 않을것 같습니다.
