### ISSUE TITLE
일리움 피드백

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#154]
- [x] 글로리 윙 가동률이 지나치게 낮다는 의견이 있음
  * 40초간 스택을 쌓고 글로리 윙으로 진입하는 것이 보통 딜사이클
- [x] 자벨린(오브 이후)의 퍼뎀이 375가 아닌 405로 책정되어 있는데, 이유를 알 수 없음
- [ ] 패시브 매직 서킷이 무기 종류를 안따라감
  * 해적 옵드와 동일한 문제
- [x] 패스트 차지에 벞지 적용해야 함

### 딜사이클 관련

- [x] 패스트 차지
  * 크리스탈 차지가 75 미만이고, 글로리 윙 OFF일 때만 사용
  * 차지 75미만 조건은 있으나 없으나 차이가 없었음
- [x] 이그니션
  * 첫 글로리 윙 지속시간에 함께 사용, 이후로는 쿨마다 사용
  * 글로리 윙과 아예 따로 쓰고, 소오크 2스택에만 맞춰쓰는게 더 세서 이쪽으로 적용
- [x] 그람홀더
  * 글로리 윙 진입 직전에 사용
- [x] 데우스
  * 글로리 윙 진입 직전에 사용
  * 현재 리요/마키나/데우스 구현 부분이 좀 대충 되어있어서 당장 적용하면 딜이 떨어짐

### 소오크 구현 계획(우선순위 낮음)

* 현재의 버프 방식 대신 `SoulCrystalUsing`, `SoulCrystalUsable` 두개의 `StackController`을 생성
* `SoulCrystalUsing`의 초기 스택은 0, `SoulCrystalUsable`의 초기 스택은 2로 시작
* 20초마다 `SoulCrystalUsable.vary(1)`을 하며, 사용 조건은 3가지가 있음
  * 1) `SoulCrystalUsable.stack == 2`
  * 2) `SoulCrystalUsing.stack == 0`
  * 3) 비-글로리윙 이그니션, 글로리 윙 쿨타임이 돌아오면 남은 개수를 모두 사용
* 소오크를 사용할 시 동작
  * `SoulCrystalUsable.vary(-1)`
  * `SoulCrystalUsing.vary(1)`, 30초 후에 `SoulCrystalUsing.vary(-1)`이 실행
  * 리액션:도미네이션, 리액션:디스트럭션,리액션:스펙트럼의 소오크 추가발동의 타수가 `SoulCrystalUsing`의 스택을 따라감
* 이렇게 하려고 했는데, 일정 시간 후 사라지는것 구현하는 부분과 글로리윙/이그니션과 맞추는 부분이 너무 꼬여서 보류

**Comment by crystalgate** [comment]
2번째 항목은 KMS 1.2.324 패치에서 375%로 바뀌었는데 그전패치버전 데미지네요 405%면, 추가로 피드백할거 적어보자면
자벨린 타수가 12로 나와있는것도 수정해야해요 실제로는 몹-공-몹-공-몹 순으로 타격해서 18타 타격합니다

**Comment by icepeng** [comment]
감사합니다. 혹시 변신주기가 너무 느린것에 대해서는 짐작가는 바가 있을까요? 필요하시다면, 일부 로그를 뽑아 드리겠습니다.

**Comment by icepeng** [comment]
그러면 일리움이 자벨린 퍼뎀을 너프당한적이 있는건가요?

자벨린이 하이퍼 적용 기준으로 4타로 알고있는데, 몹-공-몹-공-몹 이라면 4*3=12 적용이 맞지 않나요? 제가 틀렸다면 정정 부탁드립니다.

**Comment by crystalgate** [comment]
아 넵 4타씩 3번에 파편까지 18타가 맞습니다 제가 착각했네요
![일리움](https://user-images.githubusercontent.com/69237140/89391566-578f2100-d743-11ea-9344-63f662fe6f99.png)
여기보시면 390%로 나와있는데 여기서 405퍼로 한번 상향먹고 KMS 1.2.324 패치때 마스터 기준 크래프트:자벨린의 데미지가 75%p증가로 바뀐걸로 알고 있습니다

**Comment by crystalgate** [comment]
그 dpm로그 보시면 처음에 패스트차지를 쓰고 이그니션을 바로 사용하는 것처럼 보이는데 맞을지는 모르겠네요 맞다면 수정이 필요할 것으로 보입니다

**Comment by crystalgate** [comment]
그리고 패스트차지가 쿨 돌면 바로바로 사용되는것같은데 로그보시면 글로리윙이랑 겹칠때가 있어서 패스트차지 효과를 못받는것 같습니다

**Comment by icepeng** [comment]
그렇다면 390%->405%->375% 순으로 변동되어 현재는 375%가 맞다는 것이겠죠?

일단 일리움 자벨린-오브 연계 딜레이가 풀공속 기준 각각 510ms가 아닌 310ms인것 같아 수정해보고 있습니다.

**Comment by crystalgate** [comment]
네 375가 맞습니다

**Comment by icepeng** [comment]
![image](https://user-images.githubusercontent.com/12782606/89392318-5a3e4600-d744-11ea-918b-7347c3980a36.png)

자벨린-오브 딜레이 수정 이후 기준의 글로리 윙 가동률입니다.

처음에 패스트차지+이그니션부터 바로 쏘고 시작해서 글로리 윙 가동이 밀리는 것으로 보입니다.

이그니션은 어느 타이밍에 맞춰 사용하는게 최적일까요?

**Comment by icepeng** [comment]
일단 이그니션 종료 후에 패스트 차지가 사용되도록 수정해 보겠습니다.

**Comment by crystalgate** [comment]
제가 알기로는 글로리윙 최종데미지 증가량이 그람홀더와 데우스에도 영향을 꽤 많이 끼쳐서 스택0에서 시작한다면 처음에 소울 컨트렉트를 제외한 긴 버프들을 사용하고 패스트차지로 풀스택까지 쌓은 후 (어빌리티둘째줄 벞지포함 약 20초면 도달), 데우스,그람홀더 사용-소울 컨트렉트-글로리윙-이그니션 순으로 돌리고 이후에 그람홀더는 글로리윙과 맞춰서, 이그니션은 쿨돌면 바로바로 사용하는게 좋다고 생각합니다 그리고 소울오브크리스탈도 1개씩 계속 유지하되, 2개 쌓일때만 비워주고 글로리윙 타이밍에 맞춰서 2개사용후 글로리윙으로 진입하는게 좋아보입니다

**Comment by icepeng** [comment]
310ms가 아닌 390ms였군요 연계 시 딜레이가.

http://www.southperry.net/showthread.php?t=58415 이쪽 정보에 공속 적용해서 계산했습니다.

(그람홀더, 글로리 윙) 묶어서 사용 적용해보겠습니다.

이그니션은 글로리 윙이 끝난 후에 사용하는건가요?

소오크는 지금 왜 쿨이 40초로 되어있는지 모르겠네요. 소오크 데미지가 몇개 깔린 기준으로 적용중인지 보고 수정하겠습니다.

**Comment by icepeng** [comment]
지금 소오크는 40초마다 2개를 한번에 까는 방식으로 되어있습니다. 20초마다 1개씩 계속 추가로 깔아주는게 딜이 더 잘나올까요?

**Comment by crystalgate** [comment]
이그니션도 글로리윙과 겹쳐서 사용해도 무방해요  자동으로 리액션나가고, 글로리윙의 최종데미지와 소오크의 데미지증가량때문에 더 쌔게 나가기는 하는데 3크리스탈 이그니션+글로리윙이랑 글로리윙이그니션이랑 별 차이 없어서 쿨 빨리돌리는게 나을거라 판단해서 처음에만 맞추고 이후에는 쿨 돌때마다 사용하는게 좋아보인다고 말씀드린거에요 소오크가 좀 애매한데 글로리윙타이밍에 2개깔고 진입하는게 최적이라 잘 모르겠네요 쿨마다깔아서 리액션터지는게 딜적으로 이득일지 글로리윙때 데미지증가력버프 받는게 이득일지....

**Comment by icepeng** [comment]
처음에 맞춘다는게 글로리윙+이그니션을 말씀하시는 것인지 크리스탈+이그니션을 말씀하시는건지 헷갈립니다.

소오크 2개에 진입 맞추는건 다음 글로리 윙이 언제 올지 판단하기 까다롭기에 일단 20초마다 까는 것으로 하고, 자세한 부분은 차차 적용해나가겠습니다.

게시물에서도 설명드렸듯이 정말 필수적인 몇개만 맞추고, 스킬 딜레이 퍼뎀에 오류만 없으면 그 이후로는 딜사이클 최적화해도 차이가 크지 않습니다. 실전은 몰라도 dpm은 극딜에 꼭 열심히 안맞춰도 평딜 증가분이 많이 상쇄해줍니다.

물론 가능한 선에선 다 맞추고 싶기는 한데 제 몸은 하나고 지금 27시간 가까이 잠을 못자서... 딜사이클은 자고 일어나서 생각해보겠습니다.

**Comment by icepeng** [comment]
도움 주셔서 감사합니다. 내일 마저 확인해보겠습니다.

**Comment by crystalgate** [comment]
넵 진짜 수고많으십니다....
딜 사이클 좀 적어보니까 패스트차지도 글로리윙이랑 겹칠때가 있어서 사이클이 정갈해지지가 않네요...  
간단하게만 하면
패스트차지 - 처음 사용 이후 쿨타임이 돌아왔을 때, 크리스탈차지가 75이상이면(기준이 40초마다 풀스택일 경우, 20초) 그대로 쌓아서 글로리윙 진입 후 사용, 미만이면 바로 사용 
이그니션 - 첫 글로리윙 때 사용 후 쿨타임이 돌아왔을 때마다 사용(비 글로리윙 상태에서 사용시, 소울 오브 크리스탈이 충전되어있을 경우 1개 사용)    
소울 오브 크리스탈 - 1개는 상시 유지하며, 저장 최대치인 2개가 저장되면 소모해주고 글로리윙 진입 전에 1개 사용해서 2소오크 글로리윙을 사용하도록 함. 비 글로리윙 이그니션을 사용해야 할 경우에도 1개 소모 후 사용(맨처음에는 1개깔고 첫 패스트차지20초 후 1개 깔고 글로리윙 진입하면 될 거 같아요) 
*이거는 간단히 말하면 평딜 칠때는 이그니션, 글로리윙을 위해 1개는 남겨놓고 사용한다고 생각하면 편할 것 같습니다! 이쪽이 실전쪽하고 더 가깝기도 하구요
그람홀더,데우스 - 글로리윙 진입 직전에 사용
나머지 버프는 설명해주신것처럼해도 상관없을거같아요 
하이퍼 스킬은 롱기누스같은 경우에는 말뚝딜에서는 쓰면 딜로스라 자벨린3개 + 데우스리인포스 + 데우스 보너스어택 찍어줍니다

**Comment by icepeng** [comment]
* 패스트 차지
  * 크리스탈 차지가 75 미만이고, 글로리 윙 OFF일 때만 사용
* 이그니션
  * 첫 글로리 윙 지속시간에 함께 사용, 이후로는 쿨마다 사용
* 소오크
  * 현재의 버프 방식 대신 `SoulCrystalUsing`, `SoulCrystalUsable` 두개의 `StackController`을 생성
  * `SoulCrystalUsing`의 초기 스택은 0, `SoulCrystalUsable`의 초기 스택은 2로 시작
  * 20초마다 `SoulCrystalUsable.vary(1)`을 하며, 사용 조건은 3가지가 있음
  * 1) `SoulCrystalUsable.stack == 2`
  * 2) `SoulCrystalUsing.stack == 0`
  * 3) 비-글로리윙 이그니션, 글로리 윙 쿨타임이 돌아오면 남은 개수를 모두 사용
* 소오크를 사용할 시 동작
  * `SoulCrystalUsable.vary(-1)`
  * `SoulCrystalUsing.vary(1)`, 30초 후에 `SoulCrystalUsing.vary(-1)`이 실행
  * 리액션:도미네이션, 리액션:디스트럭션,리액션:스펙트럼의 소오크 추가발동의 타수가 `SoulCrystalUsing`의 스택을 따라감
* 그람홀더, 데우스
  * 글로리 윙 진입 직전에 사용
  * 만약 스택이 다 찼는데 그람홀더, 데우스 쿨이 살짝 남으면 기다렸다가 쓰고 진입하는게 좋을까요?

일리움은 다른 직업과 다르게 극딜기를 시작부터 다 켜면 안되는 점 때문에 극딜기 싱크가 유난히 안맞고 있네요.

차라리 처음에 150스택 주고 시작하는게 낫겠습니다. 실제로도 그게 맞는것 같습니다.

@crystalgate 요약에 틀린 부분 없는지 확인 부탁드립니다.

**Comment by crystalgate** [comment]
네 맞는거같아요 
데우스는 스택1사이클에 한번씩 사용가능한 대신 노쿨이라서 쿨이 남을일이 없을거같고, 그람홀더는 쿨이 살짝 남는다는게 어느정도인지는 모르겠는데 그냥 글로리윙진입하고 쿨돌면 바로 사용해도 될거같습니다 

일리움 딜방식이 너무 중구난방이어서 수고가 많으십니다 인게임자료 필요한거 있으시면 말씀해주세요

**Comment by icepeng** [comment]
아 글로리윙 진입 직전 사용이라고 하셔서 글로리 윙 상태에서는 사용을 못하는 줄 알았습니다. 일리움 수정 완료 후 버프 가동과 딜점유율 올릴테니, 문제 없는지 확인 부탁드립니다.

**Comment by icepeng** [comment]
소오크 제대로 구현하기가 너무 빡세서 일단 2스택씩 몰아쓰는 형태 그대로 두겠습니다.
각각 따로 돌아가게 할 수는 있는데 막상 해보니까 딜 차이도 거의 없고 다른 스킬들이랑 딜사이클 맞추다보면 코드가 걷잡을수 없이 불어나서... 다른 부분 다 정리되면 마지막에 다시 보겠습니다.

![image](https://user-images.githubusercontent.com/12782606/89707937-8c9eac00-d9ad-11ea-9b2f-b090ef814e25.png)

지금까지 기준으로 점유율은 이렇게 나옵니다.

**Comment by icepeng** [comment]
![image](https://user-images.githubusercontent.com/12782606/89716430-e02deb80-d9e7-11ea-971d-3e3a5e1ea8f9.png)
![image](https://user-images.githubusercontent.com/12782606/89716432-e328dc00-d9e7-11ea-941d-5156fdc6caeb.png)
![image](https://user-images.githubusercontent.com/12782606/89716433-e45a0900-d9e7-11ea-93b8-e155d7472da7.png)

오류들 더 수정하고, 피드백 바탕으로 딜사이클 만져본 결과입니다.
