### ISSUE TITLE
제로 의문

### ISSUE THREAD

**Issue by Elen-hub** [oleneyl/maplestory_dpm_calc#158]
https://github.com/oleneyl/maplestory_dpm_calc/blob/4bf8c6c66b2ef780ac778436abc0398a12755ef6/dpmModule/jobs/zero.py#L213

30렙기준 최종데미지 36%입니다
*1.2 +20이 잘못적혀있는것 같습니다

https://github.com/oleneyl/maplestory_dpm_calc/blob/4bf8c6c66b2ef780ac778436abc0398a12755ef6/dpmModule/jobs/zero.py#L116

State_Beta의 최종데미지 9.7% 보정은 알파와의 무기상수에 따른 차이입니까

**Comment by icepeng** [comment]
*1.2 부분은 리미트 브레이크의 "종료될 때 발동 시 공격에 적중된 적이 살아있다면 스킬 지속 중 제로가 해당 적에게 가한 데미지의 20%를 15번에 걸쳐 나눠 받음" 부분을 정확하게 처리하기 힘들어 버프 지속 도중의 최종 데미지를 1.2배 더 늘리는 것으로 적용했습니다. 맥뎀 연산을 고려하면 정확한 방식은 아닙니다.

해당 문제는 https://github.com/oleneyl/maplestory_dpm_calc/issues/27 이쪽에서 언급된 적 있습니다.

근데 최종뎀에 +20이 더 들어간 이유는 잘 모르겠네요. @cheese98 님이 확인해주셨으면 합니다.

State_beta의 최종 데미지 보정은 무기상수에 따른 차이를 의도한 것 같은데, 베타의 무기상수가 0.15 더 높으므로 7.5로 적용해야 하는게 아닌가 싶습니다. 이 부분도 @cheese98 확인 부탁드립니다.

**Comment by cheese98** [comment]
리미트 막타를 버프 내에 적용할 경우 30레벨 기준 최종 데미지 증가량이 1.2 * 1.36 = 1.632배가 됩니다.

`pdamage_indep = n`은 (1+0.01n)로 적용되는 방식이기 때문에 최종 데미지 증가량을 올바르게 적용하려면 `(1+0.36)*(1+0.2)`를 코드에 반영해야 하죠.

따라서 `1 + 0.36 + 0.2 + 0.36*0.2`에서 기본값인 1을 빼면 `0.36 + 0.2 + 0.36*0.2`, 묶으면 `0.36 * 1.2 + 0.2`가 되므로 맞습니다.

저도 틀린 줄 알고 계산기 두들겨봤는데 알고보니 제작자님의 깊은 뜻이 담겨있었던... 부분이었습니다.


`pdamage_indep = (1.49 / 1.34) * 100 - 100`이 맞을 것 같은데 한번 더 확인해주시면 감사하겠습니다.

**Comment by cheese98** [comment]
Before: 455232972294.04474
After: 457987577719.43945

무기 상수 패치결과 약간의 딜 상승이 있네요. (약 0.6%)

**Comment by icepeng** [comment]
아, 그게 맞네요. pdamage_indep 같은건 계속 1이 빠진채로 계산 하는게 헷갈리니 그냥 `core.CharacterModifier()`을 여러번 합산해서 계산하는게 좋겠습니다.

**Comment by icepeng** [comment]
무기상수는 음... 그렇게 계산하는게 맞을지 모르겠습니다. 제 생각에는 다를것 같은데 잠시만요

**Comment by icepeng** [comment]
아 제가 무기상수랑 숙련도랑 헷갈렸네요. 식 자체는 맞습니다. 알파 -> 베타 변경시 스탯 변화가 헷갈리기 쉬운데, 당장 generate 코드 상단에 있는 `AlphaMastery`, `BetaMastery` 값을 활용하면 되지 않나요?

**Comment by icepeng** [comment]
`CharacterModifier`에 __sub__가 구현되어 있기 때문에 충분히 활용 가능합니다.

```
        AlphaMastery = core.CharacterModifier(pdamage_indep = 34) + \
            core.CharacterModifier(att = 40, armor_ignore = 30) + \
            core.CharacterModifier(crit = 40) + \
            core.CharacterModifier(crit_damage = 50)
        BetaMastery = core.CharacterModifier(pdamage_indep = 49) + \
                    core.CharacterModifier(crit = 15, boss_pdamage = 30 + 30, att = 80) + \
                    core.CharacterModifier(armor_ignore = 50)

        AlphaBetaDiff = BetaMastery - AlphaMastery
        print(AlphaBetaDiff)
        
        # 알파: 크리티컬 바인드 크뎀 평균값 적용
        AlphaState = core.BuffSkill("상태-알파", 0, 9999*10000, cooltime = -1, crit_damage = (20*4/35)).wrap(core.BuffSkillWrapper)
        BetaState = core.BuffSkill("상태-베타", 0, 9999*10000, cooltime = -1,
            pdamage_indep = AlphaBetaDiff.pdamage_indep,
            crit = AlphaBetaDiff.crit,
            boss_pdamage = AlphaBetaDiff.boss_pdamage,
            att = AlphaBetaDiff.att,
            armor_ignore = AlphaBetaDiff.armor_ignore,
            crit_damage = AlphaBetaDiff.crit_damage + (20*4/35)
        ).wrap(core.BuffSkillWrapper)
```

이런 식으로 하면 됩니다. 그런데 상태 - 베타에 왜 크바 평균값 보정이 들어가있나요? 알파의 공격에만 반응하는 것으로 알고 있습니다.

**Comment by icepeng** [comment]
그런데 지금 BetaMastery의 값이 조금 이상해서 그대로 사용하시면 안됩니다. 값은 수정해서 활용해주세요. 일단 armor_ignore가 있는데 이건 아머 스플릿의 방무가 중복으로 들어갔습니다. 보공도 30+30이 아닌 30만 들어가야 합니다.

**Comment by icepeng** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/pull/160

올려두신 PR과 겹치는 부분이 없을거 같다 PR 올렸습니다. 확인해주세요.

**Comment by cheese98** [comment]
제가 따로 생각해놓은 방식이 있긴 한데 일단 merge된 다음에 새로 올려보겠습니다.

**Comment by oleneyl** [comment]
우선 Merge하겠습니다.

**Comment by Elen-hub** [comment]
최종데미지 20%을 버프로 보정하는건 간편하지만 괴리감이 큰방식같습니다
차라리 어파스콤보에서 가장많이쓰이는 피어스스트라이크의 버프지속시간동안 사용횟수를 참조해서 피어스스트라이크 딜지분율과 연산해서 20%데미지를 간략하게나마 유도해낼 수 있지 않을까 싶습니다

**Comment by icepeng** [comment]
맥뎀에 막히지만 않으면 최종 dpm 자체에 괴리감이 크진 않습니다. 물론 딜점유율에는 괴리가 생깁니다.

맥뎀이 꽤 빨리 막히긴 할테니 수정하는게 좋긴 합니다.

사용 횟수 기반도 좋은 의견이지만, 결국 현행 방식도 그렇고 둘 다 근사치 적용이므로 정확한 딜량 계산해서 반영 가능하도록 https://github.com/oleneyl/maplestory_dpm_calc/issues/27 쪽을 해결보는게 맞을 거 같습니다.

**Comment by cheese98** [comment]
제로는 무기 기본옵의 보공과 방무가 2회 적용돼야 합니다. 혹시 지금 제대로 적용되고 있나요?

**Comment by icepeng** [comment]
기본옵이라 함은 잠재능력 말고 무기 자체에 붙어있는거 말씀하시나요?

**Comment by cheese98** [comment]
네. 무기 자체 옵션 중에 보공과 방무만 적용됩니다. 아이템 쪽에서 제로를 예외처리한 코드를 못본 것 같아서요.

**Comment by icepeng** [comment]
네 저도 안보이네요. 예외처리 한다면 ItemKernel에 getWeapon쪽을 건드리면 될거 같긴 합니다. 듀블 블레이드도 이쪽에서 처리중입니다.

**Comment by icepeng** [comment]
get_subweapon_covering_exception쪽도 건드려야겠네요. 그러고보니 강화나 주문서 수치도 두배로 들어가나요?

**Comment by icepeng** [comment]
제로 무기의 공격력도 두번 다 들어가나요? 아니면 현재 들고있는 무기 공격력만 취급하나요? 일단 무기 자체 옵션의 보공방무만 적용되게 하려면 `item/Default.py`에서 `get_subweapon_covering_exception`의 내용물을

```
    if _type == '블레이드':
        return factory_hook.getWeapon(_type, bonusAttIndex=0, star=star, potential = potential, additional_potential = additional_potential, enable_blade=True)
    elif _type == '제로무기':
        weapon = factory_hook.getWeapon(_type, bonusAttIndex=0, star=star, potential = potential, additional_potential = additional_potential)
        weapon.att = 0
        return weapon
    else:
        return getSubweapon(potential=potential, additional_potential=additional_potential)
```

이렇게 바꿔버리면 되긴 합니다.

베타 무기 공격력이 조금 더 높은데, 저희가 사용하는 렙제에서는 전부 공통적으로 4 더 높습니다. 그건 상태(베타)에 포함해도 됩니다.

**Comment by cheese98** [comment]
무기 공격력은 두번 적용되지 않습니다. 베타 무기 공격력 차이는 나중에 PR에 덧붙이도록 하겠습니다.

**Comment by icepeng** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/pull/382

리미트 브레이크 제외, 제로 관련 이슈 모두 수정했습니다.

리미트 브레이크는 테섭 패치가 넘어오는 것을 확인 후 수정 여부를 정하겠습니다.
