### ISSUE TITLE
은월 약점 간파 관련 논의

### ISSUE THREAD

**Issue by kmsiapps** [oleneyl/maplestory_dpm_calc#162]
은월의 패시브 스킬인 약점 간파에는 체력이 50% 이하인 적에 대해서 크리티컬 확률 65%, 크리티컬 데미지 20%가 올라가는 효과가 있습니다. DPM 계산 시에 이걸 어떻게 적용해야 할까요?

일단 지금 DPM 계산 시에 딱히 허수아비 체력과 관련한 부분은 제가 알기로 없고, 또 있다고 하더라도 허수아비 체력에 대해서 이걸 적용하는 게 맞나 싶기도 하고요. (10초 딜 같은 데서 순위가 낮게 나올 것 같아서)

가동률 50%짜리 버프를 하나 만들어서 크확 65%, 크뎀 20%를 주는 게 나을까요?

**Comment by cheese98** [comment]
크게 두가지 방법이 있습니다. 가동률 50%짜리 버프 적용 or 버프효과를 반토막내서 상시적용

전자의 경우 활성화 타이밍을 언제로 잡아야할지 정해야 합니다. 딜사이클 초반부에 잡으면 극딜기랑 겹쳐서 딜량은 높게 뜨겠지만 비현실적이죠. 보통 때리기 시작할때 풀피잖아요. 그래서 저는 버프형식으로 갈거면 차라리 딜사이클 후반부에 넣는 게 나을 거라고 생각합니다.

후자의 경우 매우 간단하긴 하지만 랜덤효과도 아닌 스킬을 평균치로 적용하는 건 솔직히 좋은 방법이 아니죠.

**Comment by icepeng** [comment]
dpm의 정의 자체를 잡고 가야합니다.

지금이야 480초 혹은 1800초를 잡고 시뮬레이션을 하지만, 원래 dpm의 정의는 무한한 시간을 타격하는 것을 기준으로 하고 평균을 내는 것이였습니다.

해당 정의에 따르면 딜사이클 초반/후반을 나누는 이야기는 아예 의미가 없습니다.

물론, 저희가 해당 정의를 그대로 따를 필요는 없습니다. dpm/480, dpm/1800이라고 말 하면 그만이죠.

**Comment by icepeng** [comment]
일단 맥뎀에 애매하게 막히는 스펙이 아니면 평균치로 적용해도 큰 문제는 없습니다.

가장 확실한건 그냥 은월(50%초과), 은월(50%이하) 두개 dpm을 다 뽑는겁니다. 이거 말고는 기존 정의를 따라가면서 정확한 값을 뽑을 방법은 없다고 생각합니다.

**Comment by cheese98** [comment]
그러면 일단 표준 DPM은 허수아비 상대로 뽑기로 했으니 허수아비에 약점간파 적용 여부를 확인해보고 거기에 따르면 될것같습니다.

**Comment by icepeng** [comment]
몹 사이즈가 허수아비 기준이지 체력까지 허수아비 기준으로 생각하지는 않을거라 생각합니다.

**Comment by kmsiapps** [comment]
지금 DPM 연산은 타격 대상 체력이 무한이라고 두고 데미지만 계산하고 있는 거죠? 사실 480초/1800초 기준을 둔다고 해도 시뮬레이션 시간 동안 타격한 총 데미지 = 대상 체력이라고 가정하지 않는 이상 이걸 적용하기도 좀 쉽지 않아 보이긴 하네요.

그래도 딜에 꽤 영향을 주는 부분 중 하나라서, 어떤 방식으로든 반영하는 게 좋지 않을까... 생각합니다.

**Comment by icepeng** [comment]
아예 따로 뽑지 않는다면 가동률 50%짜리 버프로 취급하는게 그나마 무난한거 같습니다.

**Comment by kmsiapps** [comment]
@oleneyl 님 의견은 어떠신가요?

**Comment by oleneyl** [comment]
너무 늦게 확인했네요; 저는 50%로 반영하는게 좋다고 생각합니다. 말씀하신것처럼 반영하지 않기에는 좀 큰 부분이니까요

**Comment by icepeng** [comment]
조건부 양쪽 표기로 (일단은) 해두었음.
