### ISSUE TITLE
은월 귀문진 디버프 이슈

### ISSUE THREAD

**Issue by kmsiapps** [oleneyl/maplestory_dpm_calc#164]
현재 은월 코드에서는 귀문진 디버프가 제대로 동작하지 않는 것 같습니다.
귀문진 정령이 소환될 때마다(SoulTrap.onTick?) 스택이 1씩 쌓이고, 해당 스택은 8초가 지나면 1씩 감소하는 식으로 구현되어야 합니다. 

StackSkillWrapper를 가지고 좀 고민해 봤는데 잘 모르겠네요. 8초가 지나면 스택을 감소시킬 방법이 있을까요?

정확하지는 않지만 스택 고려 없이 처음부터 끝까지 10스택이 유지된다고 가정하고 아래처럼 돌려봤을 때  대략 2.5% 정도 딜 상승이 있었습니다.

`# 디버프가 8초간 지속되므로 마지막 소환 시점(39990ms) 후 8초 더 지속하도록 함`
`SoulTrapBuff = core.BuffSkill("귀문진(버프)", 0, 47990, cooltime = -1, crit_damage=10, crit=80).wrap(core.BuffSkillWrapper)`

**Comment by icepeng** [comment]
일정 시간 후에 스킬 발동시키는 코드는 여기저기 참고할게 많이 있습니다.

예를 들어 아델의 루인은

```
        Ruin.onAfter(RuinFirstTick)
        Ruin.onAfter(RuinSecondTick.controller(2000))
```

이렇게 2초 후에 막타가 들어가게 되어 있습니다.

다만 스택 조절을 2초후에 해주려면 더미 버프를 하나 만들어서 거기다가 또 걸어줘야 할거 같은데... 잠시 더 찾아보겠습니다.

**Comment by kmsiapps** [comment]
#157 에 추가해봤습니다. 생각보다 딜 상승량이 큰데... 면밀히 검토해볼 필요가 있을 것 같습니다.
print 찍어서 스택 0 -> 10, 10 -> 0으로 잘 변화하는 것까지는 체크했는데, 이게 제대로 된 건지는 확신이 없네요.
