### ISSUE TITLE
에픽어드벤쳐 계열 딜레이 이슈

### ISSUE THREAD

**Issue by oleneyl** [oleneyl/maplestory_dpm_calc#168]
해당 스킬의 딜레이를 0으로 기입하는 것이 맞을까요?
실제 인게임에서는 완전히 0이라고 보기는 약간 애매했던것 같아 질의합니다.

**Comment by icepeng** [comment]
안그래도 그쪽으로도 문의가 들어왔었습니다.

딜레이가 아무리 봐도 0은 아닌거 같은데... 위컴알에 봐도 딜레이 정보를 정확히 알기가 힘듭니다.

**Comment by cheese98** [comment]
http://www.inven.co.kr/board/maple/2299/4916553

모험가도적 10초 극딜표 만드신 분이 직접 측정한 결과 450ms라고 합니다. 댓글에 있습니다.

**Comment by icepeng** [comment]
아 그랬었죠, 450ms로 바꾸는게 좋겠습니다.

**Comment by icepeng** [comment]
이게 실험을 해봤는데... 애매합니다. 저번에 펫버프 씹힘 고치면서 버프 딜레이 관련 로직이 바뀌었습니다.

액션 딜레이가 없는 버프와 공격 스킬은 이론상 동시에 사용이 가능합니다. 듀블 히든 블레이드나 190제 하이퍼 여럿 실험했습니다.

하지만 버프-버프로 이어서 사용할때는 숨겨진 딜레이가 약 450ms정도 존재합니다.

패치 전에는 버프가 무조건 딜레이를 적용했다면, 패치 후로는 버프+공격/이동 스킬은 딜레이가 없고, 버프+버프 사용시에만 사이에 간격이 들어가는 것으로 보입니다.

전 일단 버프+공격 - 버프+공격 이렇게 이어주는게 가능하다고 가정하고 클라 딜레이가 없는 버프는 그대로 0ms 가져가도 된다고 생각합니다.

**Comment by icepeng** [comment]
추가 discussion 없으면 닫겠습니다.
