### ISSUE TITLE
데몬어벤져, 제논 구현 문제

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#17]
이 둘은 일반 직업들과는 다른 스탯을 사용하는데 이걸 어떻게 구현할지에 대한 논의 필요

**Comment by oleneyl** [comment]
현재 상태에서 구현을 하려고 할 경우  stat_main과 stat_sub만을 지원하는 현재의 status 묘사방식이
문제가 됩니다. 명확하게는 다음 프로세스들에서 문제가 생깁니다.

* 무기 및 아이템들의 template building이 주스텟/부스텟으로 생성되기 때문에 호환되지 않음
(CharacterTemplate class)

* 스텟공격력 계산방식이 달라 공격력을 계산하는 과정에서 문제가 발생
(Simulator, Analytics class)

일단 저로서는 다음과 같은 두 가지 해결책을 생각중입니다. 다른 방식이 있다면 추가바랍니다. 아직 구현 시도는 하지 않았습니다.
* CharacterTemplate class는 그대로 두고, 최종 데미지 계산 과정에 ZenonCalculator, DemonavengerCalculator class를 생성하고 삽입하여 Analytics level에서 계산 루트를 거치도록 하는것

  * 장점 : 구현이 비교적 쉽습니다(로예상됩니다)
  * 단점 : Analytics level에서 Job의 종류를 알고 있어야 합니다.
* JobGenerator class 내부에 calculator 내부 함수를 추가하고 제논, 데벤의 경우에 이 함수를 override 하여 최종 단계에서 모든 stat_main, stat_sub값을 알맞게 변형하는 방법

  * 장점 : Job에 대한 모든 작업을 JobGenerator에게 위임합니다.
  * 단점 : 구현이 매우 복잡합니다.

* 제논, 데벤져의 경우에 Template를 새로 생성하도록 하는 방법
  
  * 장점 : 구현이 매우 쉽습니다.
  * 단점 : Template를 만들 때마다 제논, 데벤져에 관련된 생성 코드를 무조건 구현해주어야 합니다.(코드가 반복되므로 매우 나쁨)

**Comment by cheese98** [comment]
일단 일반 직업들 구현하듯 코드를 작성해봐도 될까요?

**Comment by oleneyl** [comment]
네 얼마든지요
pull request 넣어주시면 감사하겠습니다.

**Comment by cheese98** [comment]
데벤 스킬들은 다 등록했는데 스킬 딜레이랑 딜사이클을 몰라서 더 이상 진행이 안되네요. 일단 지금까지 만든 거라도 올려도 되나요?

**Comment by icepeng** [comment]
#118 이동
