### ISSUE TITLE
섀도어 피드백

### ISSUE THREAD

**Issue by bonetul** [oleneyl/maplestory_dpm_calc#170]
섀도어 코드 130번째줄?에
        SonicBlowTick = core.DamageSkill("소닉 블로우(틱)", 125, 500+20*vEhc.getV(1,1), 7, modifier = core.CharacterModifier(armor_ignore = 100)).isV(vEhc,1,1).wrap(core.DamageSkillWrapper, name = "소닉 블로우(사용)")#20타
소닉블로우가 20타로 적용되어 7*2*20 = 280타로 적용되어 있는건가요?
280타는 소닉블로우가 처음 나올 때 테스트서버에서 280타였는데 본섭으로 넘어오면서 210타로 바뀌었습니다.

또한 코드 107번째줄에

BailOfShadow = core.DamageSkill("베일 오브 섀도우", 810, 800, 15, cooltime = 60000).setV(vEhc, 3, 2, False).wrap(core.DamageSkillWrapper)

로 15타로 적용되어 있는데 실제 전투분석은 14타로 적용됩니다.
소블 타수나 베일 타수 확인은
https://youtu.be/yjJwhKAXpnU 이 영상이나 
http://www.inven.co.kr/board/maple/2297/100949?category=%EC%84%80%EB%8F%84%EC%96%B4&name=subject&keyword=40%EC%B4%88
여기로 들어가서 확인하시면 될 것 같습니다.
소닉블로우는 40초동안 2번 돌려서 그 2배인 420타로 찍혀있습니다.

마지막으로 이건 개인적인 질문인데 102번째줄과 105번째줄에서의 암살 2타의 딜레이가 630+30 ms로 표기되어 있는데 무슨 의미인지 잘 모르겠습니다. 암살 2타의 딜레이는 정확한 수치는 모르겠지만 암살 1타의 약 1/3정도인데 630+30 ms로 표기된 것은 무슨의미인가요?

**Comment by icepeng** [comment]
소블, 배오섀 타수는 저녁 먹고 와서 확인해보겠습니다.

배오섀가 소환스킬로 되어있지 않은 것도 문제네요.

마지막은 아마 암메암 지연사출과 관련이 있지 않나 싶습니다.

**Comment by icepeng** [comment]
그리고 Github에서 *로 양쪽을 감싼 글자는 *이렇게* 되기 때문에, 코드 부분은 양옆에 `로 감싸서 `이렇게 5*5*5*5` 해주면 *로 인해 내용이 망가지지 않습니다.

**Comment by icepeng** [comment]
소블이 정말 20회 연속 발동으로 되어있었네요. 15회로 수정해야 합니다. 제가 지금 밖이라 코드는 pr은 나중에 올리겠습니다.

**Comment by icepeng** [comment]
@cheese98 암살 2타 딜레이 부분 확인 부탁드립니다

**Comment by cheese98** [comment]
처음부터 그렇게 되어 있었습니다. 정확한 수치를 잘 몰라서 그대로 뒀어요.

**Comment by icepeng** [comment]
일본쪽 자료에는 1타 630, 2타 420으로 사용하고 있습니다. 일단 이쪽으로 적용해볼게요.
