### ISSUE TITLE
은월 파쇄철조-반 추가

### ISSUE THREAD

**Issue by kmsiapps** [oleneyl/maplestory_dpm_calc#172]
은월이 대상에게 파쇄철조 스킬을 사용하면 최종뎀 10%짜리 파쇄철조-반 디버프(지속시간 15초)가 걸리는데, 이를 딜사이클에 반영할 필요가 있어 보입니다.

**Comment by icepeng** [comment]
아, 그러네요. 파쇄철조 3종 모두 딜레이가 같나요?

**Comment by kmsiapps** [comment]
아마 모두 같을 겁니다. 셋 중 하나만 계속 썼던 것 같아요.

**Comment by icepeng** [comment]
그러면 그중 퍼뎀 높은쪽으로 쓰면 되겠습니다. 그래도 코강은 안하겠죠?

**Comment by kmsiapps** [comment]
파쇄철조-회로 추가해 두었습니다. 코강은 안할 것 같아서 일단 인덱스 7로 해두었습니다.
