### ISSUE TITLE
contrib.py와 jobutils.py 통합에 대해

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#173]
둘다 직업 스킬 자체보다는 코드 최적화에 필요한 함수들을 제공하는 파일인데 하나로 합쳐도 될까요?

만약 합친다면 어떤 쪽으로 할까요?

**Comment by icepeng** [comment]
jobutils쪽에 합치면 되지 않나 싶습니다.

**Comment by oleneyl** [comment]
jobutil로 합치는게 좋을 것 같습니다.

**Comment by cheese98** [comment]
jobutils쪽으로 해서 PR 올렸습니다. 닫도록 하겠습니다.
