### ISSUE TITLE
호영 자료

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#174]
http://www.inven.co.kr/board/maple/2299/4926649

**Comment by cheese98** [comment]
https://github.com/cheese98/maplestory_dpm_calc/blob/hoyoung_skills/dpmModule/jobs/hoyoung.py

제 포크에다가 일단 스킬셋 따놓긴 했는데 스킬 딜레이나 딜사이클 같은건 하나도 안돼있습니다.

일단 이거라도 올려볼까요?

**Comment by icepeng** [comment]
올려두시고 차차 완성해나가면 좋겠네요.

가능하면 해당 자료 기반으로 실제 동작까지 구현해주시면 좋겠습니다.

**Comment by cheese98** [comment]
#175 
일단 올렸습니다. 지금으로서는 더 이상 작업이 불가능합니다...

**Comment by icepeng** [comment]
키네 일리움 섀도어 정리되고 한번 보겠습니다.

**Comment by Nougaga** [comment]
여의선:인, 토파류:지, 파초풍:천의 딜레이는 570ms로 모두 동일
(액션에서 확인해볼 수 없는 alert 동작이 섞입니다)

**Comment by icepeng** [comment]
#477
