### ISSUE TITLE
패스파인더 문의사항

### ISSUE THREAD

**Issue by orangemagic123** [oleneyl/maplestory_dpm_calc#176]
UltimateBlast = core.DamageSkill("얼티밋 블래스트", 1800, 2500+100*vEhc.getV(2,2), 15, cooltime = 120*1000, modifier = core.CharacterModifier(armor_ignore = 100, pdamage_indep = 100) + core.CharacterModifier(pdamage_indep = 10, boss_pdamage = 70, armor_ignore = 20)).isV(vEhc, 2,2).wrap(core.DamageSkillWrapper) 

RavenTempest = core.SummonSkill("레이븐 템페스트", 720, 250, 500+20*vEhc.getV(0,0), 5, 25*1000, cooltime = 120*1000).isV(vEhc,0,0).wrap(core.SummonSkillWrapper) 

ObsidionBarrierBlast = core.SummonSkill("옵시디언 배리어", 60, 480, 500+18*vEhc.getV(4,4), 4, 15000,cooltime = 200*1000, modifier = core.CharacterModifier(pdamage_indep = 10, boss_pdamage = 50)).isV(vEhc,4,4).wrap(core.SummonSkillWrapper) ###### Skill Wrapper ######

-----------------------------------------------------

1. 레이븐 템페스트에는 CharacterModifier(pdamage_indep = 10, boss_pdamage = 70, armor_ignore = 20)) 이 항목이 붙어있지 않네요
에인션트포스/인챈트포스 강화 패시브같은데 이거 적용해야하지 않나요?

2. 스킬 퍼뎀이 얼티밋블래스트는 2000+100*스킬레벨, 레이븐템페스트는 400+20*스킬레벨인걸로 알고 있는데 퍼뎀이 잘못된것같아요

3. 패스파인더 코드에 CancelableTime에 대한게 적혀있지 않은것같은데(제가 코드를 볼줄몰라서 그냥 못본걸수도 있구요) 연계로 인한 딜레이감소가 적용되고 있나요?

**Comment by icepeng** [comment]
1. 적용하는게 맞아보입니다.
2. 얼티밋 블래스트 퍼뎀 잘못된것 확인했습니다. 레이븐 템페스트도 잘못되어있네요.
3. 패파 연계로 딜레이 줄어드는게 블-디 연계뿐인가요? 아마 이미 줄어든 기준으로 해놨을듯 한데 좀 더 확인해보겠습니다.

지금 밖이라서 들어가면 수정해두겠습니다.

제보 감사합니다.

**Comment by orangemagic123** [comment]
http://m.inven.co.kr/board/maple/2304/17507

이 게시물에 따르면 카디널포스 스킬을 쓰다가 에인션트포스/인챈트포스 스킬을 쓸땐 연계로 인한 딜레이감소가 적용된다고 하네요

**Comment by icepeng** [comment]
자료 제공 감사합니다. 위컴알에서 데이터 확인해보고 적용하겠습니다.

**Comment by icepeng** [comment]
1, 2 수정되었습니다.
3은 적용되고 있었으나, 약간 부정확한 부분이 있어 실험 후 연계시 딜레이로 일괄 적용했습니다.
