### ISSUE TITLE
아란 문의

### ISSUE THREAD

**Issue by sumin-kim-crypto** [oleneyl/maplestory_dpm_calc#183]
1. 콤보 어빌리티+어드밴스드 콤보 어빌리티(인게임 확인 필요)
https://github.com/oleneyl/maplestory_dpm_calc/blob/3775a39ff28d85ba8ea382eed4d100712c327197/dpmModule/jobs/aran.py#L95
인게임에서 콤보 어빌리티의 설명은 콤보 카운트 50당 공격력 2 증가/방어력 20 증가/이동속도 3증가
어드밴스드 콤보 어빌리티의 설명은 콤보 카운트 50당 크확 3%, 공격력 2 추가 증가
입니다. 둘이 포함 관계에 있지 않음을 고려할때, 실제 적용은 콤보 50당 공격력 4 증가가 아닐까 싶습니다.
(확인이 필요하긴 합니다)

2. 게더링 캐쳐 쿨타임
https://github.com/oleneyl/maplestory_dpm_calc/blob/3775a39ff28d85ba8ea382eed4d100712c327197/dpmModule/jobs/aran.py#L140
쿨타임 5초가 존재하는 스킬입니다. 따라서 캔슬도 쿨타임 5초입니다.
현재 쿨이 없는것으로 보입니다.

3. 오쓰 시전시간
https://github.com/oleneyl/maplestory_dpm_calc/blob/3775a39ff28d85ba8ea382eed4d100712c327197/dpmModule/jobs/aran.py#L123
이것도 0은 아닙니다. 다른 190제 하이퍼와 같지 않을까 싶네요.

4. 파이널 블로우 아드레날린 시 퍼뎀
https://github.com/oleneyl/maplestory_dpm_calc/blob/3775a39ff28d85ba8ea382eed4d100712c327197/dpmModule/jobs/aran.py#L109
다이나믹 마스터리 20%p가 빠져있습니다.

5. 인스톨마하 눈보라 퍼뎀
https://github.com/oleneyl/maplestory_dpm_calc/blob/3775a39ff28d85ba8ea382eed4d100712c327197/dpmModule/jobs/aran.py#L130
눈보라 퍼뎀이 잘못되었습니다. 25렙 기준 900%, 30렙 기준 990%로 450%+스킬레벨*18% 입니다.

6. 펜릴 크래시
https://github.com/oleneyl/maplestory_dpm_calc/blob/3775a39ff28d85ba8ea382eed4d100712c327197/dpmModule/jobs/aran.py#L144
펜릴이 기본적으로 10명을 때리고, 1명을 때리는 기준이면 데미지 증가량이 1.06^9-1 = 68.947%입니다.
+) 펜릴 29렙까지는 타수가 6+1(비욘더 보너스어택)=7입니다. 대부분 30렙일테니 큰 의미는 없습니다.

**Comment by icepeng** [comment]
1. 콤보 50당 4가 맞는것 확인했습니다. 수정하겠습니다.
2. 게더링 캐쳐는 브마/인마/마하의영역 후딜 캔슬에만 사용합니다. 각 스킬들이 5초 내로 연달아 사용될 일은 없다고 가정한거 같습니다.
3. 190제 하이퍼는 일괄적으로 딜레이 450ms를 넣어야 합니다. 지금 전부 빠져있습니다.
4. 빠져있습니다. 수정하겠습니다.
5. 잘못 입력된게 맞습니다. 수정하겠습니다.
6. 펜릴은 비욘더의 코강 효과를 적용받아 11타겟이 되는 것으로 알고 있습니다. 타수 부분은 수정하겠습니다.
