### ISSUE TITLE
전직업 리뷰 현황 정리

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#187]
1차적인 점검 (딜레이, 퍼뎀, 타수, 스킬 연계) 완료된 직업들을 체크해둡니다.

## 모험가

- [x] 히어로
- [x] 팔라딘
- [x] 다크나이트
- [x] 아크메이지불/독
- [x] 아크메이지썬/콜
- [x] 비숍
- [x] 보우마스터
- [x] 신궁
- [x] 패스파인더
- [x] 나이트로드
- [x] 섀도어
- [x] 듀얼블레이드
- [x] 바이퍼
- [x] 캡틴
- [x] 캐논슈터

## 시그너스

- [x] 소울마스터
- [x] 플레임위자드
- [x] 윈드브레이커
- [x] 나이트워커
- [x] 스트라이커
- [x] 미하일

## 레지스탕스+데몬

- [x] 블래스터
- [x] 배틀메이지
- [x] 와일드헌터
- [x] 메카닉
- [ ] 제논 (미구현)
- [x] 데몬슬레이어
- [ ] 데몬어벤져 (미구현)

## 영웅

- [x] 아란
- [x] 에반
- [x] 루미너스
- [x] 메르세데스
- [x] 팬텀
- [x] 은월

## 노바

- [x] 카이저
- [x] 카데나
- [x] 엔젤릭버스터

## 레프

- [x] 아델
- [x] 일리움
- [x] 아크

## 혼밥

- [x] 제로
- [x] 키네시스
- [ ] 호영 (미구현)

**Comment by icepeng** [comment]
남은 직업들 난이도는 패파를 제외한 모험가들, 시그너스, 카이저 정도가 무난해보이고 나머지는 다 시간이 좀 걸릴거 같네요...

**Comment by cheese98** [comment]
보마: 잔영의시, 애로우레인 확인필요, 윈드오브프레이 미구현
윈브: 컴뱃 오더스 미적용 (작업중)
배메: 오버로드 마나 없음, 마스터 오브 데스 활성화시 데스 최종데미지 오르는지 확인필요
에반: 현재 딜사이클이 조디악 너프 이전임
제로: 템셋을 따로 짜야됨, 리미트 막타

제가 알고있는 건 이정도입니다

**Comment by icepeng** [comment]
윈브쪽 작업중이시군요. 저도 막 윈브 보고있었는데 패시브에 "엘리멘탈 엑스퍼트"와 "엘리멘탈 하모니"의 효과가 뒤바뀌어 있는걸 확인했습니다. 수정에 포함 부탁드립니다.

**Comment by cheese98** [comment]
알겠습니다. 제로 PR 완료되면 공용스킬 코드 정리 정리 + 윈브 변경안 올리겠습니다.

**Comment by icepeng** [comment]
제로 PR에 get_weapon쪽 무기 가져오는것 변경도 포함이 되어있나요?

**Comment by cheese98** [comment]
그건 공용스킬 코드 정리에 포함돼있습니다. 만약 jobutils로 합치는 게 아니라면 밀고 다시 작업해야돼서 일단 기다리는 중입니다.

**Comment by icepeng** [comment]
공용스킬 코드 정리는 pr을 올리지 않은 상태인가요? 바쁘시면 draft 상태로 올려주시면 제가 보고 마무리 해보겠습니다.

**Comment by cheese98** [comment]
일단 #188 에 올렸습니다. #167 을 포함하고 있기 때문에 이게 먼저 적용이 돼야 합니다.

**Comment by cheese98** [comment]
> 윈브쪽 작업중이시군요. 저도 막 윈브 보고있었는데 패시브에 "엘리멘탈 엑스퍼트"와 "엘리멘탈 하모니"의 효과가 뒤바뀌어 있는걸 확인했습니다. 수정에 포함 부탁드립니다.

시그너스 전체에서 해당 문제가 발견되어 수정하고 PR 올렸습니다. (#192) 이것 역시 #167 이 먼저 적용되어야 합니다.

**Comment by cheese98** [comment]
보우마스터 아머 피어싱이 쿨감모자 효과를 받는다고 하네요. 지금은 평균값으로 정해놓은 것 같은데 나중에 수정해야 할 것 같습니다.

**Comment by cheese98** [comment]
뭔가 하나 빠진 것 같았는데 미하일이 빠져있네요.

**Comment by icepeng** [comment]
숨지마라, 미하일!!
