### ISSUE TITLE
전사 수치 관련 오류 수정

### ISSUE THREAD

**Issue by oleneyl** [oleneyl/maplestory_dpm_calc#19]
히어로 : 소드오브 버닝소울의 설치 딜레이는 0.82초
인사이징은 크리티컬에 한해 총데미지 20% 증가입니다
두손검 사용

팔라딘: 두손검 사용(두둔은 미사용)

확인 후 틀렸을 경우 반영 필요

**Comment by cheese98** [comment]
확인 결과 모든 내용 이상 없습니다. (인사이징 데미지는 25%가 맞음)
