### ISSUE TITLE
쿨감모자 구현 초안

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#193]
character.characterKernel.JobGenerator.py
---
```python
class JobGenerator():
    def __init__(self, vEhc = None):
        # 초반부 생략
        self.cdr_hat = 0

    def build(self, chtr, combat = False, storage_handler=None):
        # 초반부 생략
        if self.cdr_hat > 0:
            for each_element in all_elements:
                # 쿨타임이 0이거나 무한일 경우 스킵
                if each_element.skill.cooltime._mimic_target_constant == 0 or each_element.skill.cooltime._mimic_target_constant == 99999999:
                    continue
                # 쿨감 계산
                new_cooltime = each_element.skill.cooltime._mimic_target_constant - self.cdr_hat * 1000
                # 10초 미만일 경우 효과 반감
                if new_cooltime < 10000:
                    new_cooltime = (10000 + new_cooltime) / 2
                # 5초 미만으로 감소 불가
                each_element.skill.cooltime._mimic_target_constant = max(new_cooltime, 5000)
```
대충 이렇게 구상해봤고 듀블로 시험해본 결과 유의미한 딜 상승이 있는 것을 확인했습니다. (8500 기준 약 5.0조 -> 5.2조, 스탯 -21% 적용)

앞으로 생각해봐야 할 것은 다음 3가지입니다.
- [x] 유니온 메르쿨감 적용 (쿨감모보다 우선)
- [ ] 스탯퍼 감소 적용
- [x] 하이퍼스킬은 미적용이므로 구분 필요

많은 의견 부탁드립니다.

**Comment by icepeng** [comment]
메르쿨감 받는 스킬이 전부 쿨감모 효과도 받는다고 치면, 간단히 JobGenerator에 cdr_hat 요소를 추가하고, SkillWrapper쪽에서 red=True이면 해당 요소를 가져와서 메르쿨감과 같이 계산하면 됩니다.

메르쿨감은 받는데 쿨감모는 안받는 예외가 있나요?

**Comment by cheese98** [comment]
찾아보니 메르 유니온과 쿨감모는 하이퍼 제외한 모든 스킬에 적용되는 것 같습니다.

그런데 재사용 대기시간 초기화 어빌까지 생각하면 지금의 `red` 변수 하나로는 무리일 것 같습니다. 하지만 아직 여기까지는 생각을 자세히 못해봤습니다.

그리고 원래 쿨감이 10초 미만인 스킬에 예외처리를 해주는겋 깜빡했네요. 다음주쯤 수정본 올리겠습니다.

**Comment by icepeng** [comment]
쿨감 적용 안된다고 명시된 스킬 몇개가 있긴 합니다. 몇몇 스택형 스킬도 안되는 것 같습니다.

초기화 적용되는 스킬 범위가 쿨감이랑 다른지는 잘 모르겠네요. 따로 관리해야 한다면 `cooltime_reset` 추가해야 할거 같습니다.

**Comment by oleneyl** [comment]
위와 같은 구현은 약간 위험할 것 같습니다. 아마 cooltime 변수에 대한 직접접근이 금지되어 있어서 _mimic_target_constant 를 통한 접근이 불가피하셨던 것 같습니다.

문제라 함은, 프로그램 구조에 관련된 사항입니다. 위와 같은 구현이 나오게 된 이유는

- 그래프 build 이전의 모든 변수는, Object로 관리되고, 모든 연산이 track되도록 설계되어 있습니다. 즉, 
```python
each_element.skill.cooltime._mimic_target_constant = each_element.skill.cooltime._mimic_target_constant + (-500)
```
을 입력할 경우, 나중에 
```python
collection = GlobalOperation.export_collection()
configuration = collection.get_storage().export()
print(configuration)
```
을 통해 쿨타임이 원래 몇초였고, 500ms가 감소했다는 기록을 확인할 수 있습니다.

- 위와 같이 계산할 경우, 위같은 tracking이 불가능해지며, 관련된 연산에 해를 끼칠 수 있습니다.
- 따라서, 세 가지 방법 중 하나를 택해야 합니다.
  - convert_to_static()의 호출 이후 cooltime에 직접 접근하여 변경. 이 경우에는 (아마) `_mimic_target_constact` 를 사용하지 않아도 접근 가능합니다. 다만 그래프의 요소가 변화했다는 사실을 추적할 수 없습니다.
  - convert_to_static()의 호출 이전에 `DynamicVariableOperation.reveal_argument` 를 호출하여 cooltime에 직접 접근하여 변경. 이 경우에는 위 구현과 동일합니다만, 보다 코드가 안전해집니다.
  - convert_to_static()의 호출 이전에 `DynamicVariableOperation`의 max 연산과 뺄셈 연산을 구현해서 적용. 제일 안전하지만, 코드가 좀 복잡해집니다.

세 번째 방법이 제일 좋긴 해서, 괜찮으시다면 제가 한번 구현해서 올려보겠습니다.

**Comment by icepeng** [comment]
BuffSkillWrapper 등에 있는 _use에서 계산 가능하도록 BuffSkill정의에 인자를 추가로 넘기는 방법은 없나요?

**Comment by oleneyl** [comment]
@icepeng 그렇게도 가능합니다.

**Comment by icepeng** [comment]
* `AbstractCharacter`에 `cooltimeReduce`를 `cooltime_reduce`, `pcooltime_reduce`로 이원화
* `GraphElement`에 `red`로 전달되던 부분을 `cooltime_reduce`, `pcooltime_reduce`로 변경
* `GraphElement._use()` 메소드의 계산 로직을 변경

**Comment by icepeng** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/pull/281
https://github.com/oleneyl/maplestory_dpm_calc/pull/293

쿨감 구현은 끝났고, 어떻게 item template에 적용할지만 고려하면 됩니다.
