### ISSUE TITLE
오버로드 마나 확인 필요

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#195]
오버로드 마나는 소환수를 제외한 공격스킬 사용시에만 최종 데미지를 올려줍니다.

대표적으로 에반의 조디악 레이가 오버로드 마나의 효과를 받지 않으며, 불독의 퓨리 오브 이프리트도 마찬가지일 것으로 보입니다.

**Comment by oleneyl** [comment]
네 맞습니다. 이 스킬이 소환계열에 적용이 안됩니다.. 아마 OverloadMana.skill.pdamage_indep * -1로 입력을 주어야 할 것 같습니다.
