### ISSUE TITLE
방어구 에디셔널 설정에 관해

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#198]
유니온 7000 기준 `armorAPtnl = MDF(att = 21)` 으로 되어있는데, 이렇게 전 부위를 쭉 밀어버리면 공효율만 너무 내려가는 현상이 발생합니다. 주스탯 4%, 공격력 10으로 변경하는 것을 제안합니다.

유니온 8000기준 `armorAPtnl = MDF(att = 11, pstat_main = 7)` 으로 되어있는데, 어떻게 정해진 값인지 궁금합니다.

에픽 토드로 2.5줄이라면 주스탯 4%, 공격력10, 주스탯 2%로 해서 `pstat_main=6, att=10`입니다.

유니크에서는 주스탯이 첫줄 5%, 나머지 4%, 공격력이 첫줄 12 나머지 11로 나오므로 어느쪽과도 맞지 않습니다.

유니온 8500기준 에디 레전 3줄이라고 되어있는데, `armorAPtnl = MDF(att = 14, pstat_main = 7)`로 되어있습니다.

에디 레전 첫줄에는 주스탯 7%, 올스탯 5%, 공격력 +14가 나옵니다.

2~3줄에는 주스탯 5%, 올스탯 4%, 공격력 +12가 나옵니다.

어떻게 조합해도 에디 레전 3줄에서 해당 수치가 나오지 않는 것 같습니다.

**Comment by oleneyl** [comment]
- 네 그렇게 변경하는게 좋을 것 같습니다.
- 2, 3줄이 섞여있다고 가정했던 수치입니다. 2.5줄로 못박는게 나을 것 같습니다.
- 에디 레전 수치 또한 바꾸는게 맞는 것 같습니다.
