### ISSUE TITLE
섀도어 : 킬링포인트

### ISSUE THREAD

**Issue by oleneyl** [oleneyl/maplestory_dpm_calc#21]
1. 킬링포인트 3스텍 적용확률이 첫타 34%막타 91%에서 첫타 19 막타 80%로 감소

2. 소닉블로우 쿨타임 감소도 1.5초가 아니라 암살의 막타 킬링포인트가 적용될때 1.5초기때문에 1.5초에 막타 킬링포인트 3스텍 적용확률을 곱하여야함

**Comment by oleneyl** [comment]
cite :: http://m.inven.co.kr/board/powerbbs.php?come_idx=2297&stype=subject&svalue=%EC%8A%A4%ED%83%9D&l=52201

**Comment by cheese98** [comment]
[반영 완료됐습니다](https://github.com/oleneyl/maplestory_dpm_calc/commit/b0a389c76627ed52e1c8ef1ac77da12e86256cd7)
