### ISSUE TITLE
무기 위대한 소울 효과 누락

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#218]
코드상에서 위대한 소울의 옵션 적용하는 부분이 보이지 않습니다.

크확 부족 직업군의 경우 유니온 배치 과정에서 크확때문에 칸 손해를 꽤 보고있는데, package 과정에서 무기 소울을 크확/공퍼/보공중에 골라서 장착하도록 해야 하지 않나 싶습니다.

**Comment by oleneyl** [comment]
네 소울옵션이 현재로는 적용되어 있지 않습니다.
그럼 최적화 과정에 별도로 추가해주어야겠네요.
