### ISSUE TITLE
6000~ 구간 무기류 잠재 기준

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#219]
지금 6000 이상은 weaponstat = [4, 9]로 되어있어서 3부위 다 레전 3줄로 들어가고 있는데, 다른 부위에 비해 균형이 안맞아 보입니다.

무기 보조는 어떻게든 산다고 쳐도 엠블까지 생각하면 영...

6000 - [4, 7]
7000 - [4, 8]

정도로 기준을 변경하는 것을 제안합니다.

**Comment by icepeng** [comment]
@oleneyl @cheese98

**Comment by oleneyl** [comment]
음..괜찮을것같습니다.

**Comment by cheese98** [comment]
저도 동의합니다.
