### ISSUE TITLE
제로 구현방식을 바꿔야 할 것 같습니다

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#225]
현재는 `AlphaState`와 `BetaState`를 번갈아가면서 켜주는 방식으로 돌아가는데 이러면 디바인 리어 도트뎀이 베타 상태에서 들어가는 경우가 발생할 수 있습니다. 그래서 귀찮더라도 일반 스킬에 하나하나 modifier를 직접 넣는 게 좋긴 한데 문제는 공용 스킬입니다. 어떻게 해야 할까요...

**Comment by icepeng** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/pull/220

이 pr에서 좀 대충 한 느낌이 있긴 합니다.

전 알파<->베타 전환이 10초 이상 안되는 경우는 없다고 가정했습니다.

**Comment by cheese98** [comment]
원래 데미지가 약한 스킬이라 큰 영향 없을 것 같긴 합니다. 나중에 리미트 수정할때 같이 하면 될 것 같습니다.

**Comment by icepeng** [comment]
그러게요. 기본을 아예 비우고, 알파/베타를 버프로 하는게 맞아보입니다.

**Comment by cheese98** [comment]
기본을 아예 비우면 스공계산이 망가질 위험이 있다고 생각됩니다.

일단 현행유지하되 베이스 상태에서는 크확을 베타랑 맞춰놓는 게 좋을 것 같습니다.

**Comment by icepeng** [comment]
기본을 비우고, `get_modifier_optimization_hint`쪽을 적당히 건드리는게 맞다고 생각합니다.

#229는 크확 관련 문제 해결되고 나면 merge하겠습니다.

**Comment by oleneyl** [comment]
버프 전환을 넣을 경우에는 전환이 즉각적으로 이루어지는지 여부가 좀 중요할 것 같습니다. onBefore()메서드 호출로 충분할 지 잘 모르겠네요. 연산량도 조금 많이 늘어날 거고..

**Comment by icepeng** [comment]
그 부분이 문제라면 신궁처럼 아예 스킬마다 Modifier를 박아넣는 식으로 해야할것 같네요.

**Comment by cheese98** [comment]
제가 잘못 알고 있었던 것 같네요. 신뢰도 있는 곳에서 확인해보도록 하겠습니다.
