### ISSUE TITLE
렙뻥, 포뻥 적용에 대한 논의

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#232]
처음에는 렙뻥, 포뻥 적용 유무가 그리 중요하지 않다고 생각했으나 맥뎀을 고려하면 중요하다고 생각합니다.

1.6배의 차이는 원래 70억이 뜨는 것도 112억이 되어 12억의 Loss를 만들 정도의 차이입니다.

어째서 8500 스펙에서도 맥뎀에 막히는 스킬이 거의 없는지 조사하던 도중 느낀 점입니다.

적용을 해야할지, 적용한다면 어떤 식으로 해야할지 논의가 필요합니다.

@oleneyl @cheese98

**Comment by cheese98** [comment]
가능하면 지금 상태 DPM을 베이스로 두고 포뻥렙뻥, 리부트, 무릉 같은 걸 기타 옵션으로 추가하면 좋을 것 같네요.

**Comment by oleneyl** [comment]
DPM 연산과정에서 공격을 당하는 대상에 대한 옵션을 주는 방식으로 구현하는게 좋을 것 같습니다.

**Comment by icepeng** [comment]
일단 core/constant에 계수를 적어두도록 함.
