### ISSUE TITLE
나워 쉐도우 일루전

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#237]
기존 서번트에 50%짜리 그림자랑 30%짜리 그림자를 2개 더 생성하는 스킬인데 코드에는 이걸 다 합산해버렸네요. 다른 쉐파류 직업들처럼 맥뎀 문제가 생기는 건 물론이고 쉐도우 배트 사출도 정상적으로 반영되지 않았을 가능성이 높습니다.

`create_auxilary_attack`를 잘 써먹으면 깔끔하게 만들 수 있을 것 같긴 한데...

**Comment by icepeng** [comment]
그러네요. 수정해보겠습니다. 제가 나워를 잘 몰라서 그런데, 배트가 시커마냥 같은 대상에 여러번 튕기기도 하나요?

**Comment by cheese98** [comment]
슬프게도 제 나워 레벨이 너무 낮고 무릉 허수아비도 없어서 테스트가 불가능합니다.

**Comment by icepeng** [comment]
40초 영상 찾아보고 오겠습니다. 일루전은 일단 퀸터를 일일이 70% 50% 30% 만들어서 처리해두겠습니다.

**Comment by icepeng** [comment]
아, 70%는 그대로 두고 50% 30%만 하면 되겠네요.

**Comment by icepeng** [comment]
수정을 하긴 했는데, 배트 점유율이 말도 안되게 찍혀서 좀 찾아보니 배트가 발동에 자체 쿨타임이 좀 있네요.

https://youtu.be/D1xHp-BPA14

자체 쿨타임이라기 보단 오비탈처럼 날아가고 있는 배트가 최대 제한인 4개에 포함되는가 싶기도 하고... 사출 확률이나 주기를 좀 조정해야지 싶습니다.

**Comment by cheese98** [comment]
논의장소를 #238 으로 통일시키기 위해 이 이슈는 닫도록 하겠습니다.
