### ISSUE TITLE
공용 0차 스킬 적용할 것

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#267]
여제의 축복(공마 30)
연합의 의지(올스탯 5, 공마 5) - 제로는 획득 불가
영웅의 메아리 - 적용 여부 논의해야 함

**Comment by cheese98** [comment]
영메는 자체 풀가동 직업만 패시브로 올라간 걸로 알고 있습니다.

**Comment by icepeng** [comment]
영메는 가동률 적용해야 하지 않을까요?

**Comment by cheese98** [comment]
나제불 DPM에서는 초기화 가능한 직업만 적용되어 있는 걸로 알고 있습니다. 일본 DPM에서는 전직업 적용 상태인 것 같고요.

표준 측정시간이 30분이라 쿨타임이 있는 노블버프를 포함시킨다면 영메도 포함이 돼야 한다고 생각합니다.

**Comment by icepeng** [comment]
측정 시간 30분은 "적당히 긴 시간"의 의미만 가지고, 30분이라는 것 자체가 중요하진 않다...라고 생각합니다. 실제로는 infinite를 가정하지만 어쩔 수 없이 30분치만 재는 것에 가깝습니다.

그런 의미에서 영메는 좀 변형해서 적용하거나 해야겠네요. 패시브로 두고, 효과에 초기화를 고려한 가동률을 곱하는게 좋겠습니다.

**Comment by cheese98** [comment]
그렇다면 초기화 스킬이 없는 직업중에 재사용 어빌이나 쿨감 가속효과 있는 직업만 주의하면 되겠네요.

**Comment by icepeng** [comment]
노블이 포함된 시점에서 영메도 그냥 도핑 취급하는게 맞겠습니다. 영메를 도핑에 추가하는 쪽으로 하겠습니다.
