### ISSUE TITLE
리미트 브레이크 막타

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#27]
> 종료될 때 발동 시 공격에 적중된 적이 살아있다면 스킬 지속 중 제로가 해당 적에게 가한 피해의 20%를 15번에 걸쳐 나눠 받음

스킬 막타의 데미지가 일반적인 스킬들과는 다르게 지속 시간동안 입힌 피해의 일부인데 어떻게 구현해야 될지 잘 모르겠네요.

**Comment by cheese98** [comment]
```python
class LimitBreakNew():
    def __init__(self, enhancer, skill_importance, enhance_importance):
        self.damage_start = 0
        self.damage_end = 0
        self.analytics = core.Analytics()
        self.vLevel = enhancer.getV(skill_importance, enhance_importance)

        self.LimitBreakAttack = core.DamageSkill("리미트 브레이크", 0, 400+15*self.vLevel, 5).isV(enhancer, skill_importance, enhance_importance).wrap(core.DamageSkillWrapper)
        self.LimitBreak = core.BuffSkill("리미트 브레이크(버프)", 450, (30+self.vLevel//2)*1000, pdamage_indep = (30+self.vLevel//5) * 1.2 + 20, cooltime = 240*1000).isV(enhancer, skill_importance, enhance_importance).wrap(core.BuffSkillWrapper)
        self.LimitBreak.onAfter(self.LimitBreakAttack)
        
    def LimitBreakStart(self):
        self.damage_start = self.analytics.total_damage
        return LimitBreak

    def LimitBreakEnd(self):
        self.damage_end = self.analytics.total_damage - self.damage_start
        # 지속시간 동안 가한 데미지의 20% / 15
        # 퍼뎀이 아니라 고정값으로 뜨게 수정해야 함
        return core.DamageSkill("리미트 브레이크(막타)", 0, damage_end / 75, 15).wrap(core.DamageSkillWrapper)
```

혼자서 작성하다가 잘 모르겠어서 일단 올려봅니다.
클래스를 선언하면 변수 및 스킬들을 만든 후 딜량을 받기 위해 core.Analytics를 가져옵니다. 
LimitBreakStart 메서드를 실행하면 현재 딜량을 저장한 후 LimitBreak 스킬을 리턴합니다.
LimitBreakEnd 메서드를 실행하면 딜량을 받아와서 LimitBreakStart에서 저장한 딜량과의 차이만큼 피해를 줍니다.
----
문제점은 이런 식으로 core.Analytics가 일개 직업 코드에서 불러올 수 있는 클래스인지, 그리고 이렇게 작성해도 정상 작동하는지 잘 모르겠습니다. 그리고 데미지의 차이만큼 피해를 줘야 하는데, core.DamageSkill은 스킬 퍼뎀을 입력하는 방식이라 고정 피해를 주려면 어떻게 해야 할지도 모르겠습니다.

솔직히 말하면 아예 모르겠습니다. 한번 읽어봐주시면 감사하겠습니다.

**Comment by oleneyl** [comment]
현재로는 계산 알고리즘 작성 구문에서 연산과정에 접근을 할 수 없도록 encapsulation되어 있습니다. 리미트 브레이크류 데미지 계산을 위해서 해당 기능을 위한 장치를 추가하여야 할 것 같습니다.

**Comment by cheese98** [comment]
아직 내부 구조까지 들여다볼 정도로 이해하지 못해서 일단은 보류해야겠네요 ㅠ
