### ISSUE TITLE
전직업 컴뱃 오더스 반영 현황

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#270]
일단 전직업 공통 사용하지 않는중, 수치 입력되었는가 여부만 체크

## 모험가

- [x] 히어로
- [x] 팔라딘 - 자체 오더스 기준으로 입력되어 있음
- [x] 다크나이트
- [x] 아크메이지불/독
- [x] 아크메이지썬/콜
- [x] 비숍
- [x] 보우마스터
- [x] 신궁
- [x] 패스파인더
- [x] 나이트로드
- [x] 섀도어
- [x] 듀얼블레이드
- [x] 바이퍼
- [x] 캡틴
- [x] 캐논슈터

## 시그너스

- [x] 소울마스터
- [x] 플레임위자드
- [x] 윈드브레이커
- [x] 나이트워커
- [x] 스트라이커
- [x] 미하일

## 레지스탕스+데몬

- [x] 블래스터
- [x] 배틀메이지
- [x] 와일드헌터
- [x] 메카닉
- [ ] 제논 (미구현)
- [x] 데몬슬레이어
- [x] 데몬어벤져 (미구현)

## 영웅

- [x] 아란
- [x] 에반
- [x] 루미너스
- [x] 메르세데스
- [x] 팬텀
- [x] 은월

## 노바

- [x] 카이저
- [x] 카데나
- [x] 엔젤릭버스터

## 레프

- [x] 아델
- [x] 일리움
- [x] 아크

## 혼밥

- [x] 제로
- [x] 키네시스
- [x] 호영 (미구현)

**Comment by cheese98** [comment]
제로는 쓸컴뱃과의 시너지가 최악인 직업이라 완료로 가정하고 체크해두셔도 될 것 같습니다.

**Comment by cheese98** [comment]
#303: 호영
#323: 미하일 (여기서도 빠져있네요)
#342: 불독, 썬콜, 데몬어벤져

코드가 아예 없는 제논을 제외하고는 완료됐습니다.

이제 일부 직업에서 미적용된 사항들 (더블 럭키 다이스 등)만 해결하면 완전히 끝납니다.

**Comment by icepeng** [comment]
로디드 공식 정리해뒀습니다

https://github.com/oleneyl/maplestory_dpm_calc/issues/314

**Comment by cheese98** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/blob/c22bdeecf44f8e41179f82c9ae904a932b97df6d/dpmModule/jobs/cannonshooter.py#L84
https://github.com/oleneyl/maplestory_dpm_calc/blob/c22bdeecf44f8e41179f82c9ae904a932b97df6d/dpmModule/jobs/captain.py#L113
https://github.com/oleneyl/maplestory_dpm_calc/blob/c22bdeecf44f8e41179f82c9ae904a932b97df6d/dpmModule/jobs/viper.py#L93
https://github.com/oleneyl/maplestory_dpm_calc/blob/c22bdeecf44f8e41179f82c9ae904a932b97df6d/dpmModule/jobs/mechanic.py#L107
고치려고 들어가봤는데 코드가 다 달라서 좀 난해하네요.

메카닉, 캐논슈터는 관련 하이퍼 스킬이 없고, 캡틴이랑 바이퍼는 공격스킬 vs 다이스 중에서 뭘 선택하느냐에 따라 갈릴 것 같네요.

일단 메카닉이랑 캐슈에 `20+10/6+10/6*(5/6+1/11)*(10*(5+passive_level)*0.01)` 넣어주고 나머지 둘은 하이퍼 적용여부에 따라서 적당히 바꿔주면 되나요?

**Comment by icepeng** [comment]
바이퍼는 계산을 좀 해봐야하고, 캡틴은 그냥 래피드 3종+헤드샷 리인포스,보너스어택 하면 됩니다.
