### ISSUE TITLE
직업별로 보조무기 스펙 차이 문제

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#277]
```
===subweapon===
name : 보조무기, level : 100
stat_main : 10.0, stat_sub 10.0
pstat_main : 0.0, pstat_sub 0.0
att : 3.0, patt 0.0
pdamage : 0.0, armor_ignore 0.0
==potential==
pstat_main : 0.0, pstat_sub 0.0
att : 0.0, patt 21.0
pdamage : 0.0, armor_ignore 0.0
crit : 0.0, crit_damage 0.0
==additional_potential==
pstat_main : 0.0, pstat_sub 0.0
att : 0.0, patt 6.0
pdamage : 0.0, armor_ignore 0.0
crit : 0.0, crit_damage 0.0
```
팬텀의 경우 보조무기 자체 능력치가 아예 없지만 코드 상에는 주스탯 10, 부스탯 10, 공격력 3이 붙어있습니다.

https://github.com/oleneyl/maplestory_dpm_calc/blob/fc131a0beb69965f3029acfd11cb7d1a5bd00f0a/dpmModule/item/Default.py#L12

이 현상의 원인은 보조무기의 기본 능력치가 일괄적으로 설정되어 있기 때문입니다.

해당 코드의 모든 값을 0으로 고치고 직업별로 각각 보조무기 기본 능력치를 집어넣는 게 좋겠습니다.

일부 직업의 경우 스펙에 따라 보조무기 자체가 바뀌는 경우도 있기 때문에 직업 코드에 직접 삽입하는 것보다는 Item 모듈 안에서 해결했으면 좋겠습니다.

**Comment by icepeng** [comment]
resolved by #696
