### ISSUE TITLE
시뮬 시간 질문

### ISSUE THREAD

**Issue by int11** [oleneyl/maplestory_dpm_calc#28]
1. 저가 알기론 시뮬방식에 시간은 전직업 모두 450초로 딜하는걸로 가정하고 dpm계산하는걸로 알고있는데 맞나요?

2. 맞다면 450초에서 딜시간을 변경해보셨는지 궁금합니다. 딜시간을 모든 쿨타임의 최소공배수로 수렴하게 더 늘려도 dpm수치는 변동이 별로 없기때문에 그냥 냅두시는건지?

여담으론 코드를 볼려고했는데 저의 기준으로 심각하게 복잡하네요. 
소프트웨어 , 컴퓨터 전공 쪽 이신가요?
저는 전공자는 아니라 취미로 하는지라 함수가 심각하게 세분화돼있어서 복잡하다고 해야되나요.  참고할려고 봤지만 저로선 너무 보기힘드네요 ㅠㅠ
그리고 혹시 '신궁좀살려줘' 님 dpm정보 제공에 대해선 어떻게 되셨나요. dpm제작중단글 본문에선 "수정후 공개하겠다" 라고 되있는데 정보를 제공받으신게 있으신지...
저또한 oleneyl 님과는 많이 다른 방식으로 똑같은 DPM시뮬을 제작중이라 여기에 대해서도 궁금하네요.

**Comment by oleneyl** [comment]
1,2.  dpm 계산에서 그래프 도시를 위해서만 450초로 계산되어 있습니다. 이는 장시간의 계산 결과를 출력할 경우 데이터의 양이 과도하게 많아지기 때문입니다. 반면 순위 측정을 위한 dpm에서는 1800초(30분)을 기준으로 측정되어 있습니다. 따라서 시간에 따른 신뢰성 문제는 걱정하지 않으셔도 괜찮습니다.

음 컴퓨터 전공은 아닙니다. 저도 취미로 만들어 본 코드에요 ㅋㅋ
코드가 약간 복잡한 이유가 dpm에 연계되는 각각의 변수들을 추적하기 위해서.. 코드가 조금 복잡합니다. 그래프 구조를 설정한 뒤에 컴파일을 통해 실행을 위한 그래프를 받아와서 돌리는 구조입니다.
제 코딩 실력이 부족한 점도 있고요. 고쳐야 할 점이 아직 많습니다ㅠㅠ

혹시 궁금하신 점이 있다면 언제든 이슈나 댓글 달아주세요!

+ 혹시 만들고 계신 dpm시뮬은 어떤방식인지 여쭈어봐도 괜찮을까요? 어떤 방법으로 접근하고 계신지 궁금합니다. 더 나은 방식이라면 새로운 방식으로 재설계하는 것도 생각해보고 있긴 해서요..

+ '신궁좀살려줘' 님께 제공받은 자료는 전무합니다. 아예 손을 떼신 것으로 보이네요..

**Comment by injea1291** [comment]
'수정 후 공개하겠다.' 는 일단 하신 말씀인가 보네요. 저번에 물어보니 자료 제공하는 것이 '이득' 보다 '실' 이 더 많아서 따로 공개하긴 어렵다고 하더라고요.

개인적인 의견이지만 투자하신 시간도 있으시고 자료를 공짜로 다 공개하시는 게 정보화 시대에서 신궁님이 가지고 있는 '정보'라는 가치가  한국 한정으로 왠만한  게임하는 사람들이 다 알고있는  대규모 온라인 게임을 영향을 미칠 정도의 큰 가치가 있어서 제공하시기가 많이 힘드신가 봐요.

대규모 온라인게임에서 자신들 게임 직업의 데미지 알고리즘으로 평균 딜 수치를 계산 못 해서 개인 유저가 만든 걸로 밸런싱 패치를 하는걸 보면 답도 없긴 한데
 돈도 많이 벌면 통계학, 시뮬 전공 쪽 사람 한 명 구해서 전문적으로 계산 하는 게 본인들 밸런싱 패치도 좋을 텐데 모리 사건 터진 후 지금까지 이러는 거 보면 어찌 보면 "개돼지들이 알아서 계산하겠지" 생각하고 내버려 둬 버리는 걸지도...
한번 "모든 사람들이 DPM 수치를 넥슨에 제공 안 하는 쪽으로 가는 것도 어떨까?"라는 이상한 생각도 해본 적이 있네요. ㅋㅋ 이걸만든다고 넥슨이 돈 주는 것도 아니고 자신들 밑으로 취직 도 안시켜주니...

어쨌든 신궁님의 마음은 어느 정도 이해하는 편이고 몇 년 동안 개인적인 시간 투자해서 모은 자료를 쉽게 제공하긴 힘드실 듯. 일단 분명 넥슨에서도 자료 가져다 쓸태니 전체 공개로 하는건 저도 비추.

저가 접근하는 방식으론 일단 DB로 따로 데이터,수치를 모으고 정리. SQL으로 접근하긴 너무 어려우니 쉬운 엑셀로. 계산은 파이썬에서 동기화가 아닌 비동기화 방식으로 접근하고있습니다. 자세한건 여기 다 적긴 힘드니 생략할게요 ㅋㅋㅋ

**Comment by oleneyl** [comment]
ㅋㅋㅋ그러게요.. 뭐 지금으로서는 이게 최선인 것 같습니다.
계산방식이 아니라 아키텍처 측면에서 다른거군요 ㅋㅋ DB를 활용하는것도 좋은 것 같습니다.

혹시 계산에 쓰인 세부 정보가 필요하시면 레포에서 jobs/ 안의 값을 직접 열어서 참조하시거나, '''kernel.graph.export_configuration''' 함수를 사용하여 계산에 사용되는 모든 변수를 JSON으로 받아보시면 될 것 같습니다!

잘 되시기를 빕니다 ㅎㅎ
