### ISSUE TITLE
신5차 정보 정리

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#282]
### 메카 캐리어

70초간 총 사용횟수 228회, 228*4=912타

9 + 10 + 11 + 12 + 13 + 14 + 15 + 16*9

70초간 총 16회 사출

공격 간격 2850ms + 함재기 1개당 120ms씩 추가

3930ms -> 4770ms

**Comment by cheese98** [comment]
렐릭 언바운드
---
측정기준: 마왕 발록 공격, 시전 후 블래스트-디스차지 매크로 난사

디스차지: 177회 / 177타

**Comment by cheese98** [comment]
멸귀참영진
---
시전 6초 후 우두머리 등장

협력자 공격은 6초 동안 풀히트되게 계산해서 적용하면 될 것 같습니다.

**Comment by cheese98** [comment]
하울링 피스트
---
22회 / 188타

총 시전시간 4초로 추정

막타가 140타이므로 첫타는 48타

**Comment by cheese98** [comment]
파쇄 연권
---
11회 / 85타
지속 공격 40타 (8회)
막타 45타 (3회)

**Comment by OniOniOn-** [comment]
볼텍스 스피어
-----
17회*6타
타당 딜레이 180ms
볼텍스 스피어 타격을 위해 허수아비랑 거리를 벌려서 하울링 게일 56타로 감소
