### ISSUE TITLE
천공의 노래 데미지% 확인 필요

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#285]
#276 에서 천공의 노래 컴뱃 오더스 적용에 따른 데미지% 효과를 적용했는데, 데미지 공식이 다르다는 제보가 있습니다.

스킬 설명에는 타겟 수 감소당 데미지%가 `5+u(x/2)`로 되어있으나, 실제로는 `5+d(x/2)` 으로 적용된다고 합니다.

클라이언트 값을 보면 `x = 100+5+d(x/2)`, `y=5+u(x/2)`로 적혀있습니다. 여기서 스킬 툴팁은 y로 보여주고 계산은 x를 사용하는것 같습니다.

30레벨을 기준으로 하면 20%로 동일하나, 31레벨에선 20%와 21%의 차이가 생기므로 확인이 필요합니다.

http://kaedekouyou.blog97.fc2.com/blog-entry-1062.html

2016년에 실험된 자료라 최근에 수정 되었는지 실험해야 합니다.

+추가) 아란의 비욘더, 펜릴 크래시도 같은 로직을 사용하니 함께 확인해야 합니다.

**Comment by OniOniOn-** [comment]
5+u(x/2)와 5+d(x/2)의 차이점은 모르겠는데, 일단 31레벨에서 21%가 맞습니다. 인게임에서 쓸컴뱃 사용 후 오르는 것을 확인했습니다.

**Comment by icepeng** [comment]
실제로 적용이 안된다는 뜻이 맞습니다.

u와 d의 차이는 올림, 버림 차이입니다. 툴팁상으론 올림이 적용되고 실제로는 버림이 적용된다는 말이 있어서 그렇습니다.

**Comment by OniOniOn-** [comment]
![image](https://user-images.githubusercontent.com/6011621/91087039-c7c9fc00-e68a-11ea-8f83-76854033ce95.png)

**Comment by icepeng** [comment]
아란은 데미지% 고정 6으로 되어있어 문제 없는것 확인.
