### ISSUE TITLE
배틀메이지 오버로드 마나 미사용, 블랙 매직 알터 변경사항 미구현

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#311]
오버로드 마나 같은 경우는 넣을지 말지 논의가 필요합니다.

블랙 매직 알터는 예전에 구현하려 했었는데 배메 딜사이클을 몰라서 포기했었습니다...

**Comment by icepeng** [comment]
오버로드 마나는 사실상 못쓰는 직업이 더 많습니다.

https://github.com/Monolith11/memo/issues/36

이쪽에 정리를 해두긴 했는데 포션 쿨타임 10초로 잡았을 때의 얘기입니다.

그리고 못쓰는 직업이라도 극딜때 잠시 켜는정도는 가능하기도 하고... MP통 자체를 StackSkill로 취급해서 시뮬레이션에 포함하는 방법이 있긴합니다. 안그래도 매직 서킷 풀드라이브 때문에 필요했던거라...

**Comment by cheese98** [comment]
MP통을 구현하는데 성공한다면 제논에도 적용 가능할 것 같긴 한데, 아직은 너무 먼 얘기 같네요...

**Comment by icepeng** [comment]
오버로드 마나는 이미 적용되는 스킬에만 `modifier = core.CharacterModifier(pdamage_indep = 8+vEhc.getV(3,3)//10)` 붙여서 동작하고 있네요. 다만 좀 명시적으로 바꿔줄 필요가 있겠습니다.

**Comment by icepeng** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/pull/372
