### ISSUE TITLE
로디드 다이스 정리

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#314]
딜레이 직업마다 다름 990ms / 1500ms 중 하나

메카닉은 메탈아머 탑승중에는 딜레이가 무시됨

1~4차에 다이스 있는 직업은 벞지 받고, 없는 직업은 벞지 안받음

더블 럭키 다이스 + 로디드 뎀퍼 기댓값 `20+10/6+10/6*(5/6+1/11)*(10*(5+컴뱃+패시브레벨)*0.01)`

**Comment by cheese98** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/blob/c22bdeecf44f8e41179f82c9ae904a932b97df6d/dpmModule/jobs/cannonshooter.py#L84
https://github.com/oleneyl/maplestory_dpm_calc/blob/c22bdeecf44f8e41179f82c9ae904a932b97df6d/dpmModule/jobs/captain.py#L113
https://github.com/oleneyl/maplestory_dpm_calc/blob/c22bdeecf44f8e41179f82c9ae904a932b97df6d/dpmModule/jobs/viper.py#L93
https://github.com/oleneyl/maplestory_dpm_calc/blob/c22bdeecf44f8e41179f82c9ae904a932b97df6d/dpmModule/jobs/mechanic.py#L107
고치려고 들어가봤는데 코드가 다 달라서 좀 난해하네요.

메카닉, 캐논슈터는 관련 하이퍼 스킬이 없고, 캡틴이랑 바이퍼는 공격스킬 vs 다이스 중에서 뭘 선택하느냐에 따라 갈릴 것 같네요.

일단 메카닉이랑 캐슈에 `20+10/6+10/6*(5/6+1/11)*(10*(5+passive_level)*0.01)` 넣어주고 나머지 둘은 하이퍼 적용여부에 따라서 적당히 바꿔주면 되나요?

**Comment by icepeng** [comment]
바이퍼는 계산을 좀 해봐야하고, 캡틴은 그냥 래피드 3종+헤드샷 리인포스,보너스어택 하면 됩니다.

**Comment by cheese98** [comment]
그럼 바이퍼 제외하고 3직업은 위에 있는 식 넣으면 되나요?

**Comment by icepeng** [comment]
네. 바이퍼는 제가 작업하면서 계산해둘게요.
