### ISSUE TITLE
아란 피드백

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#324]
- [ ] 비욘더: 이 스킬은 액티브(즉발) 스킬임에도 불구하고 레전드리 어빌리티의 '패시브 스킬 레벨 1 증가' 효과의 영향을 받아 마스터 레벨이 31로 적용된다. 다만 쓸만한 컴뱃 오더스를 사용하면 마스터 레벨이 31로 오르며 32로는 오르지 않기때문에 쓸컴뱃을 사용한다면 아무런 효과가 없다. (출처: [나무위키](https://namu.wiki/w/%EC%95%84%EB%9E%80(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)/%EC%8A%A4%ED%82%AC#s-6.1))
- [x] 저지먼트
*   도트딜 미적용돼있음.
*   도트딜에도 스위프트 무브가 적용되는가?
*   아드레날린일때는 저지먼트가 비활성화되는가?

제 아란이 쓸컴뱃도 없고 어빌도 레전이 아니라서 직접 테스트가 불가능합니다... 확인 가능하신 분께서 대신 알아봐주시면 감사하겠습니다.

비욘더, 스매쉬 스윙 등의 각종 파동 및 잔상류 스킬에는 패시브가 미적용인지도 확인해봐야 합니다.

나중에 정리할때 어질러져 있는 패시브 스킬 코드도 깔끔하게 정리하겠습니다.

**Comment by icepeng** [comment]
일단 저지먼트가 딜사이클에 안들어가서, 비욘더만 체크해도 될겁니다.
