### ISSUE TITLE
에반 피드백

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#325]
에반
----
서클 오브 마나 데미지값 재확인 필요
* 30레벨 기준 290\*4 + 330\*4이면 315\*8이 아니라 310\*8이 돼야 합니다.
* 가능하면 평균치를 쓰지 않고 직접 구현하는 것이 더 좋을듯합니다.
* 데미지값 차이와 컴뱃 계수는 연관이 없으므로 컴뱃 적용은 완료됐습니다.

드래곤 브레스 ~쿨타임~, 기존스킬 뎀퍼
* 쿨타임: 툴팁상에는 10초, 코드상에는 7.5초
* 서클오브윈드 (1): 퍼뎀, 타수 이상함
* 드래곤 스위프트 (2): 없음
* 서클 오브 썬더 (1): 적용은 했으나 퍼뎀 이상함
* 다이브 오브 썬더 (1): 없음

~다크 포그: 미구현 (미사용인가요?)~

(from #303)

**Comment by icepeng** [comment]
윈드 썬더 어스는 신5차때 타수 퍼뎀 패치가

**Comment by icepeng** [comment]
브레스 쿨타임은 하이퍼에 쿨타임 리듀스 25%가 있습니다. 10000*0.75가 더 와닿겠네요.

**Comment by cheese98** [comment]
브레스 쿨타임이 그렇게 된게 하이퍼 스킬 때문이었군요. 그러면 제가 자료조사 좀 더 해보고 나머지 직접 고치겠습니다.

서클오브마나는 `DamageSkill` 하나 더 만들어서 `onAfter`로 이어붙이면 될까요?

**Comment by icepeng** [comment]
마나캔슬을 고려안하면 이어붙이면 됩니다. 1,2타 각각 딜레이는 아마 일본 자료에서 찾을수 있을겁니다.

아마 윈드 썬더 어스 딜레이도 좀 바뀌었을거예요.

**Comment by cheese98** [comment]
알겠습니다. 전직업 컴뱃 적용 끝나면 에반 포함해서 오류 발견되거나 누락된 직업들 수정 들어가겠습니다.

**Comment by icepeng** [comment]
#377
