### ISSUE TITLE
카이저 피드백

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#326]
인퍼널 브레스
* 쿨타임이 미적용돼있음
  * 적용시 쿨타임: `(20-self._combat)/*1000`
* 도트 데미지 미구현

(from #303)

**Comment by necromid** [comment]
인퍼널 브레스는 도트 데미지라고 써있지만 일반 데미지형식으로 들어감, 확인 필요

**Comment by icepeng** [comment]
도트뎀과 타일뎀은 구분해야 합니다. 인퍼널은 타일뎀입니다.
