### ISSUE TITLE
캡틴 리뷰

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#330]
컨티뉴얼 에이밍 - 시전 동작이 미적용되어 있음
  한번 발동하면 끝까지 가는 스킬이긴 하지만 시전 동작이 필요하긴 합니다.

배틀쉽 봄버
  패치 적용 필요: 지속시간 30초 -> 60초, 쿨타임 60초 -> 30초
  딜사이클이 망가질까봐 아직 건드리지 못했습니다.

카운터어택 미구현
  동일한 스킬이 바이퍼에는 있으므로 캡틴에도 추가해야 할 것 같습니다.

로디드 다이스 (패시브)
  구현되어 있으나 미적용

더블 럭키 다이스
  모험가 해적 직업 일괄적용을 위해 보류

**Comment by icepeng** [comment]
컨티뉴얼 에이밍 -> dpm 정의상 미리 사용해두고 측정 시작했다고 보는게 자연스럽습니다.
배틀쉽 봄버 -> 수정완료
카운터 어택 -> 일단 바이퍼에도 뺄 생각이라 안넣었습니다.
로디드 패시브 -> 수정완료
더블 럭키 다이스 -> 적용되었음
