### ISSUE TITLE
제로 수정 계획

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#336]
**#339 에서 진행중**

~1. 스킬에 직접 modifier 적용~
```
At Time 24200.0, Skill [어드밴스드 파워 스텀프] ... Damage [3726647095.2] ... Loss [0.0] ... Delay [570.0] ... Spec [damage]
crit rate : 5.0, crit damage : -42.0
pdamage : 93.0, pdamage_indep : 438.6
stat_main : 185.8, stat_sub : 2.0
pstat_main : 0.0, pstat_sub : 0.0
stat_main_fixed : 0.0, stat_sub_fixed : 0.0
boss_pdamage : 30.0, armor_ignore : 2.9
att : 60.0, patt : 4.0
damageFactor : 0.0

At Time 27500.0, Skill [어드밴스드 파워 스텀프(태그)] ... Damage [4721618914.4] ... Loss [0.0] ... Delay [0.0] ... Spec [damage]
crit rate : 30.0, crit damage : 10.3
pdamage : 93.0, pdamage_indep : 384.4
stat_main : 185.8, stat_sub : 2.0
pstat_main : 0.0, pstat_sub : 0.0
stat_main_fixed : 0.0, stat_sub_fixed : 0.0
boss_pdamage : 0.0, armor_ignore : 32.0
att : 20.0, patt : 4.0
damageFactor : 0.0
```
~같은 스킬이 직접 사용이냐 태그냐에 따라 옵션이 달라짐.~ 제가 잘못 알고 있었던 것 같습니다. 실험으로 더 확인해보겠습니다.

2. 쉐도우 레인 관련 코드 제거

3. 리미트 브레이크 지속시간 중 다른 스킬 쿨타임 감소 효과 적용되는지 확인 (엔버링크 위주로)

**Comment by cheese98** [comment]
https://github.com/Monolith11/memo/wiki/Zero-Skill-Mechanics

일본 DPM 제작자분께 문의 결과, 대부분 스킬이 현재 캐릭터의 스펙을 따르는데 일부 예외가 있다고 하네요.

그런데 이러면 구현하기 더 골치아파지겠네요.

**Comment by icepeng** [comment]
항상 알파로 적용 / 항상 베타로 적용 / 현재 캐릭터 따라감

이렇게 3가지 케이스가 있네요.

**Comment by cheese98** [comment]
일단 제로 스킬은 `AlphaState`와 `BetaState`를 더미화하고 스킬에 직접 modifier를 적용하는 방식으로 하면 될것 같긴 하네요. 문제는 5차스킬이랑 공용스킬...

**Comment by icepeng** [comment]
5차랑 공용도 add_runtime_modifier를 만들어뒀으니 별로 어려울건 없습니다.

제로 알파/베타 스킬중에도 현재 상태 따라가는게 있으니 따로 적용해줘야 하고...

그리고 어시스트는 태그 이후에 3초간 지속되는 버프를 만들고 지속시간 내에만 발동하게 하는게 맞겠네요.

**Comment by cheese98** [comment]
추가:
* 리미트 브레이크 지속시간 중 디스토션과 엔버링크 쿨타임이 빠르게 도는 효과가 제대로 작동하지 않는 것 같음
* 쉐도우 스트라이크 사용여부는 아직 미지수

**Comment by icepeng** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/pull/382
