### ISSUE TITLE
엔젤릭버스터- 어피니티 IV 데미지 증가에 관한 피드백

### ISSUE THREAD

**Issue by pentl** [oleneyl/maplestory_dpm_calc#345]
현재 어피니티 IV로 인한 데미지 30% 증가가 상시 적용으로 계산되고 있는 것으로 보입니다.

하지만 어피니티 IV의 스킬효과는 리차지가 일어날 때 50%의 확률로 데미지 30% 증가이고, 
트리니티 3연격의 딜레이인 1080ms마다 한 번씩 리차지가 일어난다고 가정했을 때 특정 시점에 어피니티 IV로 인한 데미지 증가 효과를 받고 있을 확률은 약 97%로 계산됩니다.

아무리 리차지가 자주 일어나는 event라고 해도, 50%라는 확률은 실패를 무시할 정도로 크지 않다고 봅니다. 
따라서 어피니티 IV로 인한 데미지 증가 효과를 30%보다는 29.1% 정도로 설정하는 것이 더 정확할 것 같습니다.

**Comment by icepeng** [comment]
제보 감사합니다. 계산해보고 적용하겠습니다.

**Comment by icepeng** [comment]
97%는 어떻게 계산하신 값인가요? 제가 1080ms로 놓고 계산할 때는

`1 - 0.5^(5000/1080) = 0.9491...` 이렇게 나오는데 제가 놓친 부분이 있는지 확인 부탁드립니다.

**Comment by icepeng** [comment]
3600초간 리차지 횟수 2979회

트리니티 사용주기 약 1208.46ms

특정 시점보다 5000ms 이전에 트리니티가 n회 사용되었을 확률

4회 - 86.25%
5회 - 13.75%

`1-0.5^4`, `1-0.5^5`를 확률에 따라 가중평균 하면 약 94.1797% 가동률이 나옵니다.
