### ISSUE TITLE
적 체력 상태를 참조하는 스킬의 적용

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#376]
은월 - 약점 간파
https://github.com/oleneyl/maplestory_dpm_calc/issues/162

에반 - 브레스 오브 윈드
* 브오윈 사이클로 갈시 하이퍼를 썬더 보너스 어택 -> 윈드 보너스 찬스로 바꿔야함

적 체력 100% 가정 / 최적 조건 가정 / 가동률 반영 중 택1

가동률 반영은 에반은 아예 체력 조건따라 딜사이클이 달라져서 적용하기 어렵습니다.

**Comment by cheese98** [comment]
은월은 효과를 반토막내서 적용하고 에반은 최적조건으로 가는게 좋을 것 같습니다.

체력 100% 조건 달면 호영도 첫타에 자신감을 적용시켜야 돼서...

**Comment by icepeng** [comment]
100%도 좀 이상하긴 하네요.

에반을 최적조건으로 할거면 은월도 똑같이 해야합니다.

**Comment by oleneyl** [comment]
평균으로 계산하는게 좋아보입니다.

**Comment by icepeng** [comment]
에반처럼 딜사이클이 달라지는 경우엔 어떻게 하나요?

**Comment by oleneyl** [comment]
딜 사이클이 어떻게 변경되나요?

**Comment by icepeng** [comment]
적 체력이 35%인가 45% 이하일때는 브오어 대신 브오윈을 쓰는 사이클로 변경됩니다.

체력이 일정 수치 이하일때 브오윈 데미지가 크게 증가합니다.

**Comment by cheese98** [comment]
그러면 에반은 브오어 브오윈 둘다 짜놓은다음에 표로 공개할때는 브오윈값 35% + 브오어값 65%로 하는게 어떨까요?

대신 웹사이트 대표값은 딜이 더 높은쪽인 브오윈으로 올려놓고요.

**Comment by icepeng** [comment]
조건부 dpm으로 할것
