### ISSUE TITLE
오버드라이브 패널티 관련 질문

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#38]
해적 직업들 소스 코드를 보면 generate 함수에서 리턴할 때 `Overdrive`와 `OverdrivePenalty`가 같이 등록되어 있는데 이러면 시작할 때 두개 모두 발동되는 거 아닌가요?

만약 그렇게 되고 있다면 return 쪽에서 패널티를 빼야 될 것 같습니다. (`Overdrive.onAfter`를 통해 이미 등록이 되어 있으므로)

추가로, 직업 소스 내에서 무기 순수 공격력을 확인할 수 있는지 궁금합니다. 이것도 접근이 불가능한 부분인가요...

**Comment by oleneyl** [comment]
```python
from ...kernel import core
from ...kernel.core import VSkillModifier as V
from ...kernel.core import CharacterModifier as MDF
from ...character import characterKernel as ck
from functools import partial

https://github.com/oleneyl/maplestory_dpm_calc/blob/0afe2f38a320083a79c59397c2806b9ff069f4f0/dpmModule/jobs/jobbranch/pirates.py#L1-L15

리턴을 하지 않으면 페널티가 발동이 되지 않습니다. onAfter를 통해 스킬이 발동하여도 디버프로서 작용이 안되기 때문에 리턴해야 합니다.
```python
self.OverdrivePenalty.set_disabled_and_time_left(-1)
```
구분을 추가할 필요는 있을 것 같습니다.

무기 순수 공격력이 아마 인자로 넘겨진 `character` 에 대해 `character.itemlist["weapon"] 을 통해 접근 할 수 있을겁니다.
https://github.com/oleneyl/maplestory_dpm_calc/blob/0afe2f38a320083a79c59397c2806b9ff069f4f0/dpmModule/character/characterKernel.py#L357

**Comment by cheese98** [comment]
감사합니다. 오버드라이브 함수 자체는 잘 작동하지만 직업 코드 내에서 `chtr.itemlist["weapon"]`을 불러보니 강화 후 공격력이 나오네요. 이건 나중에 생각해봐야겠습니다.

**Comment by oleneyl** [comment]
item의 옵션에 각 강화 단계별 상태를 저장하는 옵션을 넣는 것을 고려해 볼 필요가 있을 것 같네요.

**Comment by oleneyl** [comment]
+ 무기 순수 공격력이 강화 이전 값인지, 강화 이후 값인지 기억이 잘 안나네요

**Comment by cheese98** [comment]
`ItemKernel.py`에 `self.basic_att = att` 문구를 삽입한 후 `angelicbuster.py`의 오버드라이브 정의 부분 바로 앞에 `print(chtr.itemlist["weapon"].basic_att)`를 넣고 돌려봤는데 첫번째 값이 154, 두번째 값이 427이 나옵니다. 결과적으로 값이 달라집니다.

기본 공격력을 백업하려면 좀 건드릴 게 많을 것 같은데요, 차라리 `jobs/__init__.py`에 정의되어 있는 직업 이름에 대응하는 무기 이름을 받아내서 그걸로 item 패키지 내에서 찾아내는 것도 나쁘지 않을 것 같습니다.

**Comment by icepeng** [comment]
무기 공격력을 참조 가능하게 했음.
