### ISSUE TITLE
스킬별 딜레이 작성할때 클라이언트 기준인가요?

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#39]
소스 수정하다가 코드의 스킬 딜레이가 클라이언트랑 달라서 여쭤봅니다.

[공격 속도 계산 공식](https://blog.naver.com/oe135/221125580769) 에 따르면 변환 과정을 거쳐야 된다는데, 이걸 적용해서 넣어야 되나요?

**Comment by oleneyl** [comment]
예 변환된 수치로 입력해 주시면 됩니다.
(client 공속)*0.75 의 30배수 올림값
