### ISSUE TITLE
전직업 4th V 개발 현황 정리

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#394]
## 모험가

- [x] 히어로
- [x] 팔라딘
- [x] 다크나이트
- [x] 아크메이지불/독
- [x] 아크메이지썬/콜
- [x] 비숍
- [x] 보우마스터
- [x] 신궁
- [x] 패스파인더
- [x] 나이트로드
- [x] 섀도어
- [x] 듀얼블레이드
- [x] 바이퍼
- [x] 캡틴
- [x] 캐논슈터

## 시그너스

- [x] 소울마스터
- [x] 플레임위자드
- [x] 윈드브레이커
- [x] 나이트워커
- [x] 스트라이커
- [x] 미하일

## 레지스탕스+데몬

- [x] 블래스터
- [x] 배틀메이지
- [x] 와일드헌터
- [x] 메카닉
- [x] 데몬슬레이어

## 영웅

- [x] 아란
- [x] 에반
- [x] 루미너스
- [x] 메르세데스
- [x] 팬텀
- [x] 은월

## 노바

- [x] 카이저
- [x] 카데나
- [x] 엔젤릭버스터

## 레프

- [x] 아델
- [x] 일리움
- [x] 아크

## 혼밥

- [x] 제로
- [x] 키네시스
- [ ] 호영 (미구현)

**Comment by cheese98** [comment]
테섭에서 변경사항이 있는 직업
* 비숍
* 보우마스터
* 신궁
* 나이트로드
* 나이트워커
* 루미너스
* 데몬슬레이어
* 블래스터
* 배틀메이지
* 아크

**Comment by cheese98** [comment]
* 팔라딘: 마이티 묠니르
  * 데미지: 225+9n% * 6
  * 충격파: 250+10n% * 9
* 다크나이트: 다크니스 오라
  * 일정 간격 데미지: 400+16n% * 5
  * 종료: 650+25n% * 13, 생명력 3당 1회씩 추가발동
* 아크메이지썬/콜: 주피터 썬더
  * 일정 간격 데미지: 300+12n% * 5
    * 최대 감전 횟수 30회, 감전 5회마다 빙결 중첩 감소
  * 전이: 200+8n% (단일대상에는 미적용일듯)
* 패스파인더: 렐릭 언바운드
  * 렐릭 게이지 350 소비
  * 디스차지: 일정 간격마다 500+20n%
  * 블래스트: 일정 간격마다 625+25n% * 8 * 4 (발사횟수 최대 4회)
  * 트랜지션: 일정 간격마다 700+28n% * 5, 최대 3개 설치
* 섀도어: 멸귀참영진
  * 협력자: 425+17n% * 8 (12회)
  * 우두머리: 625+25n% * 15 * 4
* 바이퍼: 하울링 피스트
  * 에너지 충전: 425+17n% * 6
  * 막타: 525+21n% * 10 * 14
* 캡틴: 데스 트리거
  * 데미지: 575+23n% * 11
  * 스킬 매커니즘에 대해 자세히 확인 필요
* 캐논슈터: 풀 메이커
  * 데미지: 700+28n% * 3 (최대 20회 발생)
  * 보급품: 20초간 데미지 15+(n//2)% 증가, 최대 2개
* 플레임위자드: 샐리맨더 미스칩
  * 데미지: 150+6n% * 7
  * 샐리맨더의 공격이 적중할 때마다 불씨를 얻고 불씨 1개마다 샐리맨더 공격의 최종 데미지 1% 증가, 불씨는 최대 15+n개까지 획득 가능
  * 샐리맨더 소멸 시 30초 동안 마력 15 증가, 불씨 1개마다 마력 2 추가 증가
* 윈드브레이커: 볼텍스 스피어
  * 데미지: 400+16n% * 6 (최대 20회까지만 적용)
* 스트라이커: 창뇌연격
  * 60초 동안 최대 12번의 연계 공격 가능
  * 연계 공격 : 최대 4명의 적을 375+15n%의 데미지로 5번 공격, 적중 시 최대 3명의 적을 500+20n%의 데미지로 4번 공격하는 번개 최대 3개 발동, 번개는 서로 다른 곳에 발동
  * 마지막 연계는 최대 7명의 적을 600+24n%의 데미지로 7번 공격, 적중 시 최대 8명의 적을 725+29n%의 데미지로 6번 공격하는 거대 번개 발동
* 미하일: 라이트 오브 커리지
  * 데미지 증가량: 10+n//2% (나무위키에 틀리게 나와있음)
  * 빛의 검: 325+13n% * 5
    * 적중한 상대에게 용기의 빛 디버프를 남기고 최대 6회까지 중첩
  * 용기의 빛
    * 추가 타격: 175+7n% * 2
    * 종료: 375+15n% * 10, 용기의 빛 중첩에 따라 개수 증가
* 와일드헌터: 와일드 발칸 Type X
  * 8.5초 동안 475+19n% * 4회의 데미지로 공격
* 아란: 블리자드 템페스트
  * 데미지: 800+32n% * 8
  * 다이어 울프의 저주: 475+19n% * 4
    * 최대 6회까지 중첩가능하며 타수 1씩 증가
* 에반: 스파이럴 오브 마나
  * 데미지: 235+n% * 6
  * 패시브: 마력 5+n 증가
* 메르세데스: 로얄 나이츠
  * 데미지: 325+13n% * 4
* 팬텀: 리프트 브레이크
  * 제자리 공격: 400+16n% * 7
* 카이저: 드래곤 블레이즈
  * 데미지: 250+10n% * 6
  * 불의 기운: 375+15n% * 5
  * 화염구: 350+14n% * 3 * 6
* 카데나: 웨폰 버라이어티 피날레
  * 데미지: 250+10n% * 7 * 4
* 일리움: 크리스탈 게이트
  * 지속시간: 130+n초
  * 마력 5+2n 증가
  * 폭격: 450+18n% * 5
  * 보스전에서 사용하기 힘들다는 코멘트가 있음
* 제로: 에고 웨폰
  * 각각 독립적인 쿨타임을 가짐
  * 라즐리: 175+7n% * 6 * 9, 타겟 1마리
  * 라피스: 175+7n% * 9 * 2 * 3, 타겟 4마리
* 키네시스
  * 데미지: 400+16n% * 6
  * 일정 시간 공격: 500+20n%
    * 현재까지 당겨진 적의 수에 비례해 공격 간격 최대 3배까지 감소 및 공격의 최종 데미지 40%까지 증가
  * 폭발: 600+24n% * 15
