### ISSUE TITLE
1.2.332 패치 공통 변경사항

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#40]
* [상태이상 적에게 추가 데미지 어빌리티] : 특정 상태이상이 아닌 모든 상태이상에 적용되게 됩니다.
  * 상태이상이 있는 직업들이 아랫줄에 넣을 수 있습니다. (유니크 8퍼, 에픽 5퍼)
* [하이퍼 스탯 DF/TF] : 싸이킥 포인트도 증가시키게 되며 1레벨당 1칸이 증가합니다.
  * 키네시스 하이퍼스탯 찍을때 반영해야 합니다. 데슬 8렙, 제로 5렙, 키네 10렙.
* [가이디드 애로우] : 매달린 상태에서는 사용할 수 없게 되고 매달린 후 일정 시간 공격하지 않으면 마법 화살이 공격을 하지 않게 됩니다. ‘전투 상태일 때 공격한다’는 스킬 설명이 현재 로직과 동일하게 캐릭터가 ‘공격할 때 공격한다’는 내용으로 변경됩니다.
  * 현재 소환수 코드로 작성되어 있는데 오라웨폰처럼 공격시 반응하는 걸로 바꿔야 할 것 같습니다. 90번 타격시 사라지는 건 어떻게 구현해야 될까요...

**Comment by oleneyl** [comment]
상태이상 부분은 어빌리티에 추가하도록 해보겠습니다.
하이퍼스탯 부분도 추가할 수 있을 것 같습니다.
가이디드의 경우에는 공격스킬 시전 이후에 하나씩 발동되게 하는 방식으로 적용할 수 있을 것 같습니다.

**Comment by icepeng** [comment]
상추뎀 -> 모법링크를 필수로 놓고, #281 에서 보공 형태로 사용되게 해뒀습니다.
하이퍼 스탯 -> 아직 안되었습니다
가이디드 애로우 -> 오라 웨폰이랑은 좀 다른게, 공격 스킬 사용시마다 반응하는게 아니라 공격을 한번 해서 타겟을 잡아주면 주기적으로 공격하기 시작하는것에 가깝습니다. 그대로 소환수로 둬도 상관없고, 90회 타수가 나오도록 지속시간과 공격주기를 바꿔두었습니다.

**Comment by icepeng** [comment]
#290 에서 마저 관리하겠습니다.
