### ISSUE TITLE
Callback 사용하기

### ISSUE THREAD

**Issue by oleneyl** [oleneyl/maplestory_dpm_calc#400]
- ResultObject에 콜백 인자를 함께 리턴하고, 이를 Scheduler에 저장하여 Scheduler가 이를 바탕으로 다음 task를 체크하도록 함

**Comment by oleneyl** [comment]
![image](https://user-images.githubusercontent.com/39217532/93009942-89f13100-f5c1-11ea-8ec5-e80591814865.png)
에서 
![image](https://user-images.githubusercontent.com/39217532/93009963-de94ac00-f5c1-11ea-9d5c-44f08512a71b.png)
로 변경할 예정

**Comment by cheese98** [comment]
* 메카닉: 메카 캐리어
* 키네시스: 로 오브 그라비티
* 제로: 리미트 브레이크(막타)

**Comment by icepeng** [comment]
메카 캐리어, 로 오브 그라비티는 지금 있는것들로도 구현이 어렵지 않습니다.

리밋브, 싸이킥 토네이도 등등 막타 터트리는게 존재하는 스킬들

에반 융합스킬, 돌아와! 알맞은 시간에 사용되도록 하는것
