### ISSUE TITLE
패스파인더의 트리플 임팩트 딜 점유율에 대해..

### ISSUE THREAD

**Issue by YuMaroong** [oleneyl/maplestory_dpm_calc#404]
안녕하세요! 이번 DPM을 만들어 주셔서 정말 감사합니다.

다름이 아니라 인벤 게시글에

9/13 17:19 수정)

렐릭 언바운드에 에인션트 아처리를 적용한 버전으로 새로 업로드 했습니다.

별개로, 지금 트리플 임팩트 점유율이 15%가 나오고 있는데 정상적인 현상인지 피드백 부탁드립니다.

렐릭 차지 II 쿨감에 의해 평균 3.051초마다 트리플 임팩트가 시전되고 있는데, 가능한 딜사이클인지 검증이 필요합니다.

라고 적어놓으셔서 문의 드립니다.

현재 패스파인더의 딜 사이클은 블디매크로 연계후 엣지오브레조넌스 트리플임팩트를 연계로 쓰고 있습니다.

여기서 트리플임팩트는 엣지오브 레조넌스와 쿨타임을 맞추어 같이 사용합니다.

저도 오늘 패파의 딜 사이클을 연구하면서 이렇게 하면 훨씬 더 많이 딜이 올라가겠는데? 하면서 하루종일 딜 사이클을 연구하고 재현해보려고 해본 바 있습니다. http://www.inven.co.kr/board/maple/2296/61864?my=post

하지만 엣지오브레조넌스와 트리플임팩트를 따로 쓰는 경우는 오히려 저희에게는 딜 하락을 유발하였습니다.

그 이유로는 

블디 매크로중 엣지 오브 레조넌스를 쓰면 블디 매크로가 끊기며 인간의 손으로 아무리 빠르게 다시 누른다 하여도 딜레이가 있다.  이로 인해 쿨타임 감소 능력을 못받으며 오히려 이게 스노우볼링이 굴러가 딜 하락을 유발한다.

입니다.

실질적으로 이론에 가까운 딜을 넣어보고 싶어 연구해본 바이지만 터무니없는, 오히려 기계가 아니라면 넣을 수 없는 딜 사이클이 되어버려서 구현할 수 없는 딜 사이클이라 판명하게 되었습니다.

실제로 저도 계산해 본 결과 , 엣지 오브 레조넌스와 트리플 임팩트를 따로 쓰게 된다면 트리플 임팩트의 점유율이 15% 가량으로 증가하였습니다.

하지만 실제로 사용하는 딜 사이클인 트리플임팩트를 엣지 오브 레조넌스의 쿨타임에 맞추어 동시에 쓰는 방법은 트리플 임팩트의 점유율이 12~13%가량으로 하락하므로 이를 고려해주셔서 DPM에 적용시켜주시면 감사하겠습니다.

긴 글 읽어주셔서 감사합니다. 언제나 응원하고 있습니다!! 힘내세요!!

**Comment by YuMaroong** [comment]
앗 그리고 제 딜 사이클은 에인션트 아스트라는 쓰지 않는 딜 사이클이라 아스트라를 쓰는 분들에게는 더 하락할 수 있습니다.

**Comment by icepeng** [comment]
상세한 피드백 감사합니다. 정확히 제가 필요했던 정보입니다.

저 또한 임팩을 레조에 맞췄을떄 12%대로 나오는 것을 확인했었습니다. 계산 결과가 동일하니 다행입니다.

딜사이클은 아스트라를 어떻게 사용해도 딜이 더 낮게 나와서 배제했습니다. 게이지를 빼는 용으로 쓰려고 해도, 이미 에인션트 가이던스의 가동률이 나쁘지 않아서 굳이 쓸 필요가 없었습니다.

근데 제가 해보기로는 엣오레가 블-디 매크로 도중에 사용이 되어서 블래 이펙트가 보이자마자 엣오레 사용 -> 다시 블디 매크로 꾹 누르는 식으로 해보니 딜레이 손해없이 연결이 가능했습니다.

블+디가 약 480~500ms인데 이 안에 눌렀다 떼는건 블래스터의 매그팡 조건에 비교하면 가능한 영역이라고 판단됩니다.

그래서 쿨마다 쓸때 딜 하락되는 이유는 트리플 임팩트쪽에 뭔가 더 있을것이라고 판단되어 추가적인 조사가 필요합니다.

검증하고 싶은 부분이 몇가지 더 남아있는데, 혹시 추가로 질문드려도 괜찮을까요?

**Comment by icepeng** [comment]
게시물 읽어보았는데, 서버렉이 없어도 블디는 1초에 2.0833....번이 한계입니다.

그리고 트리플 임팩트는 쿨타임이 점프->발사 이후부터 돌기 시작해서 실질 쿨타임은 약 540ms가 더 추가됩니다.

제 추측으로는 트리플 임팩트가 클라상 딜레이보다 실제 플레이에서 더 많은 딜레이를 잡아먹을 수 있다는 것입니다.

블디 매크로->트리플 임팩트를 누를 때 최대 속도로 하면 디스차지 이후 270ms만에 사용가능하지만, 약간 늦어질 수 있습니다.

또한, 트리플 임팩트 발사 직후 블디 매크로를 다시 사용하는 시점의 문제도 있습니다. 트리플 임팩트를 쓸때 점프하자마자 블디 매크로를 꾹 누르고 있으면 거의 임팩 발사하자마자 블디가 바로 나가는 것을 확인할 수 있습니다. 대부분의 유저들은 이 타이밍이 약간 늦어질 것으로 생각됩니다.

한번 이 부분들을 신경써서 쿨마다 쓰는 사이클로 전투분석을 해보면 좋을것 같습니다.

**Comment by YuMaroong** [comment]
계속 쿨을 같이 돌리는 형식으로 해보는데 블디매크로 이후 레조넌스 쿨타임에 맞춘 트임레조에 딜이 현저히 밀리는 현상이 나옵니다.

전투분석을 통해 분석을 해본 결과 제작자님 말대로 트리플 임팩트에 문제가 있었다는 것을 알 수 있었습니다. 
블디매크로 후 트리플 임팩트를 쓰면 블디 다 나가고 연계가 되는 것이 아닌 블래스트 후 트리플 임팩트가 써져 디스차지가 씹히는 경우를 볼 수 있습니다. 
또한 후딜레이가 상당히 길어 쿨타임을 돌리기에도 더욱 어려워 엣지 오브 레조넌스의 횟수가 차이가 계속 납니다.

http://www.inven.co.kr/board/maple/2296/61997

이것은 제 전투분석 측정이며 

http://www.inven.co.kr/board/maple/2296/61993

어떤 유저분이 분석해주신 글입니다. 댓글을 봐주시면 감사하겠습니다.

**Comment by icepeng** [comment]
분석한 글을 보니 블디 매크로 딜레이가 420ms로 1초에 2.38회까지 될 수 있는게 주요 원인으로 생각됩니다. 480ms로 1초에 2.0833....번이 한계라고 단정지어 생각했는데 패치로 60ms 후딜이 제거된것을 파악하지 못했습니다.

http://www.inven.co.kr/board/maple/2296/51645

이쪽 실험에서도 추가로 확인됩니다.

이러면 블디 대비 트리플의 상대적인 딜 차이가 적으므로, 트리플로 인해 지연되는 약간의 시간을 감수하면서까지 쿨마다 돌려줄 이유는 없어보입니다.

해당 부분 반영한 결과 트리플/레조 쿨마다 사용 >= 트리플/레조 함께 사용 > 레조만사용 순으로 결과가 나왔습니다. 이론치와 다르게 쿨마다 사용이 미세하게 더 높게 나오는데, 현재 쿨감 로직상 아주 약간의 오차가 있습니다. 오차를 수정하는 패치까지 적용된 후에 다시 비교해보겠습니다.

어쨌거나, 실제 게임에서는 항상 최소 시간으로 캔슬하며 트리플을 사용할 수 없다는 점을 반영해 트리플/레조 함께 사용하는 딜사이클로 변경하겠습니다.
