### ISSUE TITLE
오버로드 마나 정리

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#405]
설치기와 소환수에는 적용되지 않습니다.

* 비숍
  * 모든 5차 스킬에 발동
  * 바하뮤트 미적용
* 키네시스
  * 로 오브 그라비티: 아예 미적용
  * 트레인, BPM, 드레인 적용 (시전시에 HP 감소)
  * 나머지는 모두 적용되나 실제 측정값으로 재확인 필요

**Comment by icepeng** [comment]
설치기나 소환수임에도 적용되는 예시가 있긴 합니다. 일리움 리요/데우스라던가...

**Comment by cheese98** [comment]
Monolith 시트 기반 자료

* 불독
페럴라이즈로 추정 (ナムネスバインド) & 도트
이그나이트
미스트 이럽션
플레임 헤이즈 & 도트
포이즌 미스트 & 도트
메테오 + 파이널 어택
이프리트 & 도트
파이어 오라
메기도 플레임 & 도트
도트 퍼니셔 & 도트
포이즌 노바 & 도트
퓨리 오브 이프리트
포이즌 체인

**Comment by icepeng** [comment]
남 네스 바인딩으로 번역되는게 패럴라이즈가 맞습니다.
