### ISSUE TITLE
호영 진행도

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#407]
from #18 ~ #398
- [x] 스킬 등록
- [x] 스킬 내부 구조
  * 허/실 스킬에 `create_auxilary_attack` 적용 가능할지 확인필요
- [x] 딜사이클
- [x] 게이지 시스템
- [x] 최적화
- [x] jobs 및 item에 호영 관련 정보 등록

**Comment by cheese98** [comment]
https://www.youtube.com/watch?v=9FPkf4_jE9M

환영 분신부 - 호접지몽 - 아니마 - 선단 - 산령소환 - 흡성와류 - 분신난무 - 괴력난신 - 미생강변 - 레투다 - 천지인 환영 - 스인미 - 미생강변

토파류 계속 사용
금고봉, 지진쇄 쿨돌때마다 사용

**Comment by cheese98** [comment]
참고자료 #174

**Comment by icepeng** [comment]
#477
