### ISSUE TITLE
루미너스 피드백

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#409]
- [x] 이퀄이 종료된 상태일지라도 빛둠세 스택이 11스택인 경우 앱킬을 한번 더 사용해서 빛둠세 초기화시키는 로직이 필요함
- [x] 초고스펙 구간에서 타수 늘려주는 용도로 모닝 스타폴을 딜사이클에 섞으면 벽썬브처럼 풀힛이 가능할 때 조건부로 딜이 올라갈 여지가 있다고 듣긴 했는데 하도 버려진 스킬이다보니 스킬 자체가 코드에 안들어가있음
- [x] 이퀄상태일지라도 빛둠세가 11스택이고 쿨타임이 5초 이하로 남은 경우엔 라리플 or 아포를 쓰는 쪽 딜량이 높은데 이거 역시 코드로 구현되어있지 않음 이퀄상태에서 라리플 or 아포 자체를 아예 봉인해두는 식으로 코드가 짜인듯

https://gall.dcinside.com/board/view/?id=maplestory&no=11988108

**Comment by icepeng** [comment]
1. 이퀄 빨리 땡겨오는게 나을수 있어서 비교해보고 적용
2. 허수아비 맵 중앙을 가정할거라 필요없는듯 함
3. 빛둠세 퍼뎀과 (앱킬-아포) 퍼뎀을 비교해서 x초 이하부터 앱킬을 멈출지 생각하고 적용하면 될듯함

앱킬/아포/라리플을 Constraint가 아닌 Rule단에서 사용 여부를 정하는게 좋아보임

**Comment by cheese98** [comment]
추가내용: 1번은 이퀄 더 빨리쓰는게 아마 어떤 버프도 없을때는 확실히 맞는 말이긴 할텐데 엔버링크, 메용2같은 스킬들이 남아있을 경우 무조건 극딜버프에 맞춰서 빛둠세 한 번이라도 빨리 박는게 이득이 되겠죠
이것도 극딜버프가 존재하는 경우에 한정된 조건부 비교라서 꽤나 머리아프겠네요

**Comment by icepeng** [comment]
Ruleset쪽을 한번 뜯어고쳐야 이런저런 요구사항이 잘 충족될거 같습니다... 지금으로썬 복잡한 딜사이클 설계가 영 어렵네요.

**Comment by Nougaga** [comment]
2. 모닝 스타폴 허수아비
마을 중앙 허수아비 기준 공격 횟수 11~12회 (틱11 or 틱11+폭1 or 틱12)
- 딜레이 660ms, 어둠게이지 1회 당 10
- 리버레이션 오브 반응 X

일단 참고용으로 남겨놓습니다

**Comment by icepeng** [comment]
리버레이션 오브 추가 및 밸패 후로는 앱킬을 비이퀄때도 그냥 쿨마다 박는게 낫네요. 이퀄 진입 텀이 좀 길어져도 마력으로 상쇄할 수 있어서 그런건지...? 로그 뽑아보니 이퀄 쿨마다 박으면 리버레이션 마력이 4/4도 간혹 나오네요. 봉인하면 3/4까지밖에 안나오고요.

아마도 밸패때 리버레이션 기본 퍼뎀이 줄어들어 마력 스택당 증가폭이 커지고, 20회 타격이 보장된 것 때문에 이제는 앱킬을 쿨마다 박으면서 딜하는게 좋아진거 같습니다.

앱킬 쿨마다 쓰면서 얻는 이득이 원래는 빛둠세 하나뿐이였다면, 이제는 이퀄 텀이 길어지는것을 리버레이션이 상쇄해주네요.

**Comment by icepeng** [comment]
그리고 빛둠세 11스택 & 쿨타임 5초 이하인 상황 자체가 dpm상에선 아예 나오질 않습니다. 모든 딜을 다 끝없이 집어넣다 보니 16초 이하로 내려가기 전에 무조건 초기화됩니다.
