### ISSUE TITLE
윈브 신5차 / 게일 피드백

### ISSUE THREAD

**Issue by kowi10** [oleneyl/maplestory_dpm_calc#412]
http://www.inven.co.kr/board/maple/2296/62215

위의 링크에서 실험한 것을 보면 볼텍스스피어와 1스택 게일의 최적 히트수는 17히트 / 58히트로 보입니다(1스택 게일 히트수 2 증가)

다만 저 위치에서 몇 픽셀만 벗어나도 볼텍스스피어의 히트수가 16으로 떨어지거나 1스택게일의 히트수가 57 혹은 그 이하로 떨어집니다.(심지어 같은 위치에서 쏴도 허수아비의 좌우 흔들림, 게일 ai 반응속도 운에 따라 가끔씩 히트수가 차이남)
더욱 정확한 조건을 확인하려면 꽤나 많은 횟수의 실험을 해봐야 할 거 같습니다

**Comment by icepeng** [comment]
해당 거리에서 천노가 닿나요? 천노가 닿는 거리가 아니라면 전후로 윈드워크 딜레이가 들어가야 하기 때문에 확인이 필요합니다.

**Comment by kowi10** [comment]
천노 닿습니다. 게일 56히트 나오는 좀 더 먼 거리에서도 천노는 닿았습니다

**Comment by icepeng** [comment]
그리고 허수아비가 빨아먹는 무릉 포인트 관해서는, 저는 몹 크기가 많이 중요한 테스트가 아닌 경우 에르다 스펙트럼에서 가운데 응집기를 치면서 확인했습니다. 아마 가로폭도 허수아비랑 비슷할거 같긴 한데...

**Comment by kowi10** [comment]
몹 크기가 살짝만 변해도 히트수가 달라질 것으로 보여 진퉁 허수아비를 써야할 것으로 예상합니다만
조금 있다 스펙트럼 들어가서 측정 한번 해보겠습니다

**Comment by kowi10** [comment]
http://www.inven.co.kr/board/maple/2299/5212127

응집기 확인결과입니다.

**Comment by icepeng** [comment]
응집기 히트박스가 약간 더 넓은거같네요.

허수아비를 기준으로 같은 위치에서 여러번 시도했을때 게일 타수가 약 90%이상 확률로 58히트가 뽑힌다면 58히트로 적용하는게 맞겠습니다.

**Comment by kowi10** [comment]
http://www.inven.co.kr/board/maple/2299/5212598

일단 허수아비 2개 사용해서 36회 실험 완료했습니다
게일은 크게 문제를 일으키지 않고 오히려 볼텍스 히트수가 낮아지는 경우가 많았습니다.
위치를 몇 픽셀 조금 더 잘 잡으면 히트수가 줄어드는 경우가 줄어들 것 같지만 인간의 영역이 아닌것 같습니다

**Comment by icepeng** [comment]
이정도면 17/58을 기준으로 해도 된다고 생각합니다.

실험 감사합니다.

**Comment by kowi10** [comment]
항상 dpm표 잘 보고 있습니다
dpm 작업 잘 마무리 되길 바랍니다
