### ISSUE TITLE
매직 서킷 풀드라이브

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#414]
일리움, 아크, 아델이 사용중인데 모두가 서로 다른 방식으로 구현되어 있음
* 일리움: SummonSkill (독립 코드)
* 아크: DamageSkill (독립 코드)
* 아델: DamageSkill (공용 코드)

통합 코드를 일리움과 아크도 사용할 수 있도록 수정 필요

**Comment by Nougaga** [comment]
매직 서킷 풀드라이브(마력 폭풍)
- 발동 조건: 소환 스킬을 제외한 모든 공격 적중 시
ex)
- atom: 다가오는 죽음, 오더, 인피니트 - 터짐
- tile: 황홀한 구속, 어비스 스펠 - 터짐
- summon: 스인미 다리딜, 테리토리, 소울스킬 - 안터짐
- 게더링, 블로썸, 루인, 리스토어, 스톰, ... - 터짐
