### ISSUE TITLE
kinesis.py 소소한 수정안

### ISSUE THREAD

**Issue by Gwang-jun** [oleneyl/maplestory_dpm_calc#43]
먼저 그냥 텍스트로 적어드려 죄송합니다...

1) 우선 텔레키네시스가 최종적으론 구현이 안 되어있는 것 같습니다. 싸이킥 그랩2, 싸이킥 그라운드2(공격), 싸이코 브레이크(공격), 에버싸이킥(최종), 싸이킥 토네이도에는 텔레키네시스가 사출되는데 그런 비슷한 코드가 없는 것 같네요. 대충 은월 코드를 둘러봤는데 FoxSoul이 BasicAttack이라고 정의한 기본 딜사이클에서 onAfter 형식으로 자동 사출되도록 한 것 같습니다. (대신 의문은, 여우령 사출 확률은 어떻게 구현되어 있는건지 헷갈리네요) 이것처럼 키네시스도 적용 가능한지 궁금합니다.

2) 그리고 얼티밋 트레인이 구현이 안 되어있는 것 같습니다. 많은 키네시스 유저들은 싸이킥 오버 때 pp를 덜어내기 위해서라도 트레인을 사용하는 편입니다. 실전 딜사이클에 종종 포함되고 거론되는 만큼, 구현이 필요하다고 생각합니다.

3) 그리고 싸이킥 오버 사용시 pp 소모량 변화는 x -> [(x+1)/2] (소숫점 올림)이 아니라 x -> [x/2] (소숫점 내림)입니다. 따라서

L136 뒤: 싸이킥 오버시 3 소모함을 추가 (싸이킥 오버시 메테리얼 pp소모 정보가 빠짐 -> 맥뎀에 막히지 않는 스펙에서 딜사이클이 샷 반복이 아닌 메테리얼 반복으로 수정이 될 가능성이 큼)
L148: 3 -> 2 소모
L156: 8 -> 7 소모
L162: 오타 존재. UltimateMovingMatter -> UltimatePsychicBullet
그리고 불릿은 3 소모 및 보스 적중시 1 충전이므로, 간단하게
L163: 3 -> 2 소모
L164: 싸이킥 오버시 [3/2] = 1 소모 및 보스 적중시 1 충전이므로 0 소모 (다만, 싸이킥 오버시에는 pp가 남아돌아 그만큼 비워내는게 중요하므로 예상컨대 불릿은 사용 우선순위에서 밀리리라고 봅니다.)
로 바꾸면 되지 않을까 싶습니다

4) 그리고 이건 pp 최대치 문제인데, 하이퍼스탯에서 pp 최대치 증가를 선택하는 경우 당연히 그로인한 다른 스탯 손실이 있으므로 정확히 어떤 결과가 도출될 지는 잘 모르겠습니다. 다만 중자본 이상의 키네시스 유저들은 대부분 pp 최대치를 10을 늘리는 것을 선택하기 때문에 그에 맞춰서 키네시스 기본 스탯을 좀 줄이신다는 가정 하에,
L151: 30 -> 40 증가 (에버싸이킥)

5) 다만 에버싸이킥은 약간 기술적인 문제가 있는데, 에버싸이킥 사용 후 바로 다른 스킬들을 사용하려면 pp 2를 소모하여 싸이킥 무브(Kinetic Jaunt)를 시전해서 에버싸이킥 모션을 캔슬해야 합니다. 싸이킥 무브가 공격/버프류 스킬이 아니므로 코드에 포함이 되어있지 않은데, 가장 간단한 해결방안은 다음과 같아보입니다.
어차피 에버싸이킥은 pp를 최대로 충전시켜주므로, 모든 키네시스 유저들은 에버사이킥 이후 곧바로 싸이킥 무브를 사용(다만 키다운은 하지않고 바로 취소)합니다. 따라서 에버사이킥 자체 딜레이를 유저들이 평균적으로 싸이킥 무브를 사용하고 취소하는 딜레이(얼마인지는 측정이 필요합니다.)만큼 더 늘려도 무방하다고 볼 수 있습니다. (다만 이 경우 싸이킥 무브 사용에 들어가는 pp를 생각하면 앞서 제시한 L151에서 30 -> 38 증가로 바꾸는게 가장 직관적이라고 봅니다.)

6) L168 에서는 급한대로 상수인 10 증가로 적으셨습니다. (스킬 로직대로 구현이 애매한 것은 동의합니다.) 만약 이런 상수를 그대로 도입할 것이라면 대부분의 키네시스 유저는 적어도 bpm이 꺼지지 않도록 조절하므로 pp가 2-10일 때 차징을 사용하게 됩니다. 이는 pp 최대치 40 기준 19-15의 증가를 가져오는데 대략 이 정도 범위의 숫자로 변경하는 것이 크게 무리는 없다고 생각합니다.

**Comment by oleneyl** [comment]
- 안녕하세요. 키네시스 관련 코드에 관해 피드백 주셔서 감사합니다. 말씀해 주신 사항에 대해 답변드립니다.

- 텔레키네시스는 구현이 안되어 있는것을 확인했습니다. 빠르게 commit하도록 하겠습니다.
- 얼티메이트-트레인은 미구현상태입니다. 트레인을 사용하는 경우의 수가 어떠한 경우인지 보다 자세히 알 수 있을까요?
- 말씀해주신 사항은 반영되어 있는 상황입니다. 현재 포인트 소모 체크 로직이
  - 먼저 소비량을 소모하고
  - 싸이킥 오버가 있을 경우 절반을 되돌려 받는 구조
  - 이기 때문에 올림값이 반영되어 있는 사항이 맞습니다. 불릿의 경우 불릿-블랙홀에서 pp가 1 추가로 수급되므로 이 역시 맞습니다.

- 에버 사이킥의 경우 우선적으로 40포인트로 반영해두도록 하였습니다.
- 에버 사이킥 캔슬의 경우, 최종타만 반영되는지, 캔슬시에도 16타+최종타가 전부 반영되는지 궁금합니다. 말씀해주신 부분의 반영은 어렵지 않습니다.
- 말씀주신 부분을 반영하여 17포인트로 설정하였습니다.

- 종합하면, 얼티메이트-트레인의 사용 환경, 그리고 에버 사이킥 캔슬시에 타수에 대해 말씀해 주시면 보다 정확히 구현할 수 있을 것 같습니다. 감사합니다.

**Comment by oleneyl** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/blob/c1f3a7692328cc428f458889deebb23ed81ec9dd/dpmModule/jobs/kinesis.py#L121-L129

**Comment by Gwang-jun** [comment]
에버싸이킥은 16타+최종타로 연결되는 데미지와 키네시스의 강제 공중부양으로 이루어져 있습니다. 싸이킥무브는 키네시스의 공중부양 모션만 캔슬하는 것이므로 16타+최종타가 전부 반영됩니다. 대신 그 캔슬에 사용되는 시간이 얼마인지 ms단위로 정확히는 모르겠습니다.. 1000ms 미만이라고는 생각됩니다.

얼티밋 트레인은 1. 평딜사이클에선 pp소모가 굉장히 많은 편인데에 비해 데미지 기댓값이 크게 높은 편이 아니라 사용하지 않는 유저들이 많은데 반해 2. 싸이킥오버로 시작하는 극딜사이클에선 pp소모가 현저히 줄어들기 때문에 사용하는 유저들이 많습니다. 정확히 이게 얼마나 샷이나 메테리얼에 비해 이점이 있는지는 모르겠습니다.(결과가 말해주겠죠?) 그래도 예상하자면 실전에 비추어봤을때 말뚝딜에 사용하지 않는 불릿도 코드 내에 딜사이클에 포함된 만큼 트레인도 일단 풀힛기준 데미지로 포함시키면 변화가 있을거라 생각합니다.

싸이킥오버가 사용후 돌려받는 구조네요 다시봤습니다 감사합니다

**Comment by oleneyl** [comment]
5 : L162는 오타가 맞습니다. 수정 예정입니다.
나머지는 집에서 다시 확인하겠습니다.

**Comment by cheese98** [comment]
6번은 제가 작성한 부분인데요, 작성할때 조건을 잘못 잡았던 것 같습니다. 최대의 딜을 넣는 상황이라는 걸 확률적 요소에까지 적용해버렸네요. 4가지 스킬들이 순서대로 발동하는 걸로 간주하고 딜레이를 4배로 바꾸면 될 것 같습니다. + 현재 이계 여신의 축복을 사용하고 있는 직업은 없습니다.

**Comment by oleneyl** [comment]
1 : 반영했습니다.
2. 트레인 사용시 -0.2% 정도 피해량이 감소하여 딜사이클에는 미포함시키되 코드 상에는 반영하였습니다.
4. 추가하였습니다.

**Comment by Gwang-jun** [comment]
혹시 싸이킥 그랩과 샷의 딜레이 로직이 정확한지 궁금합니다.

정확한 명칭을 사용하자면, 키네시스가 물체(레벨 범위 내의 잡몹이 있을 경우 잡몹)를 들어올리는 모션이 싸이킥 '그랩'이고, 이는 데미지를 동반하지 않으나 주력기 중 두 가지를 사용하기 위해 반드시 선행되는 행동입니다. 이후 가능해지는 키네시스의 주력기는 다음과 같습니다.

1) 싸이킥 '스매싱'을 사용하여 평딜. 한 번의 '그랩'으로는 최대 5회의 '스매싱'을 할 수 있으며, 마지막 5회째의 '스매싱' 이후엔 들어올려진 물체가 없는 상태가 되어 다시 '그랩'을 해야 1) 또는 2)의 행동을 취할 수 있음. 5회째 스매싱을 하기 전까지는 물체가 들어올려져 있는 상태이므로 언제든지 1) 또는 2)의 행동을 취할 수 있음.
2) 싸이킥 '샷'을 사용. 이 때 들어올린 물체를 날려보내므로, 물체를 들어올리는 '그랩'을 재사용해야 1) 또는 2)의 행동을 다시 취할 수 있음.

문득 시뮬레이션 결과에서 너무 싸이킥 샷 사용 횟수와 점유율이 높아보여 문의드립니다. 혹시 싸이킥 그랩의 딜레이가 반영이 되어있는게 맞나요?

**Comment by icepeng** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/pull/166

이쪽에 그랩 딜레이 반영하는 수정이 있습니다.
