### ISSUE TITLE
메르세데스 딜싸이클 피드백

### ISSUE THREAD

**Issue by kij0708** [oleneyl/maplestory_dpm_calc#436]
메르 딜 싸이클에서  
엘리멘탈 고스트 시 연계딜로 계산된 경우가 있습니다.
이것을
프리드6스택 무적시+ 엘리멘탈고스트시는 연계딜로 하고
일반적인 엘리멘탈 고스트시는 이슈+쿨마다엔릴스듀,스피어 정도로 수정되었으면 합니다. 
이론상이라도 프리드 무적없이 라엣, 유니콘스파이크,거스트다이브를 연계로 딜을 넣는다는것은 거이 모든 보스에서 실현가능성이 없습니다.
부탁드리겠습니다.

**Comment by icepeng** [comment]
조건별 dpm을 추가할겁니다.

**Comment by kij0708** [comment]
감사합니다. dpm표만들어주셔서 정말 감사드리고 건승하십쇼!
