### ISSUE TITLE
바이퍼 에너지 소모량 오류

### ISSUE THREAD

**Issue by ksp7331** [oleneyl/maplestory_dpm_calc#438]
https://github.com/oleneyl/maplestory_dpm_calc/blob/master/dpmModule/jobs/viper.py 파일에서 160번째 줄부터
1. 하울링 피스트는 비완충때도 에너지를 충전하지 않고 소모합니다. (1750만큼 1회 소모)
2. 서펜트 초당 에너지 소모 60입니다.

**Comment by icepeng** [comment]
에너지 충전이 아예 안되는 스킬인가요? 최초 사용시 -1750만 하면 될까요?

**Comment by ksp7331** [comment]
네 에너지 충전 아예 안되는 스킬이고 에너지가 부족하면 아예 시전도 안됩니다.

**Comment by ksp7331** [comment]
최초사용시 -1750 하면 됩니다.

**Comment by icepeng** [comment]
감사합니다. 수정하겠습니다.
