### ISSUE TITLE
아크 피드백

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#439]
- [x] 차지 스펠 엠플리피케이션은 스펠이 발동되어야 갱신됨, 레프 상태에서 쌓거나 미리 장전해두는 스케쥴링이 필요함
- [x] 영굶짐은 게이지가 부족할때 쓰면 레프로 돌아가서 죽음 사출에 실패할 가능성이 있음. 스케쥴링 필요함
- [x] 인피니티 스펠때 레프상태 악몽은 쓰지 않는게 딜이 더 높음. 인피때 새악 발동으로만 쓰는건 확인 필요.
  * 인피때 충동도 확인 필요

**Comment by Nougaga** [comment]
3번은 딜레이가 240+540이면 악몽도 손해가 아니었는데 270+540은 손해였네요..
충동은 인피 시 확실하게 손해입니다
