### ISSUE TITLE
self에 관한 질문

### ISSUE THREAD

**Issue by Gwang-Sik** [oleneyl/maplestory_dpm_calc#44]
dpmModule/kernel/core.py 에서
def __init__ 함수에서 사용하는 self는 직접 사용자가 생성한 캐릭터나 직업인가요? 

그리고 개인메일을 알 수 있을까요 DPM CALC 과 관련된 질문이 아닌 다른것에 대해 
개발자 분의 메일을 통해 여쭈어 보고싶습니다

**Comment by oleneyl** [comment]
- `__init__` 함수는 class initialization에 활용되는 함수입니다. 어떤 부분이 궁금하신 것인지 혹시 다시 한 번 말씀해 주실 수 있으실까요?
- 개인적인 사항에 관해서는 maplestats.contact@gmail.com 으로 메일 주시면 답변가능한 부분에 대해서 답변드릴 수 있습니다. 감사합니다.
