### ISSUE TITLE
은월 딜사이클 질문입니다

### ISSUE THREAD

**Issue by whguswls58** [oleneyl/maplestory_dpm_calc#441]
안녕하세요 인벤에 게시해주신 글 정말 감사합니다. 

dpm표를 보고 의문점이 들어서 질문을 남겨봅니다.

1. 은월도 2초 쿨감뚝을 쓴 기준으로 측정되었는데 
2초 쿨뚝으로 얻는 이득이 힘12% 스탯한줄보다 유의미한 딜차이가 나는지 궁금합니다.
만약 딜차이가 난다면 어떤식의 계산을 통해서 딜차이가 발생했는지도 알고 싶습니다.

2. 이번 dpm 산출표에 따르면 30분간 허수아비를 때린것으로 측정되었는데 
은월의 경우 딜사이클이 어떤식으로 측정되었는지 궁금합니다.

정령결속극대화(이하 정결극), 히어로즈 오브 오쓰, 정령집속의 쿨타임은 120초쿨타임이며,
귀문진, 파쇄연권의 경우는 쿨타임이 90초이며
분혼격참의 경우에는 사용주기가 정령집속으로 초기화를 활용한 90초인지 120초인지 궁금합니다.

또한 랑혼장막의 경우 정결극 가동률 100%를 가정하였을때 

**가동률 100%를 고려하여 최초 1번만 사용 후 랑혼장막 활용**
정결극 최초 사용 (랑혼장막) - 정결극 사용  60초 후(랑혼장막) - 정결극 사용 120초 후(랑혼장막) - 정결극 사용 180초 후(랑혼장막)
의 사이클로 랑혼장막이 가동된 것인지

**정결극 쿨타임마다 활용하여**
정결극 최초 사용 (랑혼장막) - 정결극 60초 후(랑혼장막) - 정결극 120초 후(랑혼장막) -
2번째 정결극 사용(랑혼장막) - 2번째 정결극 사용 60초 후(랑혼장막) - 2번째 정결극 사용 120초 후(랑혼장막)
의 사이클로 랑혼장막이 가동된 것인지 궁금합니다.

아래의 경우 첫 정결극에서 세번째 랑혼장막 발동 직후(정결극을 발동하고 바로 랑혼장막을 사용한다고 가정했을때 약 120초~130초 후에 세번째 랑혼장막 발동) 다시 정결극을 사용하면 랑혼장막을 바로 한번더 사용이 가능해서 랑혼장막의 가동률을 좀더 올릴 수 있습니다.

3. 허수아비의 체력의 경우 100%를 고정으로 딜을 한 것인지 궁금합니다.
은월의 경우 4차스킬의 패시브에 약점간파라는 스킬이 있습니다.
약점간파의 경우 HP 50% 이하의 대상에게 크리데미지 20% 증가효과가 있습니다.
시뮬레이터의 dpm기준이 허수아비의 체력을 100%로 고정하고 딜을 할 경우
약점간파의 효과가 적용되지 않은 상태로 측정되지 않았을까 싶습니다.

다소 두서없는 글이지만 dpm표를 만드시는데 조금이나마 도움이 되었으면 좋겠습니다

**Comment by icepeng** [comment]
쿨감뚝은 http://www.inven.co.kr/board/maple/2299/5274551 이쪽 링크를 참고해주세요.

분혼 격참은 90초마다 사용하며, 정령 집속으로 초기화 되더라도 분혼 저항이 남아있으면 사용하지 않습니다.

적 체력은 지금은 약점 간파가 적용되지 않는 높은 체력 비율을 상정했으나, 가동률을 고려한 크뎀 10%로 하는 쪽으로 바꾸는게 나을지 생각하고 있습니다.
