### ISSUE TITLE
검증을 보다 정확하게 하기 위한 방안

### ISSUE THREAD

**Issue by Rudolf35** [oleneyl/maplestory_dpm_calc#442]
기준 스펙(스탯창 상세정보)+상시 유지 스킬 기준 한줄데미지 표를 뽑으면 직접 유저가 허수아비 타격으로 교차 검증이 가능할 것 같습니다

**Comment by icepeng** [comment]
전체 로그에서 평타 스킬의 딜이 가장 낮게 찍힌 곳을 가져오면 될거 같긴 합니다.

**Comment by icepeng** [comment]
https://drive.google.com/file/d/1PkB70iJ8_cA73AIWgN181J9Yap1gGg43/view?usp=sharing

스킬당 최대 / 최소 데미지를 포함한 상세 보고서 제공하는 것으로 함.
