### ISSUE TITLE
패스파인더 블래스트 타격 몹 수 감소당 최종데미지 증가 실험을 해보았습니다.

### ISSUE THREAD

**Issue by kssko1** [oleneyl/maplestory_dpm_calc#445]
블래스트 대상수 감소당 타수 최종뎀 증가 방금 제가 실험해봤습니다.
시행회수는 10회이며 1회당 4타씩 총 40회라고 보시면 될거같습니다. 해당 값의 평균입니다.
4마리 타겟팅 : 607억/40 = 15.175
3마리 타겟팅 : 494억/30 = 16.46
2마리 타겟팅 : 353억/20 = 17.65
1마리 타겟팅 : 190억/10 = 19
복리 증가라고 보기에는 최종뎀 20%를 받는 4마리 타격과 
50%를 받는 1마리 타격에서 증가 수치가 복리라고 보기는 어려운것 같습니다.
10%씩 복리를 받는다고 가정하면, 1마리 타겟팅 배율과 4마리 타겟팅 배율을 나누면 1.61/1.21= 1.33이란 값이 나옵니다.
15.175*1.33= 20.18이며
단리라고 가정했을시 1.5/1.2=1.25
15.175*1.25= 18.2
근사치는 단리에 가까우나 현재 무기의 숙련도가 해당사항에 적용이 되어 시행횟수를 더 늘려봐야 할것같습니다.
조건 불변을 위해 모든 링크는 다 제거하고 실험하였습니다.
![1마리;](https://user-images.githubusercontent.com/62807632/93606551-35a3e200-fa03-11ea-9f03-698ba3416cc3.png)
![2마리](https://user-images.githubusercontent.com/62807632/93606552-35a3e200-fa03-11ea-92a4-a84249a1cb7e.png)
![3마리](https://user-images.githubusercontent.com/62807632/93606554-363c7880-fa03-11ea-8e61-8be224022ce8.png)
![4마리](https://user-images.githubusercontent.com/62807632/93606556-36d50f00-fa03-11ea-9276-219d1a78f3a6.png)
![5마리](https://user-images.githubusercontent.com/62807632/93606578-3b99c300-fa03-11ea-94c3-c7dc8ae22eed.png)

사진 첨부합니다.

**Comment by icepeng** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/pull/450

다른 결과들과 함께 고려해 50%로 변경했습니다. 감사합니다.
