### ISSUE TITLE
메르세데스 구현상 오류 목록입니다.

### ISSUE THREAD

**Issue by illhyhl1111** [oleneyl/maplestory_dpm_calc#446]
https://github.com/oleneyl/maplestory_dpm_calc/blob/master/dpmModule/jobs/mercedes.py

# 오류
코드상으로 확인된 오류입니다. (코드를 100% 이해한건 아니라 풀리퀘보다는 이슈로 남기겠습니다 확인해주세요)

### 1) 엘리멘탈 고스트 잔상확률 오류 
  * 코드상 잔상 발동확률이 총 210%, 속사기는 105%로 적용
https://github.com/oleneyl/maplestory_dpm_calc/blob/3b0b3d504ca3609a5b0eaf528befa1b20e1a7316/dpmModule/jobs/mercedes.py#L18
https://github.com/oleneyl/maplestory_dpm_calc/blob/3b0b3d504ca3609a5b0eaf528befa1b20e1a7316/dpmModule/jobs/mercedes.py#L23
  * 인게임상으로는 첫번째 잔상이 90% 확률로 발동되어야 2번째 잔상이 70% 확률로 발동되고, 2번째 잔상이 발동되어야 3번째 잔상이 50% 확률로 발동되는 로직
    * 연계스킬의 최종 발동확률은 0.9*(1+0.7*(1+0.5)) = 1.845 
    *  비연계스킬의 최종 발동확률은 0.45*(1+0.35*(1+0.25)) = 0.646875
  * 실험자료 - https://blog.naver.com/memo/MemologPostView.nhn?blogId=oe135&logNo=221472968709&currentPage=3

### 2) 엘리멘탈 고스트 잔상에 적용되는 파이널어택 데미지 오류
  * 코드상 파이널어택을 독립적으로 잔상에 적용된 것으로 추정됨
https://github.com/oleneyl/maplestory_dpm_calc/blob/3b0b3d504ca3609a5b0eaf528befa1b20e1a7316/dpmModule/jobs/mercedes.py#L206
    * 즉 발동확률에 잔상 최종데미지 감소량이 적용된 상태
  * 인게임상으로는 고스트 잔상으로 인해 터진 파이널 어택 데미지는 잔상 최종데미지 감소를 받지 않음
  * 실험자료 - 엘고 사용여부에 관계없이 파이널어택 데미지는 동일
![image](https://user-images.githubusercontent.com/15259969/93603551-1f942280-f9ff-11ea-85de-c2d628116275.png)
![image](https://user-images.githubusercontent.com/15259969/93603494-0ab78f00-f9ff-11ea-80c3-a323e2fc5f0c.png)

### 3) 유니콘 스파이크 5차코어 강화 계수
  * 코드상 2% 증가
https://github.com/oleneyl/maplestory_dpm_calc/blob/3b0b3d504ca3609a5b0eaf528befa1b20e1a7316/dpmModule/jobs/mercedes.py#L111
  * 인게임상으로 3% 증가
  * 실험으로 겉값인지 확인해봤고 만렙시 180% 정상적용됨
![image](https://user-images.githubusercontent.com/15259969/93603925-a648ff80-f9ff-11ea-8d1e-e724cf88f63f.png)

### 4) 연계스킬 딜레이
  * 코드 - https://github.com/oleneyl/maplestory_dpm_calc/blob/3b0b3d504ca3609a5b0eaf528befa1b20e1a7316/dpmModule/jobs/mercedes.py#L110
  * 실제 인게임상 딜레이 (영상 찍어서 딜레이 측정함)
![image](https://user-images.githubusercontent.com/15259969/93604464-5d457b00-fa00-11ea-91b8-f3eb48ac71e7.png)
    * 레전더리 스피어에 SkipActionFrame 미적용, 거스트 다이브에 공속이 미적용되는 버그 존재
  * 메르 연계는 cancelableTime이 아닌 SkipActionFrame이 적용되는 캐릭이므로 딜레이 30ms 추가가 필요없을 것으로 생각됨
    1. 레전더리 스피어: 690ms(코드) -> 660ms
    2. 라이트닝 엣지: 630ms(코드) -> 600ms
    3. 리프 토네이도: 390ms(코드) -> 360ms
    4. 거스트 다이브: 480ms(코드) -> 540ms
    5. 어드밴스드 스트라이크 듀얼샷(연계): 360ms(코드) -> 330ms

### 5) 엘고 발동 시 최적 연계사이클
  * 코드상 스듀-엔릴-스듀-유니콘-스듀-스피어-맆토-거스트 콤보 사용중
https://github.com/oleneyl/maplestory_dpm_calc/blob/3b0b3d504ca3609a5b0eaf528befa1b20e1a7316/dpmModule/jobs/mercedes.py#L177
  * 실제로 맆토를 제거한 스듀-엔릴-스듀-유니콘-스듀-스피어-거스트 콤보가 소폭 더 강함(약 1%..)
    * 한 사이클 딜레이 2.85ms로, 메르쿨감이 적용된 유니콘 쿨타임 9.5s에 연계가 7번 붙으면 쿨타임이 돌게 됨.
    * 스듀-유니콘과 같이 스킬 앞에 연계를 붙이면 뒤에 스킬(유니콘) 쿨타임도 같이 1초 줄어드는 로직이 실제 적용중
       * 현재 구현 상 유니콘, 스피어, 엔릴은 항상 연계로 사용하므로 쿨타임 입력을 처음부터 1초씩 줄이는게 구현에 편할듯함

### 6) 버프 스킬 사용주기
  * 코드상으로는 엔버링크, 크리인만 엘고에 맞춰서 사용
https://github.com/oleneyl/maplestory_dpm_calc/blob/3b0b3d504ca3609a5b0eaf528befa1b20e1a7316/dpmModule/jobs/mercedes.py#L89
  * 자체적으로 측정한 딜 비중에서 엘고시간동안 넣는 딜량이 엘고 꺼진시간동안 넣는 딜량보다 약 3배쯤 더 강함
    * 하이퍼 버프스킬(엘비쉬 블레싱, 히어로즈 오쓰)도 마찬가지로 엘고와 같이 쓰는게 아마 딜량이 더 높을것으로 예상됨
 * 지속/쿨타임이 같은 크리인과 로얄나이츠 역시 최대한 같이 사용하여서 지속시간을 공유하는 것이 더 좋음

# 정보
코드상으로 확인된건 아니고 긴가민가한 사항들입니다.

### 1) 엘리멘탈 나이트의 최대 소환수는 2마리입니다
  * 2마리 소환상태에서 한마리를 추가로 소환하면 먼저 소환한 한마리는 해제됩니다.

### 2) 엘고 연계사이클 사용 시 거스트 다이브의 잔상이 빗나가는 버그가 있습니다
  * 거스트 다이브가 돌진기라 사용 직후 방향을 반대로 돌려야되는데, 잔상 발동의 방향이 발동 시점이 아닌 **현 시점**에서 캐릭터가 바라보는 방향으로 나가기 때문에 거스트 다이브의 잔상이 일부 빗나가게 됩니다
  * 근데 이건 너무 빠듯한 조건이라서 고려하지 않으셔도..

### 3) 메용2 (아마도) 최적의 사이클
  * 첫번째 사이클(엘고 발동) 30초 전 메용2 사용
  * 두번째 사이클(엘고 발동) 동시에 메용2 사용
  * 세번째 사이클(엘고 발동) 30초 이후 메용2 사용
  * 네번째 사이클(엘고 발동) 에 메용2 사용하지 않음
  * 다섯번째 사이클부터 반복 (30초 전 메용2 사용)
    * 그냥 쿨타임마다 돌려도 큰 차이는 없을듯

### 4) 연계사이클 사용 시 코어강화
* 코강에 필요한 스킬이 7개라서, 연계스킬 사용 시 보통 2중5코 사용
  * 2중5코 사용 시 7스킬을 2번 강화하고 남는 스킬강화 한칸은 차지/하이킥/문썰트를 보통 강화하지만, DPM 상으로는 라엣을 강화하는게 아주 조금이라도 더 유리

### 5) 전투분석 점유율
조금만 있다가 추가하겠습니다.. 내일 안에 올릴께요

**Comment by icepeng** [comment]
정보1 - 적용중입니다

1,2,3번 수정되었습니다. 나머지는 확인을 더 해보고 수정하겠습니다.

메르 딜레이가 왜 저렇게 입력했었는지 확신이 안서는데, 어쩌면 30ms가 추가되는 문제가 있었다가 수정되었을지도 모르겠습니다. 딱히 블래 카데나같은 기준을 적용한건 아닙니다.

**Comment by illhyhl1111** [comment]
ㅎㅇㅌㅎㅇㅌ

**Comment by icepeng** [comment]
엄청 도움됩니다. 단 시드링은 사용하지 않고 측정 부탁드립니다.

**Comment by icepeng** [comment]
메르 딜레이가 30ms씩 더해졌던건 공중에서 사용 페널티라고 메모되어있는데 무슨 뜻인지 저도 모르겠네요......

**Comment by icepeng** [comment]
그리고 어스듀는 공속이 30단위 올림적용이라 360ms가 맞습니다.

거다는 기본공속은 적용되는데 부스터만 안되는거 같아 4단계 공속 기준인 480ms를 사용했습니다.

추가 실험 요청드립니다.

5번만 우선 반영하고 4번은 확인 후 적용하겠습니다.

**Comment by illhyhl1111** [comment]
http://www.inven.co.kr/board/maple/2304/23223?name=subject&keyword=%EA%B3%B5%EC%86%8D
아 저거 말씀이시죠
기존 공속공식이 반올림이라서 그렇게 계산해버렸네요. 스듀는 360ms가 맞습니다. 측정값도 360ms로 나왔고요.

개인적으로 측정한 거다 딜레이는 510ms로 나왔습니다. 5단계랑 2단계(풀공속) 붙인 짤인데 딜레이가 정확히 일치합니다
![최종](https://user-images.githubusercontent.com/15259969/93629451-4ebc8b00-fa23-11ea-8f55-f6eb836bdb5d.gif)

**Comment by illhyhl1111** [comment]
근데 제가 실험할땐 풀공속은 쓸윈부로 맞춰놓았는데
기본공속, 익스그린은 적용되지만 부스터 쓸윈부같은 버프스킬류는 적용안되는 사항이라면 ㅄ같지만 납득은 되겠네요.
익스그린 기준 480ms가 나왔다면 그걸로 적용해주세요.

**Comment by icepeng** [comment]
공속 관련 - 부스터만 안받고 익스그린은 받습니다. 정신나간 스킬이네요.

스킬 딜레이 관련 - 스킬이 공중에서 연계될시 30ms가 추가되는 현상이 있다고 합니다. 코드를 660+30과 같이 변경하고 주석을 달아두는게 좋겠습니다.

6번도 해결해두었습니다.

**Comment by icepeng** [comment]
- [ ] 엘고 잔상
- [ ] 파택
- [ ] 유니콘 코강
- [ ] 스킬 딜레이
- [ ] 엘고 사이클
- [ ] 버프 주기

**Comment by illhyhl1111** [comment]
## 전분
![image](https://user-images.githubusercontent.com/15259969/93666588-6a26a500-faba-11ea-9c45-0c302cc2b84a.png)
![image](https://user-images.githubusercontent.com/15259969/93666605-71e64980-faba-11ea-900c-d06287dba922.png)
![image](https://user-images.githubusercontent.com/15259969/93666613-77dc2a80-faba-11ea-8a14-9a7aa6b62ec2.png)

## 스텟/스펙
![image](https://user-images.githubusercontent.com/15259969/93666625-97735300-faba-11ea-9750-7ba4ebc0f35f.png)
![image](https://user-images.githubusercontent.com/15259969/93666627-a0fcbb00-faba-11ea-9a5b-321a175b242b.png)
![image](https://user-images.githubusercontent.com/15259969/93666640-b96cd580-faba-11ea-8c43-536f44100f44.png)


* 2분 30초 측정
* 실피디아 미사용
* 엘고 켜져있을 때 스듀-엔릴-스듀-유니콘-스듀-스피어-거다
* 엘고 꺼졌을 때 이슈로 딜하면서 유니콘 디버프만 유지되도록 적당히 연계
  * 엘고 꺼졌을 때 정확한 딜사이클이 필요하다면 다시 측정하겠습니다
* 도핑 남아있을 때 했는데 문제가 된다면 노도핑으로 다시 측정하겠습니다
* 영상 필요하시면 영상 드리겠습니다

**Comment by illhyhl1111** [comment]
공중에서 연계는 음 제가 측정해본걸로는 그대로 나왔는데..
아주 정확하게 잰건 아니니까 넵 그렇게 해주세요

**Comment by icepeng** [comment]
이르칼라의 숨결, 16.3052%
어드밴스드 스트라이크 듀얼샷, 12.5933%
이슈타르의 링, 11.4516%
래쓰 오브 엔릴, 11.2602%
어드밴스드 파이널 어택, 10.1499%
유니콘 스파이크, 7.0490%
로얄 나이츠, 6.6598%
레전드리 스피어, 5.6223%
가이디드 애로우, 5.0250%
거스트 다이브, 4.3955%
엘리멘탈 고스트, 3.6774%
엘리멘탈 나이트, 3.0276%
스파이더 인 미러, 2.7302%
라이트닝 엣지, 0.0530%

오 이정도면 꽤... 좋습니다.

다만 파택 점유율 차이가 큰데 이걸 확인해봐야겠네요.

**Comment by illhyhl1111** [comment]
1.  파이널어택 터지는 공격이 951회 나가서 확률상 파택이 713번 터져야되는데 차이가 좀 나네요. 저도 버그 있는지 확인해 보겠습니다
2. 다이브는 위에서 말씀드린데로 잔상 발동방향 버그때문에 그런듯합니다
3. 엘리멘탈 나이트 3%는 너무 낮습니다. 보통 전분표대로 점유율이 나오는게 맞습니다.
4. 로얄 나이츠 6.7%도 너무 낮습니다. 가이디드에 로얄나이츠가 터져서, 시전 딜레이 도중에 첫타가 터지면서 1회당 타수가 336 혹은 352타가 나와야됩니다.(전분상으로는 서버랙때문에 늘어남)

**Comment by icepeng** [comment]
아 맞다 거스트 다이브에 파택 속성은 지정되어있는데 안나가는 버그가 있다는 제보를 들었습니다.

**Comment by icepeng** [comment]
엘리멘탈 나이트는 혹시 미리 2개 뽑아두고 치신게 아닌가 싶습니다.

**Comment by illhyhl1111** [comment]
나이트 미리 뽑아둔거 맞습니다.
파택은 그보다 전반적으로 연계스킬 사용시 파택이 씹히는 버그가 있는듯 하네요

![image](https://user-images.githubusercontent.com/15259969/93672033-a53cce80-fae2-11ea-89f5-4a7a396661a4.png)
확률상 사용횟수는 237회

![image](https://user-images.githubusercontent.com/15259969/93672060-e03f0200-fae2-11ea-9e83-f8d7f23f0318.png)
![image](https://user-images.githubusercontent.com/15259969/93672062-e6cd7980-fae2-11ea-8804-cea76e583d6f.png)
정확히 연계사이클 10번 돌렸는데.. 확률상 파택 발동회수는 131회입니다.

**Comment by illhyhl1111** [comment]
![image](https://user-images.githubusercontent.com/15259969/93672131-73783780-fae3-11ea-9e96-f3072cc17fe1.png)
![image](https://user-images.githubusercontent.com/15259969/93672134-796e1880-fae3-11ea-918f-1b9c085e2010.png)

엘고 없이 10번 때렸는데, 엘고 없으면 정상적으로 발동되는듯 합니다

**Comment by icepeng** [comment]
엘리멘탈 나이트는 지금 코드상 미리 2개를 뽑아두지 않고 1개만 뽑히니 점유율 차이가 이해갑니다.

지금 로얄 나이츠가 272타가 나오네요. 원인 찾아보겠습니다.

**Comment by icepeng** [comment]
가이디드에 로얄나이츠가 터져서 <<< 세상에... 적용하겠습니다. 감사합니다.

**Comment by icepeng** [comment]
거다는 억세게 운이 안좋은건가요 아니면 원래 엘고가 안터지나요..?

**Comment by icepeng** [comment]
1. 거다에 엘고/파택 안터지게 함
2. 엘고 잔상에 파택 안터지게 함

두개 조건을 주고 뽑아봤습니다.

Used는 참고하기 부적절하니 Hit의 합으로 판단해주세요.

거스트 다이브 Used 21 Delay 10080
Hit 84 Damage 272390870281.6 Loss 0.0
Share 2.2535%
라이트닝 엣지 Used 2 Delay 1260
Hit 6 Damage 6784874049.1 Loss 0.0
Share 0.0561%
래쓰 오브 엔릴 Used 25 Delay 5250
Hit 250 Damage 736223736274.6 Loss -0.0
Share 6.0908%
래쓰 오브 엔릴(엘고) Used 21 Delay 0
Hit 387.4499999999999 Damage 704517856957.5 Loss 0.0
Share 5.8285%
레전드리 스피어 Used 23 Delay 15870
Hit 69 Damage 362710306010.3 Loss -0.0
Share 3.0007%
레전드리 스피어(엘고) Used 20 Delay 0
Hit 110.69999999999996 Damage 356662768706.8 Loss -0.0
Share 2.9507%
로얄 나이츠(공격) Used 21 Delay 0
Hit 336 Damage 916946383532.2 Loss 0.0
Share 7.5860%
스파이더 인 미러(공간 붕괴) Used 1 Delay 720
Hit 15 Damage 60965944604.4 Loss 0.0
Share 0.5044%
어드밴스드 스트라이크 듀얼샷 Used 2 Delay 960
Hit 8 Damage 18262213106.7 Loss 0.0
Share 0.1511%
어드밴스드 스트라이크 듀얼샷(연계) Used 71 Delay 25560
Hit 284 Damage 797935566189.9 Loss 0.0
Share 6.6014%
어드밴스드 스트라이크 듀얼샷(연계)(엘고) Used 62 Delay 0
Hit 457.5599999999998 Damage 795116469454.3 Loss -0.0
Share 6.5781%
어드밴스드 파이널 어택(속사) Used 557 Delay 0
Hit 846.6399999999937 Damage 646511941566.5 Loss 0.0
Share 5.3486%
어드밴스드 파이널 어택(일반) Used 146 Delay 0
Hit 221.92000000000053 Damage 197012767431.8 Loss 0.0
Share 1.6299%
엘리멘탈 고스트(정령의 기운) Used 18 Delay 0
Hit 144 Damage 443262960483.3 Loss 0.0
Share 3.6671%
엘리멘탈 나이트 Used 2 Delay 0
Hit 0 Damage 0.0 Loss 0.0
Share 0.0000%
유니콘 스파이크 Used 23 Delay 10350
Hit 115 Damage 452750557267.3 Loss 0.0
Share 3.7456%
유니콘 스파이크(엘고) Used 20 Delay 0
Hit 184.49999999999994 Damage 449168390183.2 Loss 0.0
Share 3.7160%
이르칼라의 숨결 Used 1 Delay 900
Hit 0 Damage 0.0 Loss 0.0
Share 0.0000%
이르칼라의 숨결(틱) Used 52 Delay 7800
Hit 416 Damage 1502923434395.3 Loss 0.0
Share 12.4338%
이르칼라의 숨결(틱)(엘고) Used 52 Delay 0
Hit 269.10000000000025 Damage 583322157974.7 Loss 0.0
Share 4.8259%
이슈타르의 링 Used 505 Delay 60600
Hit 1010 Damage 1465230292463.6 Loss 0.0
Share 12.1220%

이르칼라의 숨결, 17.2597%
어드밴스드 스트라이크 듀얼샷, 13.3305%
이슈타르의 링, 12.1220%
래쓰 오브 엔릴, 11.9194%
로얄 나이츠, 7.5860%
유니콘 스파이크, 7.4616%
어드밴스드 파이널 어택, 6.9785%
레전드리 스피어, 5.9514%
가이디드 애로우, 5.3192%
엘리멘탈 고스트, 3.6671%
엘리멘탈 나이트, 3.2048%
스파이더 인 미러, 2.8901%
거스트 다이브, 2.2535%
라이트닝 엣지, 0.0561%

이 두가지 조건이 저 전분을 대체로 설명해주는거 같습니다.

**Comment by illhyhl1111** [comment]
1. 거다에도 잔상 터지는데 보통 다이브를 쓰고 바로 방향을 전환하면서 잔상이 모두 다 증발합니다.
전분표에서도 거스트 다이브 혼자 타수가 엄청 낮아요.

2. 파택이 터지기 전 방향을 반대로 보면 파택이 터지지 않습니다.
엔릴-방향키전환-스듀 연계를 하면 파택이 아예 안터지는걸 볼수 있습니다.
![image](https://user-images.githubusercontent.com/15259969/93674193-7e809700-fae6-11ea-839c-f5a5eff8a69d.png)
1회는 실수

3. 연계없이 천천히 스킬을 쓰면 파택이 정상적으로 적용됩니다.
예를 들어 엔릴 딱 한번만 쓰면 파택이 2회 이상 찍히기도 합니다.
![image](https://user-images.githubusercontent.com/15259969/93672033-a53cce80-fae2-11ea-89f5-4a7a396661a4.png)
여기서도 원래 확률에 비해선 덜터진게 맞는데 잔상에 안터진다기엔 타수가 많아요

어디선가 타격 주기가 엄청 짧아지면 파이널어택류 스킬이 증발한다는 얘기를 들었는데
이슈타르/이르칼라로 실험했을땐 문제없어서 아닌줄 알았는데 연계시 확실히 문제가 생기는거 같습니다.

버그까지 감안하고 DPM표 제작하신다면
1. 거스트 다이브에 잔상 미적용
2. 아무튼 연계시 파택이 터지는 횟수는 잔상 미적용시 횟수에 근사하므로 엘고 잔상에 파택 미적용

**Comment by icepeng** [comment]
제 생각에 잔상 로직이 파택과 유사한거 같습니다. 방향 바꾼다고 증발하는거 보면...

혹시 거다 쓰고 방향 안바꾸면 파택도 터지나요?

거다에 잔상 증발이 연계시 거의 100%에 벌어지는 일이면 반영하는게 맞습니다.

엘고 잔상에 파택증발은... 이것도 게임에서 안되는거니 적용하는게 맞다 싶긴한데 보마도 같이 조사를 좀 해야겠네요.

**Comment by illhyhl1111** [comment]
거스트 다이브 본체에는 정상적으로 파이널어택이 터집니다.
근데 방향전환을 아예 안해도 거스트 다이브가 잔상 이펙트만 터지고 타격이 안들어가네요?
뭐이런

**Comment by icepeng** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 그럼 거다는 잔상 빼야겠네요.

흠 파택이 안터진다고 들었는데 파택은 터지는군요...

**Comment by illhyhl1111** [comment]
더스크같은 크기가 큰 몹에게 실험하면 잔상데미지가 들어가네요
잔상 데미지가 들어가는 판정이 거스트 다이브 착지지점을 기준으로 정해지는게 아닐까 하는데 실험 좀 더 해봐야 알거같습니다

**Comment by icepeng** [comment]
아마 파택 판정이 그 파택을 터트린 스킬의 범위를 참조할텐데, 거다가 범위 판정이 많이 이상합니다. 그래서 전 파택도 안터진다 생각했는데...

**Comment by icepeng** [comment]
여기까지 실험에선

1. 엘고시 잔상 파택이 다씹힘
2. 착지 지점이 허수아비랑 겹쳐야 거다 잔상이 맞음. 그와중에 2,3회는 절대안터짐

이정도로 보이네요. 

혹시 잔상 안터지는 거다에도 파택은 터지는지 딱 한번만 더...부탁드립니다.

**Comment by illhyhl1111** [comment]
엘고 끄고 착지지점에 몹 놓고 파택 터지는지 보면 되는거죠?

**Comment by icepeng** [comment]
음 아뇨 착지지점이 아닌곳에 놓고 거다를 맞추기만 하면 됩니다

**Comment by illhyhl1111** [comment]
![image](https://user-images.githubusercontent.com/15259969/93686121-21d5aa00-faef-11ea-9cee-bfb6801efa0e.png)

아 그거라면 파택 정상적으로 터집니다.
거다 본체 판정에는 파택에 오류 없다고 보시면 될거같아요

**Comment by icepeng** [comment]
그럼 엘고판정과 파택판정이 같다고 생각하는것도 불가능해졌군요. 아란도 그러더니 영웅들이 참...

1. 잔상에 파택 전부 안터지게
2. 거스트는 잔상 안터지게

하는게 맞겠습니다. 이 변경안이 적절한지에 대해 의견이 모이면 반영하겠습니다.

실험 도와주셔서 정말 감사합니다.

**Comment by illhyhl1111** [comment]
화이팅화이팅

**Comment by icepeng** [comment]
거다가 왜 정확히 겹칠때만 잔상이 터지고, 2번째 잔상부터 안터지는지 이미지로 표현해보면

![image](https://user-images.githubusercontent.com/12782606/93711997-729be000-fb8d-11ea-9995-67ab62aa4f8a.png)

이렇게 동작하고 있을 확률이 무지 높습니다.......

**Comment by icepeng** [comment]
#470
