### ISSUE TITLE
패스파인더 카디널 디스차지와 카디널 블래스트 타수 문제

### ISSUE THREAD

**Issue by kanginha** [oleneyl/maplestory_dpm_calc#449]
안녕하세요, 올려주신 코드를 git clone한 후 실행을 해봤는데 몇 가지 의문 사항이 있어 issue를 남기게 되었습니다.
python test.py --job 패스파인더 --level 275 --ulevel 8500 --time 40 --log 로
**40초 딜 시뮬레이션**을 해보았을 때 카디널 블래스트와 카디널 디스차지의 데미지 정보만 추려보았을 때 다음과 같습니다.
(전체 로그는 맨 아래에 적어 두겠습니다)

카디널 디스차지 Used 54 Delay 11340
**Hit 16470** Damage 1412129388477.4 Loss 0.0
Share 13.1495%
카디널 블래스트 Used 54 Delay 12960
**Hit 21870** Damage 1514862661289.0 Loss -0.0
Share 14.1062%

카디널 디스차지의 Hit 수가 16470타,
카디널 블래스트의 Hit 수가 21870타로 나오는데,
이는 실제와 큰 차이가 있는 것 같아 어떤 식으로 계산된 결과인지 질문드립니다.

혹시나 도움이 될까 하여, 세글자님의 허수하비/루시드 실전 전투분석 표도 첨부하도록 하겠습니다.
![1](https://user-images.githubusercontent.com/40761899/93615803-d946bf80-fa0e-11ea-90e8-c164f6c9099c.jpg)
![2](https://user-images.githubusercontent.com/40761899/93615806-da77ec80-fa0e-11ea-90c5-442ae0ab0ed9.png)

이것을 보면, 실전딜보다 타수가 50-60배 이상 많이 나온 것 같은데 이에 대해 설명해 주실 수 있으실까요?

(전체 로그)
Total damage 10739015234379.3 in 40 second
Loss 251270349744.8

===Buff Skills===
렐릭 에볼루션 Used 1 Delay 0
렐릭 차지 Used 1 Delay 0
메이플 용사 Used 1 Delay 0
메이플월드 여신의 축복 Used 1 Delay 450
샤프 아이즈 Used 1 Delay 0
소울 컨트랙트 Used 1 Delay 900
쓸만한 윈드 부스터 Used 1 Delay 900
쓸만한 컴뱃 오더스 Used 1 Delay 1500
에인션트 가이던스(버프) Used 1 Delay 0
에인션트 보우 부스터 Used 1 Delay 0
에픽 어드벤처 Used 1 Delay 0
커스 톨러런스 Used 1 Delay 0
커스 트랜지션 Used 3 Delay 0
크리티컬 리인포스 Used 1 Delay 600

===Damage Skills===
스파이더 인 미러(공간 붕괴) Used 1 Delay 720
Hit 15 Damage 59859124434.8 Loss 0.0
Share 0.5574%
얼티밋 블래스트 Used 1 Delay 1380
Hit 75 Damage 749459664333.0 Loss 51244605905.2
Share 6.9788%
에디셔널 디스차지 Used 50 Delay 0
Hit 225.0 Damage 283086534866.8 Loss -0.0
Share 2.6361%
에디셔널 디스차지(렐릭 에볼루션) Used 38 Delay 0
Hit 57.0 Damage 75409659240.0 Loss 0.0
Share 0.7022%
에디셔널 블래스트 Used 54 Delay 0
Hit 162.0 Damage 270839234153.1 Loss 0.0
Share 2.5220%
에디셔널 블래스트(렐릭 에볼루션) Used 41 Delay 0
Hit 61.5 Damage 108312402098.1 Loss 0.0
Share 1.0086%
엣지 오브 레조넌스 Used 9 Delay 0
Hit 54 Damage 540000000000.0 Loss 200025743839.6
Share 5.0284%
카디널 디스차지 Used 54 Delay 11340
Hit 16470 Damage 1412129388477.4 Loss 0.0
Share 13.1495%
카디널 블래스트 Used 54 Delay 12960
Hit 21870 Damage 1514862661289.0 Loss -0.0
Share 14.1062%
콤보 어썰트 Used 3 Delay 0
Hit 0 Damage 0.0 Loss 0.0
Share 0.0000%
콤보 어썰트(디스차지) Used 2 Delay 1260
Hit 14 Damage 76014140686.9 Loss 0.0
Share 0.7078%
콤보 어썰트(디스차지)(화살) Used 2 Delay 300
Hit 10 Damage 58746291397.3 Loss 0.0
Share 0.5470%
콤보 어썰트(트랜지션) Used 1 Delay 630
Hit 7 Damage 45466272145.8 Loss 0.0
Share 0.4234%
콤보 어썰트(트랜지션)(화살) Used 1 Delay 150
Hit 5 Damage 35137868403.1 Loss 0.0
Share 0.3272%
트리플 임팩트 Used 10 Delay 0
Hit 150 Damage 923245409926.8 Loss 0.0
Share 8.5971%
트리플 임팩트(점프) Used 10 Delay 4500
Hit 0 Damage 0.0 Loss 0.0
Share 0.0000%

===Summon/DoT Skills===
가이디드 애로우 Summoned 1 Delay 720
Used 68 Hit 68
Damage 218048192813.7 Loss 0.0
Share 2.0304%
레이븐 템페스트 Summoned 1 Delay 570
Used 100 Hit 500
Damage 2406590067975.5 Loss -0.0
Share 22.4098%
렐릭 언바운드(디스차지) Summoned 1 Delay 630
Used 61 Hit 183
Damage 958321924862.9 Loss 0.0
Share 8.9237%
스파이더 인 미러(거울 속의 거미) Summoned 1 Delay 0
Used 5 Hit 200
Damage 295008237101.9 Loss 0.0
Share 2.7471%
옵시디언 배리어 Summoned 1 Delay 90
Used 31 Hit 124
Damage 455479806122.9 Loss 0.0
Share 4.2414%
이볼브 Summoned 1 Delay 600
Used 11 Hit 77
Damage 252998354050.4 Loss 0.0
Share 2.3559%

===Skill Share===
레이븐 템페스트, 22.4098%
카디널 블래스트, 14.1062%
카디널 디스차지, 13.1495%
렐릭 언바운드, 8.9237%
트리플 임팩트, 8.5971%
얼티밋 블래스트, 6.9788%
엣지 오브 레조넌스, 5.0284%
옵시디언 배리어, 4.2414%
에디셔널 블래스트, 3.5306%
에디셔널 디스차지, 3.3383%
스파이더 인 미러, 3.3045%
이볼브, 2.3559%
가이디드 애로우, 2.0304%
콤보 어썰트, 2.0054%
패스파인더 16108522851569.006

**Comment by cheese98** [comment]
타수와 퍼뎀의 위치가 바뀐 오류였고 아까 수정됐습니다.

repository 동기화하고 다시 돌려보시면 맞게 나올겁니다.

**Comment by kanginha** [comment]
수정사항 잘 확인하였습니다! 혹시 어떤 조건의 허수아비를 설정하신 건지 여쭤봐도 될까요?

**Comment by icepeng** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/pull/447
https://github.com/oleneyl/maplestory_dpm_calc/pull/444

방어율 300% 반감입니다. 렙뻥 포뻥 미포함입니다.
