### ISSUE TITLE
dpm 점유율을 보고싶습니다

### ISSUE THREAD

**Issue by jml845854** [oleneyl/maplestory_dpm_calc#457]
직업마다 점유율을 뽑아내서 보고싶은데 코드를 잘 읽지 못해서 어려움을 겪고있습니다.

어떤파일을 이용하면 점유율을 뽑을수 있을까요

**Comment by oleneyl** [comment]
코드 받으시고, python test.py --job 직업한글명 --log 실행해주시면 맨 밑에 점유율이 붙어나올겁니다

**Comment by icepeng** [comment]
제가 --stat 플래그를 넣어뒀습니다. 이쪽이 더 편합니다.
