### ISSUE TITLE
데몬슬레이어 서버러스에 블루블러드 적용

### ISSUE THREAD

**Issue by ehfkwlfkwl** [oleneyl/maplestory_dpm_calc#458]
for sk in [DemonSlashAW1, DemonSlashAW2, DemonSlashAW3, DemonSlashAW4, DemonImpact, DemonBaneTick, DemonBane2Tick, DevilCry, AuraWeapon]:

블루블러드가 적용되는 스킬 목록 중에 Cerberus가 빠져있네요.

**Comment by oleneyl** [comment]
아마 적용되어야 할 것 같은데, 확인부탁드립니다.

**Comment by icepeng** [comment]
적용되는게 맞습니다.
