### ISSUE TITLE
패스파인더 딜사이클

### ISSUE THREAD

**Issue by ilbeom** [oleneyl/maplestory_dpm_calc#46]
패스파인더 딜사이클이 극딜탐 레템+트랜지션 아스트라로 되어있던데 딜이 더 높은 블디+임팩레조 혹은 디스차지 아스트라로 해야 하지 않을까요?

**Comment by oleneyl** [comment]
보다 해당 딜 사이클에 대해서 자세히 알 수 있을까요?

**Comment by ilbeom** [comment]
아스트라(트랜)은 예전 제자리 스킬 끊김 완화 이후로는 말뚝딜에선 쓰지 않고, 그냥 블래디차임팩레조 평딜이 아스트라(디차) 보다도 소폭 더 강합니다.

**Comment by icepeng** [comment]
아스트라를 사용하지 않는것이 dpm이 더 높게 나와 딜사이클에서 제거했습니다. 감사합니다.
