### ISSUE TITLE
용어혼동에 의한 논쟁방지를 위한 용어 제시

### ISSUE THREAD

**Issue by skansla** [oleneyl/maplestory_dpm_calc#460]
일단 DPM표를 작성하신 노력에 박수를 보내드립니다.  작성하신 글 잘 보고 있습니다.

현재 패스파인더 관련 논쟁이 한참 띄거웠던걸로 압니다.  패스파인더 유저들의 생각하는 딜과 DPM 순위가 달라서 인것 같은데 
카데나와 블래스터 dpm만 봐도 dpm표와 실전딜은 전혀 다른건데 dpm순위가 바로 딜순위다라고 생각하시는 분이 많은거 같더라고요

dpm표는 이상적인 환경에서 이상적인 딜 싸이클로 시물레이션 한 값인데 
이 dpm이라는 단어를 실전딜로 해석할 수 있다고 생각합니다

댓글로 종종 저 딜량이 말이 안된다. 보스에선 딜싸이클 저렇게 못돌린다. 실전에서는 말도 안된다 등등 여러 말이 나오는 것 자체가 이상적인 상황에서 최대 데미지를 시뮬레이션한 실험이라는 걸 인지하지 못하고 있는 거라고 생각합니다.

Damage per Minute (분당 대미지) 이  아닌 

Maximum Damage Potential per Minute ( MDPPM, 분당 최대 데미지 포텐셜?, 분당 최대 잠재데미지 )
Expected Maximum Damage per Minute ( EMDPM, 분당 최대 대미지 기댓값) 

등의 용어로 dpm표를 오해석할 수있는 가능성을 줄일 수 있지 않을까 생각합니다. 

아마 스타포스 확률계산에 있어 기댓값이라는 용어가 더 친숙하지않을까 싶습니다.

**Comment by icepeng** [comment]
음... 어떻게 해도 안될거란 생각이 듭니다.

이름이 바뀌면 오히려 또 뭔가 다른거라고 생각하고 물고 늘어질거고... 차라리 그나마 유지되던 개념을 이어가는게 낫지 않을까요?

**Comment by skansla** [comment]
제목은 그대로 dpm을 유지한채 
본문이나 설명칸에 큼지막하게 설명하는 방식도 좋을것 같습니다.
선택은 제작자분께서 하시면 될 듯 싶습니다.

**Comment by oleneyl** [comment]
명칭을 바꾸어 불러도 커뮤니티에서의 명칭은 어차피 동일할 것 같아서..잘 모르겠습니다

**Comment by icepeng** [comment]
표 하단 혹은 워터마크로 설명을 보충하도록 하겠습니다.
