### ISSUE TITLE
패스파인터 관련 문의 입니다

### ISSUE THREAD

**Issue by jml845854** [oleneyl/maplestory_dpm_calc#464]
class JobGenerator(ck.JobGenerator):
    def __init__(self):
        super(JobGenerator, self).__init__()
        self.jobtype = "dex"
        self.jobname = "패스파인더"
        self.vEnhanceNum = 11
        self.ability_list = Ability_tool.get_ability_set('boss_pdamage', 'crit', 'buff_rem')
        self.preEmptiveSkills = 1

jobs.pathfinder 의 일부 입니다

어빌리티가 보스데미지, 크리티컬, 버프지속으로 되어있는것 같아서
보스데미지,크리티컬,상태이상으로 보고싶어서

buff_rem 을 mess 변경후 실행을했습니다.
실행을 한 후 결과가 똑같은데 뭘 바꿔야 볼 수 있을까요

변경 전
===Skill Share===
카디널 디스차지, 20.1092%
카디널 블래스트, 20.0586%
트리플 임팩트, 12.2233%
레이븐 템페스트, 11.1586%
엣지 오브 레조넌스, 9.8802%
렐릭 언바운드, 4.5040%
에디셔널 디스차지, 4.4514%
에디셔널 블래스트, 4.3254%
얼티밋 블래스트, 3.7150%
콤보 어썰트, 2.6235%
가이디드 애로우, 2.3642%
레이븐, 1.3499%
이볼브, 1.2981%
옵시디언 배리어, 1.2352%
스파이더 인 미러, 0.7034%
패스파인더 1020957070491.8694

변경 후
===Skill Share===
카디널 디스차지, 20.1092%
카디널 블래스트, 20.0586%
트리플 임팩트, 12.2233%
레이븐 템페스트, 11.1586%
엣지 오브 레조넌스, 9.8802%
렐릭 언바운드, 4.5040%
에디셔널 디스차지, 4.4514%
에디셔널 블래스트, 4.3254%
얼티밋 블래스트, 3.7150%
콤보 어썰트, 2.6235%
가이디드 애로우, 2.3642%
레이븐, 1.3499%
이볼브, 1.2981%
옵시디언 배리어, 1.2352%
스파이더 인 미러, 0.7034%
패스파인더 1020957070491.8694

**Comment by icepeng** [comment]
어빌은 현재 세팅상 레전 첫째줄만 사용되고 있습니다.

어빌 사용을 레전 3줄로 바꿔보시고 싶으면 `dpmgenerator.py`에 39번째 line을

`graph = gen.package(target, v_builder, ulevel = ulevel, weaponstat = weaponstat, vEnhanceGenerateFlag = "njb_style")`

에서

`graph = gen.package(target, v_builder, ulevel = ulevel, weaponstat = weaponstat, ability_grade=Ability_grade(4,3), vEnhanceGenerateFlag = "njb_style")`

이렇게 바꿔야 합니다. 코드 상단에서 `from dpmModule.status.ability import Ability_grade` 해두시면 됩니다.
