### ISSUE TITLE
패스파인더 레이븐 템페스트와 이볼브가 같이 쓰이는 것 같습니다.

### ISSUE THREAD

**Issue by gongganggit** [oleneyl/maplestory_dpm_calc#465]
안녕하세요. 수고가 많으십니다 ㄷㄷ

패스파인더 스킬 관련 질문이 하나 있는데, 혹시 이볼브와 레이븐 템페스트가 동시에 써지지 않는 건 적용되어 있는건가요? (이볼브 사용 중 레이븐 템페스트 사용시 이볼브 사라짐)

코드 보니까 레이븐이랑 이볼브는 서로 같이 안써져 있게 막혀있는건 보이는데, 레이븐 템페스트에는 별도로 이볼브를 끄는 코드는 보이지 않았습니다.

추가로 maplestats.com 에 나와있는 시간별 스킬 사용 그래프 (상세 dpm - 3번째 그래프) 보면 이볼브랑 레이븐템페스트가 같이 딜이 들어가고있는거 같아서 질문 드려봅니다

**Comment by icepeng** [comment]
1. 레템 사용시 이볼브 사라져야함 (레템 끝나면 이볼브가 아닌 레이븐으로 나오겠죠?)
2. 레템 도중에 이볼브 발동 불가능해야함 (레이븐이 없으면 이볼브 발동 조건 추가로 처리)

곧 수정하겠습니다.

**Comment by gongganggit** [comment]
넵 이볼브 사용 도중 레템 사용 시 이볼브는 사라지고, 레템 끝나면 레이븐으로 나옵니다. (레이븐 딜레이 0, 자동으로 나옵니다.)

수정 감사합니다.

**Comment by icepeng** [comment]
허어... 수정하니 이볼브 봉인하는게 dpm이 더 높게 나오네요.

레이븐도 코강을 하기 때문에 딜 차이가 적고, 레이븐은 공격마다 렐릭 게이지를 채워줘서 그런게 아닌가 싶습니다.

혹시 패파는 이볼브도 렐릭 게이지를 채워주나요?

**Comment by gongganggit** [comment]
앗 네 방금 실험해보고 왔습니다.

이볼브도 레이븐과 똑같이 공격시마다 렐릭 게이지를 10씩 채워줍니다.

**Comment by icepeng** [comment]
감사합니다.

지금 3모궁 모두 소환수와 이볼브 공격주기에 약간 문제가 있어 수정중입니다.
