### ISSUE TITLE
240초 주기 직업도 30분을 하는게 맞을까요?

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#469]
Discord를 통해 문의가 들어왔습니다.

현재 30분 측정은 120초,150초,180초,200초 주기는 모두 공배수지만 240초 직업에 대해 약간의 과대평가가 발생할 가능성이 있습니다. 극딜 이후 평딜 타이밍이 절반만 반영되기 때문입니다.

1시간 측정시 30분에 비해 히어로는 0.459%, 아크는 1.2% 가량의 차이를 보입니다.

이정도로 순위가 변동되기 어렵긴 하지만, 1.2%는 좀 위험하긴 합니다.

240초 직업의 경우 28분 혹은 32분 측정으로 평균내는게 어떨까 싶습니다.

**Comment by oleneyl** [comment]
음..1%오차범위정도는 괜찮다고 생각하긴 합니다. 직업별로 시간주기를 다르게 할거라면 다른 직업도 28, 32분을 측정해서 셋 중 제일 잘 나온 값으로 해줘야할것같아요,
