### ISSUE TITLE
패스파인더 에이션트 가이던스 설정방법

### ISSUE THREAD

**Issue by pathfinderalive** [oleneyl/maplestory_dpm_calc#472]
narnke님이 패파 코드해설 해주신거 보면

[렐릭 게이지와 에인션트 가이던스 게이지를 함께 관리합니다.
렐릭 게이지가 차오르면 에인션트 가이던스 게이지가 (현재 게이지 - 이전 게이지) 만큼 더해집니다.
에인션트 가이던스 게이지가 1000 이상이 되면, 가이던스 버프가 발동되면서 가이던스 게이지가 0으로 초기화됩니다.]

라고 적혀있는데, 이 부분만 보면 게이지 뺴는 과정이 없어서 10초 정도 단축되고있습니다.
렐릭게이지 0에서 1000채우는데 걸리는시간 13초에서 14초
 렐릭게이지 1000에서 임펙레조+어썰트로 빼면서 채우는데 걸리는시간 23초에서 24초
(에이션트 포스를 사용하지 않으면, 렐릭게이지가 감소하지않으므로 가이던스 게이지가 차지않습니다.)

그래서 가동률이 68%가 나오고있고 
실제 가동률은 55~56%라고 생각합니다.
이부분은 dpm에 직접적으로 영향을 준다고 생각합니다.
이 부분을 dpm실험에 적용하면 좋을거 같습니다.

추가적으로 dpm측정시 30분 측정 기준은 몇몇직업에 한해서 유리하거나 불리할수 있다고 생각합니다.
히로, 아크, 제로, 데슬같은 240초 극딜 직업들은 
1800초동안 점유율 높은 극딜기를 딱맞게 쓰지 못하기 때문에 정확한 dpm이라 보기 힘들다고 생각합니다.
각 직업마다 극딜주기에 맞는 딜량 체크후 소요시간을 나누어  dpm을 비교하는것을 제안합니다.

**Comment by icepeng** [comment]
렐릭 게이지와 가이던스 게이지는 별개로 동작합니다.

가이던스 게이지는 이미 렐릭 게이지의 delta만큼 채워지며, 렐릭 게이지가 1000일때는 충전되지 않습니다. 그러니까 문제가 없습니다.

dpm은 240초 직업중에 30분과 1시간 측정이 가장 큰 오차를 보이는 아크가 1.1%입니다. 순위를 크게 바꿀만한 요소는 아니나, 그래도 반영은 해야할거 같아 #469 에서 논의할 것입니다.
