### ISSUE TITLE
제논 "일정 주기" 측정 자료

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#473]
홀로그램 그래피티
---
하이퍼 3종 적용기준, 캡틴유니온 X
* 관통: 116회
* 역장: 64회
* 융합: 176회

메가 스매셔
---
풀차지 기준
* 타수 뜨기 직전 프레임: 27.641s
* 종료 직전 프레임: 40.920s
* 시전 횟수: 64회

오버로드 모드
---
| 타수 | 영상 시간 |
| - | - |
| 4타 | 9.041초 |
| 8타 | 18.792초 |
| 12타 | 28.011초 |
| 16타 | 32.006초 |

----

측정 대상: 마왕 발록

포톤 레이는 스킬이해도가 부족하여 실험을 못했습니다.

나중에 일본 DPM과 교차검증을 해보도록 하겠습니다.

**Comment by icepeng** [comment]
정리 완료되면 close하고 이쪽이나 Monolith쪽 wiki로 옮겨주세요
