### ISSUE TITLE
혹시 dpm표 퍼센트를 비숍을 100%로 작업해주실 수 있으신가요?

### ISSUE THREAD

**Issue by bishopuser** [oleneyl/maplestory_dpm_calc#483]
비숍을 100으로잡았을때는 직업간 격차를 보고싶습니다!

**Comment by oleneyl** [comment]
해당 수치는 직접 비숍의 배율을 기준으로 나눠보면 얻을 수 있습니다. 표의 작성 원칙에 대한 요청이신가요?

**Comment by bishopuser** [comment]
배포해주시는 표가 100프로 라는 기준직업이 따로 없어서
이 부분에 대해서 한 직업을 100프로로 잡고 만들어주신다면
직업간 격차가 더 직관적으로 표현될것같아서 요청드렸습니다.

**Comment by icepeng** [comment]
이런저런 요청이 너무 많아, raw data를 제공할 생각입니다.

전 직업 0초/2초/4초 데이터를 엑셀로 뽑아서 올릴테니, 직접 자기가 원하는 모양의 표를 구성하시면 되겠습니다.
