### ISSUE TITLE
아란 비욘더의 아드레날린 패시브 효과 적용 질문

### ISSUE THREAD

**Issue by rangers0113** [oleneyl/maplestory_dpm_calc#485]
코드를 보는데 
파이널 어택이나 파이널 블로우는 100+150 이런식으로 퍼뎀이 증가된 한편,
비욘더는 이런식의 퍼뎀 증가를 볼수 없었습니다
혹시 이 부분에 대해 확인이 가능하신지 여쭙고싶습니다

**Comment by cheese98** [comment]
비욘더 원래 퍼뎀이 285, 300, 315인데 코드상에는 385, 400, 415로 표기되어 있네요. 분리해서 넣는 방식과 합산해서 넣는 방식이 혼용되고 있는 것 같습니다.

**Comment by rangers0113** [comment]
아 그렇네용
