### ISSUE TITLE
쉐도우 파트너 계열 추가타격으로 로직변경

### ISSUE THREAD

**Issue by oleneyl** [oleneyl/maplestory_dpm_calc#49]
쉐도우 파트너 계열 추가타격으로 로직변경 필요

**Comment by oleneyl** [comment]
#54 듀얼블레이드 완료

**Comment by cheese98** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/blob/6938a23fe9b2c9cde487ab822c738299a0cca377/dpmModule/jobs/dualblade.py#L98

`450+18*vEhc.getV(2,2) * 0.7`로 하면 스킬 계수에만 0.7이 곱해지므로 전체에 괄호를 씌워야 할 것 같습니다.

그리고 블토(소환)만 미러이미징 함수를 사용하지 않는 이유를 여쭤봐도 될까요? 다른 직업들에도 쉐파를 적용하려 하는데 여기서 의문점이 들어서 여쭤봅니다.

**Comment by oleneyl** [comment]
수정하도록 하겠습니다.
`core.SummonSkill` 은 return되는 object의 목록에 포함되어 있어야 하고, 생성자가 DamageSkill과 같지 않아서 미러이미징 함수를 이용해 하나로 묶기 어려워서 따로 뽑아두었습니다.

**Comment by oleneyl** [comment]
#56 해당 부분은 수정했습니다. 추가적으로 수정할 부분이 있을까요?

**Comment by cheese98** [comment]
지금 제가 메갤에서 오픈톡으로 문의받는 중입니다. 완료되면 바로 올릴게요.

**Comment by icepeng** [comment]
create_auxilary_attack으로 해결 완료되었다고 판단해 닫습니다.
