### ISSUE TITLE
패스파인더 dpm 문의

### ISSUE THREAD

**Issue by jml845854** [oleneyl/maplestory_dpm_calc#490]
패스파인더가 딜을 할때 
엣지 오브 레조넌스를 트리플 임팩트를 쓴 후 공중에서 쓰는게 보통인데

dpm표의 딜 사이클은 레조넌스가 돌아올 때마다 쓰는게 맞나요?
레조넌스를 트리플 임팩트를 쓴 후 공중에 있을때만 쓰게 하고싶은데

트리플 임팩트에 
TripleImpact.onAfter(EdgeOfResonance)
이 코드를 추가해주면  정상적으로 동작하는게 맞을까요?

**Comment by icepeng** [comment]
이미

`TripleImpact.onConstraint(core.ConstraintElement("레조넌스 동기화", EdgeOfResonance, EdgeOfResonance.is_usable))`

가 걸려있어서 레조넌스가 사용 가능할때만 트리플 임팩트를 사용하고, 트리플 임팩트 직후에 레조넌스가 어차피 나갑니다.

**Comment by icepeng** [comment]
TripleImpact.onAfter(EdgeOfResonance) 으로 하면 onAfter는 뒤에 이어지는 스킬의 쿨타임이 돌았는지 별도로 체크하지 않고 강제로 실행합니다. 차라리 EdgeOfResonance.onBefore(TripleImpact)로 하는게 안전합니다. 이렇게 한다면 TripleImpact.protect_from_running()을 해두어야 합니다. 트리플 임팩트를 직접 사용하지 못하게 막고, 레조넌스 사용시에만 묶어서 사용하도록.

지금 딜사이클은 레조넌스와 트리플이 무조건 함께 나가니 수정할 부분은 없을 것 같습니다.
