### ISSUE TITLE
배메 5차스킬이 어둠이 아닌 물리속성으로 적용됩니다.

### ISSUE THREAD

**Issue by kellymonster** [oleneyl/maplestory_dpm_calc#494]
유니온 오라를 제외한 블랙매직 알터, 그림리퍼, 어비셜 라이트닝이 전부 물리속성으로 적용되 마스터오브데스 쿨타임 감소에 영향을 받질 않습니다.
관련 링크: http://www.inven.co.kr/board/maple/2295/101998
                 http://www.inven.co.kr/board/maple/2295/102048
추가로, 추석코인샵 패치 이후로 링크스킬의 후딜이 텔레포트로 캔슬이 안되는게 정상적이라고 답변이 왔는데, 엔버링크 후딜을 배메는 텔레포트(다크 라이트닝)로 캔슬이 이제 안되니, 디피엠에 유의미한 하락이 있는지 궁금합니다.

**Comment by icepeng** [comment]
블랙 매직 알터, 그림 리퍼, 어비셜 라이트닝 모두 elemAttr이 지정되지 않아 물리속성 판정이 되는것을 확인했습니다.

마스터 오브 데스의 데스 쿨타임 줄어드는 스킬 목록을 수정하겠습니다.

텔포의 엔버링크 후딜 캔슬은 이미 되지 않는 것으로 동작하고 있었습니다.
