### ISSUE TITLE
배틀메이지의 5차스킬이 물리속성으로 적용됩니다.

### ISSUE THREAD

**Issue by kellymonster** [oleneyl/maplestory_dpm_calc#495]
유니온 오라를 제외한 블랙매직 알터, 그림리퍼, 어비셜 라이트닝이 전부 어둠속성이 아닌 물리속성으로 적용되 마스터오브데스의 데스 재발동 쿨타임 감소에 영향을 받질 않습니다.
관련 링크: http://www.inven.co.kr/board/maple/2295/101998
                 http://www.inven.co.kr/board/maple/2295/102048
추가로, 추석코인샵 패치 이후로 링크스킬의 후딜이 텔레포트로 캔슬이 안되는게 정상적이라고 답변이 왔는데, 엔버링크 후딜을 배메는 텔레포트(다크or 어비셜 라이트닝)로 캔슬이 이제 안되니, 디피엠에 유의미한 하락이 있는지 궁금합니다.

**Comment by icepeng** [comment]
duplicate of #494
