### ISSUE TITLE
에반 패시브 스킬 중 문의

### ISSUE THREAD

**Issue by jml845854** [oleneyl/maplestory_dpm_calc#497]
ElementalReset = core.InformedCharacterModifier("엘리멘탈 리셋",pdamage_indep = 15)
        CriticalMagic = core.InformedCharacterModifier("크리티컬 매직",crit = 30, crit_damage = 20)
        MagicAmplification = core.InformedCharacterModifier("매직 엠플리피케이션",pdamage_indep = 30)
        DragonPotential = core.InformedCharacterModifier("드래곤 포텐셜",armor_ignore = 20)
        
        MagicMastery = core.InformedCharacterModifier("매직 마스터리",att = 30 , crit_damage = 20 + passive_level//2)
        DragonFury = core.InformedCharacterModifier("드래곤 퓨리",patt = 35 + passive_level)
        HighDragonPotential = core.InformedCharacterModifier("하이 드래곤 포텐셜",boss_pdamage = 20 + passive_level)

에반의 패시브 스킬 리스트 코드 입니다
패시브 레벨이 적용되어있는데 
인게임의 스킬은 

매직마스터리 : 숙련도 70, 마력 30 , 크뎀 20
드래곤퓨리 : 마력 35퍼
하이 드래곤 포텐셜 : 보공 20

인데 무엇때문에 적용되는지 알 수 있을까요?
이해가 잘 안되네요..

**Comment by oleneyl** [comment]
`passive_level` 은 컴뱃오더스 등으로 추가로 올라가는 스킬레벨을 뜻하는 인자입니다.

**Comment by oleneyl** [comment]
이름이 약간 모호하긴 하네요. 더 나은 이름이 있을까요?

**Comment by jml845854** [comment]
음.. bonus_level 이라거나 additional_level, 아니면 컴뱃오더스가 주로 레벨을 올려주니 combat_level도 나쁘지는 않을거같은데
제작자님이 제일 잘 알아볼 수있는 이름이 passive_level이면 현상유지도 좋을거같아요

아니면 알아보기 쉽게 주석을 짧게 달아서 설명해주는것도 좋을거 같구요

**Comment by icepeng** [comment]
정확히는 컴뱃 + 패시브 레벨 증가를 합한 수치가 `passive_level`인데, 이름 짓기가 애매해서 그렇게 해두었습니다.

컴뱃만 적용받는 스킬과 컴뱃,패시브레벨 둘 다 적용받는 스킬이 있기 때문에 이름이 확연히 구분될 필요가 있었습니다.
