### ISSUE TITLE
팬스파인텀 dpm 조사 필요

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#523]
http://m.inven.co.kr/board/maple/2299/5644931?iskin=maple

블디로 해도 마오팬 발동가능 -> dpm 상승여지 있음

**Comment by cheese98** [comment]
| 쿨감모 | 얼드 | 블디 | 차이 |
| - | - | - | - |
| 0초 | 4212699385025.799 | 4918817252152.127 | 16.76% |
| 2초 | 4258613599790.877 | 4961087481972.755 | 16.50% |
| 4초 | 4364816276169.7153 | 5030295869066.474 | 15.25% |

유니온 8000 기준 측정값입니다. 쿨감 4초 기준 stat 결과를 첨부합니다.
[pathfintom.txt](https://github.com/oleneyl/maplestory_dpm_calc/files/5588461/pathfintom.txt)
