### ISSUE TITLE
신궁 가이디드 애로우에 거리패시브 적용됩니다

### ISSUE THREAD

**Issue by orangemagic123** [oleneyl/maplestory_dpm_calc#524]
원래는 적용이 안 됐는데 스플릿애로우 겉값 패치하면서 거리측정 매커니즘이 좀 바뀌었나봐요
디스턴싱센스가 적용되는것은 확인했는데 라스트맨스탠딩과 위크니스파인딩도 적용되는지는 확인이 필요합니다.

**Comment by icepeng** [comment]
감사합니다. 확인해보겠습니다.

**Comment by icepeng** [comment]
가이디드 -> 적용
스인미, 이볼브 -> 미적용

라스트맨, 위크니스는 체크 못했지만 다 같이 적용된다고 가정
