### ISSUE TITLE
캐릭터 레벨 반영 여부

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#55]
```
D:\maplestory_dpm_calc>python test.py --job 패스파인더 --level 230
패스파인더 473250239788.3442

D:\maplestory_dpm_calc>python test.py --job 패스파인더 --level 240
패스파인더 473250239788.3442

D:\maplestory_dpm_calc>python test.py --job 패스파인더 --level 250
패스파인더 473250239788.3442

D:\maplestory_dpm_calc>python test.py --job 패스파인더 --level 260
패스파인더 473250239788.3442
```

동일스펙 기준 레벨에 따른 dpm 차이를 알아보려고 레벨 조건만 다르게 해보려고 했는데 다 똑같은 값이 뜹니다. 자연적인 스탯 상승 때문에 동일할 수가 없는데 왜 이렇게 나오는지 모르겠습니다. 한번 확인해주실 수 있으신가요?

**Comment by oleneyl** [comment]
확인해보겠습니다.

**Comment by oleneyl** [comment]
#57 수정했습니다.
template을 활용하는 경우에 레벨을 사용할 수 없도록 되어 있었습니다. 이전에 지원하던 옵션이
캡슐화 과정에서 제거된 것으로 보입니다. 다시 사용가능합니다.

**Comment by cheese98** [comment]
감사합니다. 제가 저런거 직접 만질정도로 이해도가 높지 않아 문의를 올릴 수밖에 없는 점 양해 부탁드립니다...

**Comment by oleneyl** [comment]
제가 코드를 너무 어렵게 짜두어서 그렇습니다..
닫도록 하겠습니다.
