### ISSUE TITLE
윈브 하울링게일 관련 질문

### ISSUE THREAD

**Issue by kowi10** [oleneyl/maplestory_dpm_calc#589]
현재 dpm상 딜사이클에서 게일이 쿨마다 쓰는 스킬로 구현 되어있는 걸로 알고 있습니다

이걸 스택을 구현해서 실전에서 쓰는것처럼 크리인 전 20 초정도부터 게일을 안쓰고 스택을 모으다 크리인과 맞춰서 3연속으로 1게일을 쓰면 dpm 상승이 있을지 궁금합니다.

만약 딜사이클을 위처럼 바꾼다면 크리인을 게일이 도는 120초 주기에 맞춰 돌리는 것과 기존처럼 110~114초마다 쿨이 도는대로 쓰는것 둘 다 고려해봐야 할 거 같습니다.

마찬가지로 딜사이클을 바꾸게 된다면 엔버링크도 기존처럼 쿨마다 돌릴지 크리인,게일에 맞출지 고려해봐야 할 거 같습니다.(게일을 크리인에 맞출려고 안돌리는 상황인데 엔버링크가 on일 경우 등등..) 
이 부분은 특히 윈드월과 함께 쿨감 4초 조건에서 쿨이 81.5초 정도로 줄어들어 3번 빡빡하게 돌리면 240초에 약간씩 뒤로 밀리면서 어거지로 맞출 수도 있어서 각 쿨감 조건마다 따로 고려해봐야 할 거 같습니다.

**Comment by icepeng** [comment]
감사합니다. 스택 방식으로 수정 후 시도해 보겠습니다.

**Comment by icepeng** [comment]
윈브 딜사이클 반영 완료되었습니다.
