### ISSUE TITLE
dpm표 제보입니다

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#59]
<details>
    <summary>1차 전문</summary>

제보자 [오후 12:44] ㅎㅇㅎㅇ
[cheese98] [오후 12:45] 안녕하세용
제보자 [오후 12:45] 표 보면서
제보자 [오후 12:45] 하는 캐릭이 좀 많긴한데 주력캐릭 관해서만
제보자 [오후 12:45] 제가 좀 봤거든요 딜 사이클이나
제보자 [오후 12:45] 점유율이나
[cheese98] [오후 12:45] 일단 이 문의내용이 github issue에 게시되는 것에 동의하시죠?
제보자 [오후 12:45] 정확히는 버프사이클
제보자 [오후 12:45] ㅇㅇ동의함다
제보자 [오후 12:45] 아무튼
[cheese98] [오후 12:45] 비공개적으로 하면 어머목 될수있어서 양해부탁드림다
[cheese98] [오후 12:45] 말씀해주세요
제보자 [오후 12:45] 제로부터 좀 보면
[cheese98] [오후 12:45] 제로: 륀축 미구현, 리미트 막타 미구현
제보자 [오후 12:46] 그거
제보자 [오후 12:46] 감안하고도 제가
제보자 [오후 12:46] 말하는거임 보니까 막타랑
제보자 [오후 12:46] 륀축이 없더라고여
제보자 [오후 12:46] 근데 일단 소울 컨트랙트랑 타임 디스토션 이 부분부터
제보자 [오후 12:46] 짚고 넘어가고 싶은 게
[cheese98] [오후 12:46] 넹넹
제보자 [오후 12:46] 보통 타임 디스토션에 증뎀이 있고
제보자 [오후 12:46] 이게 쿨감이나 쿨초를 먹어서
제보자 [오후 12:46] 이 디스토션을 먼저 깔고 딜을 하다가
제보자 [오후 12:47] 끝나갈 때 쯤 타임홀딩 시전하고 디스토션 깔고 버프 돌리면서 소컨까지 쓰고 탐브를 걸거든요
제보자 [오후 12:47] 그리고 이 탐브에 쿨초나 쿨감 먹는 스킬은 쿨타임이 오지게 뺑뺑뻉 돌아가는 그런 효과가 있음
제보자 [오후 12:47] 그래서 끝나갈 때 쯤 소컨이 한 번 더 들어갈 수 있게 되는데
제보자 [오후 12:48] 이 부분이 버프 표에 완전히 미반영 되어있더라고요
[cheese98] [오후 12:48] 탐브가 리밋브 말씀하시는거져?
제보자 [오후 12:48] 네네 리밋브
제보자 [오후 12:48] ㅈㅅㅈㅅ 탐브라 했네 맨날 탐브탐브 거려서
[cheese98] [오후 12:48] 저도 제로유저라서 잘 알쥬
제보자 [오후 12:48] 그리고 제로도 보통 벞지를 무조건 챙기게 되니까
[cheese98] [오후 12:48] 미구현돼있는건 저도 몰랐었네용
제보자 [오후 12:48] 소컨 시간이 저렇게 짧은 것도 약간
제보자 [오후 12:48] 의아합니다 왜냐면
제보자 [오후 12:48] 알파의 빛수 가동률 100% 때문에
[cheese98] [오후 12:48] 벞지는 어빌리티 적용할때 추가가 됩니다
제보자 [오후 12:48] 벞지 57%가 필수니까...
제보자 [오후 12:49] 아무튼 이러한 부분이 일단 첫째적으로
제보자 [오후 12:49] 의문이었고
[cheese98] [오후 12:49] self.ability_list = Ability_tool.get_ability_set('boss_pdamage', 'crit', 'buff_rem')
어빌을 각각 보공, 크확, 벞지를 사용한다는 뜻이예요
제보자 [오후 12:50] 네네
제보자 [오후 12:50] 그 뭐냐 그리고 이제 듀블...
제보자 [오후 12:50] 짚기 전에 30초만요
[cheese98] [오후 12:50] 알겠습니다
[cheese98] [오후 12:50] 천천히하셔요
제보자 [오후 12:50] 네네 잠깐 일 때문에
제보자 [오후 12:50] 그 이거 블토랑 카퓨가...
제보자 [오후 12:50] 보통 블토카퓨라고 부를만큼 둘이 같이 쓰잖아요?
[cheese98] [오후 12:51] 그렇죠 해조방송만 봐도
제보자 [오후 12:51] 근데 지금 보니까 블토 딜 점유율이
제보자 [오후 12:51] 38.24%나 되는데
제보자 [오후 12:51] 카퓨는 4.56% 밖에 안됩니다 이게 가장 큰 의문점이고
[cheese98] [오후 12:51] 그거 저도 좀 그렇더라고요
제보자 [오후 12:55] 죄송해요 또 뭐 한다고
제보자 [오후 12:55] 그리고 이...
제보자 [오후 12:56] 블레이드 스톰(틱)
제보자 [오후 12:56] 이게 도대체 뭔가 싶습니다 블레이드 스톰엔 틱 데미지가 없는데...
제보자 [오후 12:56] 아수라도 그렇고요
[cheese98] [오후 12:56] 잠시만요
[cheese98] [오후 12:57] 블레이드 스톰: 첫타
블레이드 스톰(틱): 후속타
제보자 [오후 12:57] 그리고 히든 블레이드가 파택 100% 부여 스킬이고 60초 지속인 가동률 50% 버프인데 점유율이 또 왜 이렇게 낮은지도...
제보자 [오후 12:57] 아 그런 의미였군요
[cheese98] [오후 12:57] 아수라 자체는 더미버프고요 아수라(틱)이 딜이네요
제보자 [오후 12:58] 네네 그건 보니까
제보자 [오후 12:58] 알 거 같아요
제보자 [오후 12:58] 그리고
[cheese98] [오후 12:58] 아수라 버프 지속시간동안 아수라(틱)이 반복해서 발동하는 매커니즘인것 같습니다
제보자 [오후 12:58] 아아
제보자 [오후 12:59] 그리고 에반...
제보자 [오후 12:59] 관련해서도 있어요
[cheese98] [오후 12:59] 점유율 관련은 제가 답변을 드리기가 어렵습니다
듀블을 안해보기도 했고 제가 저거 매커니즘을 자세히 하는게 아니라
[cheese98] [오후 12:59] 죄송합니다
제보자 [오후 12:59] 괜찮아요 이거 관해서
제보자 [오후 12:59] 의문점만 제기하는거라서
[cheese98] [오후 12:59] ㅇㅎ 많이 해주시면 저희야 감사하죠
제보자 [오후 1:00] 그리고 에반은 보통 미르가 쉴새없이 일을 해서 거의 안끊기는데 미르(사용중)이 생각보다 굉장히 많이 끊겨있습니다 이 점이랑
제보자 [오후 1:00] 점유율 부분에서
제보자 [오후 1:00] 다오어/브오윈/브레스 3종 이 다섯 개가 주력기이고 서클오브마나는
제보자 [오후 1:00] 에반의 주력기로 되어있거든요 이 부분까진 상관이 없는데
제보자 [오후 1:01] 이 브레스 3종이 아예 미산정 되어 있고
제보자 [오후 1:01] 서클 오브 마나의 딜 점유율이 극딜 스페셜리스트라서 고평가 받는 에반의 메인 극딜기인 조디악 레이의 준 3배의 수치를 갖는다는 점이
제보자 [오후 1:01] 굉장히 의아합니다 서클 오브 마나가 32.07%인ㄷ
제보자 [오후 1:01] 인데ㅔ
제보자 [오후 1:01] 조디악 레이는 11.86%로 산정되어 있어요
[cheese98] [오후 1:02] 흠 일단 에반은 최신패치가 반영이 안돼있네요
제작자분도 조디악 발동 수정을 TODO로만 걸어두시고 이후 변경내용이 업습니다
제보자 [오후 1:03] 해당 패치 반영 부탁드리고... 카데나는
[cheese98] [오후 1:03] 그리고 이것도 죄송하지만 제가 답변드리긴 어렵네요... 대신 반드시 건의해서 조치를 받을수 있도록 하겠습니다
제보자 [오후 1:03] 네네
제보자 [오후 1:03] 건의만 부탁드려요 제가 문의라서
제보자 [오후 1:03] 답변까진 바라진 않아요
제보자 [오후 1:03] 40캐릭 다 하는 사람 잘 없잖아요ㅎㅎ
[cheese98] [오후 1:03] 일단 최대한 말씀해주세요 문의만으로도 큰 도움이 됩니다
제보자 [오후 1:03] 그 카데나의 메일스트롬이 퍼뎀이 초당 5천%이긴한데
제보자 [오후 1:04] 카데나의 메인 딜은 연계에 있고 이 중 주력기는 니들배트거든요
제보자 [오후 1:04] 이 니들배트 쿨이 12초라고 하긴 하는데 단일 대상부터 딜뻥이 엄청나게 들어가는 것도 있고 해서
제보자 [오후 1:05] 거의 메일스트롬과 비등하거나 그 이상급인데 이 니들배트는 합쳐도 9%인데
제보자 [오후 1:05] 메일스트롬이 28.22%나 된다는 점...
제보자 [오후 1:05] 이 부분도 의아합니다
[cheese98] [오후 1:05] 니들배트 공격타겟 뎀퍼는 적용이 돼있구요
[cheese98] [오후 1:05] 점유율 관련해서는 저도 좀 의문이네요
저도 배트가 주력기라고 알고있었는데
제보자 [오후 1:06] 오드넌스의 딜 점유율도 10%나 된다는 것 또한 상당히 의문을 제기하고 싶습니다 이게 원래 하스우급 이상 보스에서도
제보자 [오후 1:06] 아무리 자주 깐다고 쳐도 이렇게까지 높은 점유율이 나오는 것도 아니고
제보자 [오후 1:07] 체인아츠 퓨리가 카데나의 꽃이라고 봐도 무방한데 이건 아예 적용이 안되어 있어요
[cheese98] [오후 1:09] 이게 허수아비 타겟이라 오드넌스를 최대한 설치한다고 가정한 상태라서 그런것 같아요. 아니면 제보자님께서 말씀하셨듯이 다른 스킬들이 너무 낮아서 얘가 상대적으로 높아보이는것 같기도 하고요.
[cheese98] [오후 1:09] 체인아츠 퓨리는 홈페이지 기준 4.81%로 나와있어요
제보자 [오후 1:09] 아아 방금 찾았어요 퓨리
제보자 [오후 1:09] 죄송해요
[cheese98] [오후 1:10] 아닙니다..
제보자 [오후 1:11] 그 잠시만요
제보자 [오후 1:11] 또 문의할 게 있어서
제보자 [오후 1:12] 점심만 먹고 문의드릴게요
[cheese98] [오후 1:12] 알겠습니다
[cheese98] [오후 1:12] 일단 지금까지 한거 업로드해도 될까요?
제보자 [오후 1:22] 네네

</details>
요약

1. 리미트 브레이크를 켜면 스킬 쿨타임이 빠르게 줄어드는데 구현이 되어있지 않습니다 : 디스토션 - 끝날때쯤 타임 홀딩으로 쿨초 후 버프를 돌리면서 엔버링크 사용 - 리미트 브레이크를 발동하면 스킬쿨이 빨리돌아 끝날때쯤 엔버링크를 한번 더 사용가능
2. 블토에 비해 카퓨의 점유율이 지나치게 낮음. 히든블레이드의 점유율도 너무 낮음.
3. 에반의 `미르(사용중)`이 굉장히 많이 끊겨있음. 브레스 3종 미산정, 서클오브마나의 딜 점유율 조디악에 비해 너무 높음.
4. 카데나의 니들배트 점유율이 메일스트롬에 비해 너무 낮음. 오드넌스는 너무 높음.

일단 이렇게 제보를 받았고, 나중에 추가 문의를 받으면 더 올리겠습니다. 오픈채팅으로 받으니까 문의가 들어오긴 하는데, 제가 일개 기여자인데 이렇게 해도 되는지 모르겠네요. 만약 원하지 않으신다면 채팅방은 닫도록 하겠습니다.

**Comment by cheese98** [comment]
<details>
    <summary>2차 전문</summary>

[cheese98] [오후 1:23] 실례지만 캐릭터나 커뮤니티 계정 같은거 인증해주실수 있으신가요? 신뢰도를 위해 부탁드리는 것이니 이해 부탁드립니다...
제보자 [오후 1:55] 그
제보자 [오후 1:55] 커뮤니티 계정은 제가
제보자 [오후 1:55] 인증을 못해드려요 개인 사정 때문에
제보자 [오후 1:55] 대신
제보자 [오후 1:55] 캐릭터 인증으로
[cheese98] [오후 1:56] 알겠습니다
제보자 [오후 1:56] 할게요
[cheese98] [오후 1:56] 캐릭인증이 더 좋죠
제보자 [오후 1:56] 스펙이 낮아서 공신력이
제보자 [오후 1:56] 있을까 싶은데
[cheese98] [오후 1:56] 그냥 신분확인만을 위한 것입니다
제보자 [오후 1:56] 잠시만요
[cheese98] [오후 1:57] 출처가 누구인지 밝히긴 해야할것같아서요
제보자 [오후 1:57] 사진
제보자 [오후 1:57] 현재 이 상태예요
[cheese98] [오후 1:57] https://maple.gg/u/%EC%A0%9C%EB%A1%9C%EB%B2%84%EB%A6%AC%EA%B3%A0%ED%95%A8
제보자 [오후 1:57] 네네 그거예요 현재 아마
제보자 [오후 1:57] 45층일거예요 저게
[cheese98] [오후 1:58] 인증에 응해주셔서 감사합니다
레벨, 스펙이 이해도를 대변해주지 않으니 소신껏 말씀해주시면 감사하겠습니다.
제보자 [오후 1:59] 그리고 블래스터 관련해서도 있는데 블래스터가 딜이 결코 낮은 편이 아니라고 생각하거든요. 타 직업 준극딜급 딜을 평딜로 끊임없이 우겨넣는다고 평가받고 저도 그렇게 생각을 하는데
제보자 [오후 1:59] 10위에 랭크된 점 때문에 블래스터는 전반적으로 계산에 어떠한 오류가 있지 않나 싶은 점도 있어요
[cheese98] [오후 2:00] 저나 제작자분이나 모든 직업을 꿰고 있지 않기 때문에 순위 관련해서는 문의해도 명확한 답변을 얻지 못하실 수도 있습니다. 일단 올려볼테니 답변이 불만족스러워도 이해해주세요.
제보자 [오후 2:01] 네네 괜찮아요
[cheese98] [오후 2:01] 궁금한 점 더 있으신가요?
제보자 [오후 2:01] 그리고 아델은 아예 없더라고요... 제가 현재는 아델로 갈아타서 아델이 메인이라
제보자 [오후 2:02] 검마 최초 격수였던 사람부터 거의 왠만한 서버 상위권에 랭크된 아델 유저들이 모인 방이 있는데
제보자 [오후 2:02] 거기 있는 방 대부분의 인원이 도대체 딜 산정을 어떻게 한건지 대체로 궁금해합니다 저도 그거 때문에
제보자 [오후 2:02] 상세 DPM까지 들어가서 봤는데
제보자 [오후 2:02] 이 항목이 아예 없어서 이건 이견조차 못내겠더라고요 저게 있어야 문의를 드릴 수 있는데
[cheese98] [오후 2:03] https://youtu.be/_VBcNu4Bw6c
제보자 [오후 2:03] 현재 이게 기준인건가요?
[cheese98] [오후 2:03] 이 전분을 기반으로 만들어진 것 같은데 저도 공식 설명은 없어서 잘 모르겠네요
[cheese98] [오후 2:03] 소스코드 주석에 있는 링크입니당
제보자 [오후 2:03] 저거랑 지금 엄청나게 많이 차이가 나요 거의 30% 이상 깎여나갔다는 게 주된 의견인데...
제보자 [오후 2:03] 일단 잠시만요
[cheese98] [오후 2:03] 네네
제보자 [오후 2:04] 네네 죄송해요
제보자 [오후 2:04] 아무튼 그게 주된 의견이거든요
제보자 [오후 2:04] 아델이 현재 평딜을 올려주는 임레샤드트레드 콤보를
[cheese98] [오후 2:04] 제가 아델은 아예 키워보지를 않아서 아예 몰라요..ㅠㅠ 일단 추가해달라고 부탁드려볼게요. 공식 설명이 떠야 아델분들도 피드백을 하실수가 있으니까
[cheese98] [오후 2:05] 일단 거기서 나온 의견 최대한 알려주세요
제보자 [오후 2:05] 한 번의 실수도 없이 계속 사용하면서 게블을 쿨마다 넣어도 절대 저 수치만큼의 딜이 안나올 거라고 생각해요
제보자 [오후 2:05] 제가 그럼
제보자 [오후 2:05] 거기 분들에게
제보자 [오후 2:05] 말씀드려서 의견 추합해서
제보자 [오후 2:05] 올게요
[cheese98] [오후 2:05] 알겠습니다
[cheese98] [오후 2:05] 그럼 일단 여기서 채팅로그 끊고 올려도 될까요?
제보자 [오후 2:07] 네네

</details>
5. 블래스터가 10위권인 것이 의아하다. 오류가 있는지 확인할 필요 있음.
6. 아델 딜사이클에 대한 설명이 존재하지 않아 유저들 사이에서 의문점이 많습니다.
[제로버리고함](https://maple.gg/u/%EC%A0%9C%EB%A1%9C%EB%B2%84%EB%A6%AC%EA%B3%A0%ED%95%A8/)님 제보입니다. 신뢰도 확보를 위해 제보자님께 캐릭터 인증을 요청했습니다.

**Comment by cheese98** [comment]
<details>
    <summary>3차 전문</summary>

제보자 [오후 2:40] 현재까진 주된 의견이
[cheese98] [오후 2:40] 네
제보자 [오후 2:40] 아델 테섭 시절을 기준으로 삼아서 평가 자체가 안되니 패치 내용 전부 적용해서 계산해주시고 딜 점유율이랑 버프 순서 올려달라고 하시네요 다들
[cheese98] [오후 2:41] 아하 알겠습니다
제보자 [오후 2:41] 그리고 그 검마 격수이신 분이
제보자 [오후 2:42] 지나가듯 걱정하면서 말씀하신건데
제보자 [오후 2:42] 에테르 게이지별로 크리에이션이 딜이 달라지는데 오더를 뽑으면 이 게이지가 사라지고 차오르고 이런 부분에 관해서
제보자 [오후 2:42] 계산하기 굉장히 어려울텐데 이에 대해 어떻게 하실건지 물어보세요 사실 저도 저게 좀
제보자 [오후 2:42] 의문이긴 하거든요 저게 엄청 유동적이라
[cheese98] [오후 2:44] 제작자님께서 상황에 따라 달라지는 경우는 평균치를 내셨더라고요
제보자 [오후 2:44] 풀 게이지가 400인데 오더 1번 뽑을 때마다 칼이 두 자루가 사출되고 게이지가 100이 나가거든요
제보자 [오후 2:44] 평균치...
제보자 [오후 2:44] 근데 문제가
[cheese98] [오후 2:44] 근데 아델은 안읽어봐서 어떻게 돼있는지 잘 몰라요
제보자 [오후 2:45] 평소엔 최대 게이지 300을 써서 칼이 총 6자루 유지되거든요 이게 6자루가 한계 사출량이예요
제보자 [오후 2:45] 근데 리스토어라는 5차 버프를 발동하면 이 사출량이 8까지 늘어나서
제보자 [오후 2:45] 게이지 400을 다 태워버릴 수 있어요 이러면 크리에이션이 아예 안차고
제보자 [오후 2:45] 이 리스토어에는 게이지 수급량을 트리거 스킬 한해서 50%인가 올려주는 효과가 있거든요
제보자 [오후 2:45] 이런 것도 다 계산이 혹시 가능한지 물어봐주실 수 있나요
[cheese98] [오후 2:46] 특수 자원을 쓰는 경우는 코드 내에 구현을 하셨더라고요. (예: 아란 콤보)
제보자 [오후 2:46] 크리에이션이 아예 안차고->크리에이션이 게이지 100 채워지기 전까지 아예 발동이 안되고
제보자 [오후 2:46] 음... 혹시 어떤 식으로 구현이 된건가요?
[cheese98] [오후 2:49] 아란같은경우 콤보 변수를 따로 둬서 계산을 해요. 아드끝나면 + 500, 인스톨마하 +100 이런식으로요
제보자 [오후 2:49] 아 그 콤보 수치가
제보자 [오후 2:50] 남는 정도의
제보자 [오후 2:50] 평균값을 낸다는 말씀이시죠?
[cheese98] [오후 2:50] 여기서는 실제 전투하듯이 계산을 하는 것 같아요
[cheese98] [오후 2:50] 제가 말한 평균은 파이널어택 70%일시 70%뎀지 적용 이거였구요
제보자 [오후 2:53] 흠...
제보자 [오후 2:53] 에테르 게이지가 파택이나 이런 거랑 너무 달라서 좀 걱정이 되긴하는데 일단 답변 주시는 분이 아델 관련 확답은
제보자 [오후 2:53] 불가능하다고 하셨으니
제보자 [오후 2:54] 일단 저 재계산 된 걸
제보자 [오후 2:54] 업데이트 해주시기 전까진
제보자 [오후 2:54] 기다려야 할 거 같긴 해요
[cheese98] [오후 2:54] 그렇죠...
제보자 [오후 2:55] 혹시 언제쯤 되는지 대충 알 수 있을까요?
[cheese98] [오후 2:55] 그건 잘 모르겠어요
제보자 [오후 2:58] 아... 계산을 시간 틈틈히 내서 하시는건가보네요
[cheese98] [오후 2:58] 저나 다른분들이나 이게 본업은 아니니까요
제보자 [오후 2:58] 그렇겠죠 아무래도 그럼 좀 기다려야겠네요
[cheese98] [오후 2:58] 안타깝지만 그럴수밖에 없네요
[cheese98] [오후 2:58] 더 문의하실 거 있으신가요?
제보자 [오후 2:59] 1달 정도 기다릴 거라고 생각하긴 했어요
제보자 [오후 2:59] 음
제보자 [오후 2:59] 아직 의견 더 모아봐야 할 거 같아서
제보자 [오후 2:59] 지금 당장은 모르겠어요
[cheese98] [오후 2:59] 일단 오늘은 여기까지?
제보자 [오후 3:01] 네네
제보자 [오후 3:01] 혹시 방 지우실건가요?
[cheese98] [오후 3:02] 일단 놔둬야죠
제보자 [오후 3:02] 알겠습니다 제가 그럼
제보자 [오후 3:02] 다른 직업 같은 것도
제보자 [오후 3:02] 의견 들리면 모아서
제보자 [오후 3:02] 말씀드릴게요
[cheese98] [오후 3:02] 만약에 문제가 될것같다고 하시면 터뜨릴거고 아니면 유지해야겠죠
[cheese98] [오후 3:02] 정말 감사드립니다.
제보자 [오후 3:02] 저는 커뮤니티
제보자 [오후 3:02] 그렇게 많이 안해서
제보자 [오후 3:02] 딱히 문제는 안됨다 저에게
[cheese98] [오후 3:02] 그럼 여기서 끊고 업로드하러갈게요
제보자 [오후 3:02] 네네
[cheese98] [오후 3:02] 고생 많으셨어요
제보자 [오후 3:02] 그거 혹시 업로드 되는 거
제보자 [오후 3:02] 공개로 되는건가요? 다른 사람도
제보자 [오후 3:02] 볼 수 있는
제보자 [오후 3:03] 공개면 저도 구경하려고...ㅎㅎ
[cheese98] [오후 3:03] 프로필은 비공개고요 발언만 공개입니다
제보자 [오후 3:03] 아아
제보자 [오후 3:03] 그럼 구경가겠슴다
[cheese98] [오후 3:03] https://github.com/oleneyl/maplestory_dpm_calc/issues/59
제보자 [오후 3:03] 감사함다 또 의견 모이면 말씀드릴게요
[cheese98] [오후 3:03] 넹넹
[cheese98] [오후 3:03] 즐메하세요
제보자 [오후 3:03] 네넵 즐메하셔요

</details>
아델이 너프를 먹으면서 딜사이클이 많이 달라졌는데 어떻게 반영이 될건지에 대한 내용이었습니다.


문의 방식에 대해: [메갤 글](http://m.dcinside.com/board/maplestory/10617543)에서 제보자분이 장문의 건의를 할테니 오픈톡을 열어달라고 부탁해서 이렇게 된 것입니다. 제작자님 허락 없이 임의로 이렇게 한 것은 정말 죄송합니다. 다른 방법이 없었다는 점을 이해해주시면 감사하겠습니다.

**Comment by oleneyl** [comment]
오픈소스인걸요ㅋㅋ @cheese98 님도 contributor이신데 문제될 것 없습니다.
피드백은 많을수록 좋으니까요. 반영할 시간이 있는가는 다른 문제지만..

**Comment by oleneyl** [comment]
나중에 취합해서 개별 이슈로 생성하도록 해야겠네요.

**Comment by cheese98** [comment]
감사합니다. 그러면 앞으로 직업 톡방이나 인터넷 등에서도 제보를 찾아보도록 하겠습니다.

혹시 개별 이슈 생성이 완료되면 이 이슈는 닫아도 될까요? 제보자분께서 커뮤니티 관련 언급을 원하지 않으셔서요.

**Comment by icepeng** [comment]
* 리밋브 쿨타임 가속 구현됨
* 듀블 수정됨
* 에반 수정됨
* 카데나 수정됨
* 블래 수정됨 (맥시마이즈 캐논 과열감소 미적용 문제였음)
* 아델 새로 구현함
