### ISSUE TITLE
윈브 천노 코강 마리수 증가 효과 안받음

### ISSUE THREAD

**Issue by Erixen1** [oleneyl/maplestory_dpm_calc#640]
코어 강화에 20렙에 마리수 증가 효과가 있는데 이러면 데미지가 20% 곱연산으로 증가해야되지만 증가가 안되는것같아요 확인 해봐야 할 것 같습니다

**Comment by cheese98** [comment]
Monolith11/memo#117 에서 윈브 천노를 포함한 타겟수-뎀증 효과를 확인중입니다.

**Comment by icepeng** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/issues/285

이때 측정에 의하면 뎀퍼가 1.2^4로 들어가는건 맞는 것 같습니다.

타겟+ 적용 여부 뿐만이 아니라, 1타겟일때 적용되는 데미지%를 따로 확인해야 합니다.

**Comment by mechmango** [comment]
https://gall.dcinside.com/mgallery/board/view/?id=danpoong&no=20579&_rk=zx3&page=1
천노 뎀퍼 중첩 실험결과입니다. 현재 테섭기준 1.2^3으로 적용됩니다.
