### ISSUE TITLE
무기 순공격력 구하는 함수

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#66]
```python
def getWeaponATT(koJob, spec):
    if spec < 5000:
        #파프
        return RootAbyss.WeaponFactory.getWeapon(weaponList[koJob], star = 0, elist = [0,0,0,0] ).att
    elif spec < 7000:
        #앱솔
        return Absolab.WeaponFactory.getWeapon(weaponList[koJob], star = 0, elist = [0,0,0,0] ).att
    else:
        #아케인
        return Arcane.WeaponFactory.getWeapon(weaponList[koJob], star = 0, elist = [0,0,0,0] ).att
```
해적 계열 직업들과 레프 직업군의 일부 스킬이 무기의 순수 공격력을 필요로 하기에 작성해서 `jobs/__init__.py`에 삽입해봤는데 init 파일과 직업 파일간의 순환참조에 걸려서 사용을 못하고 있습니다. 좋은 방법 없을까요?

**Comment by oleneyl** [comment]
`jobs/util.py` 를 생성해서 그 안에 삽입하면 가능한가요?

**Comment by cheese98** [comment]
```python
WEAPON_ATT = util.getWeaponATT("너클", 6000)
```
`util.py` 생성 후 인자를 직업이름에서 무기이름으로 바꾸니까 잘 작동하네요. `__init__.py`의 `weaponList`를 사용하려 하니까 직업 → init → 무기공격력 → 직업 형태로 순환참조가 생기는 게 원인이었습니다.

질문이 있는데요, 직업 코드 안에서 측정 스펙이 어느정도인지 확인할 수 있나요? (`spec` 변수) 그리고 무기 변경 기준을 코드처럼 5000, 7000으로 하는게 괜찮을지요?

**Comment by oleneyl** [comment]
직업 코드의 `generate()` 함수가 인자로 받는 `chtr` 항목이 `dpmModule.character.characterKernel.AbstractCharacter' 오브젝트 이므로 해당 인자에 접근하시면 됩니다.
무기 변경 기준은 아직 심도깊게 생각을 안해봤는데, 어떻게생각하시나요?

**Comment by cheese98** [comment]
혹시 `AbstractCharacter` 에서 측정기준 유니온 레벨을 가져올 수 있나요? `level`은 캐릭터 레벨을 가리키는 것 같아서요...

제 생각에 무기 기준은 현행 상태를 유지하되 사람들의 불만이 크다면 여론에 따라 바꾸는게 좋을 것 같습니다. 다만 캐릭터 레벨과 묶으면 안될 것 같습니다. (동일레벨에서 스펙별 성능 비교를 위해)

**Comment by oleneyl** [comment]
유니온 레벨을 직접적으로 가져오는 함수는 없습니다. 아니면 무기에 직접적으로 액세스 하는 편이 나을 수도 있을 것 같네요.
스펙 기준에 대해서 변경이 필요하다고 느껴지신 부분이 있으실까요? 저도 변경의 필요성을 느끼고 있습니다.

**Comment by cheese98** [comment]
8500대 스펙을 검마 격수를 대변하는 스펙으로 바꿨으면 합니다. 지금 기준으로 아이템은 충분히 강력하지만 레벨이 낮아 제대로 딜이 안들어갑니다. 캐릭터 레벨을 270 또는 275로 올리고 세트효과를 제네시스 + 4카5아로 바꾸는 게 어떨까요?

9000대를 따로 만드는 건 의미가 없다고 생각되는게, 8000대 유저들도 검마를 잘 가며 9000대인 유저 중에 검마를 못가는 사람도 있습니다. 그래서 차라리 8500대를 더 상향하는게 좋을 것 같다는 생각이 드네요.

**Comment by oleneyl** [comment]
네 그럼 초고스펙용 아이템셋을 생성하고, 제네시스 효과 추가부터 해야겠습니다.

**Comment by icepeng** [comment]
Item에 무기 공격력 추가, 해결되었음.
