### ISSUE TITLE
제논 템셋관련 문의 정리

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#685]
* 아이템 세팅 (도적템 기준)
  * https://gall.dcinside.com/mgallery/board/view/?id=danpoong&no=20485
  * 파프타일은 거의 사장된 아이템
  * 다른 직업들과 같은 아이템을 사용하면 됨
  * 파탈마 < 3카5앱 or 4카5앱 < 1아2카5앱
* 작
  * 무기: 힘 1작 + 나머지 럭작
  * 방어구: 방공 3작 + 힘 1작 + 나머지 방공작
  * 방공과 주흔의 가격차이를 감안해야 함
* 추옵
  * 도적템이라도 힘이 붙어있어야 함
  * 올텟퍼1%당 20, 합스탯/2하면 일반직업의 추옵식과 비슷
  * 공격력1은 합스탯 6의 효율을 가짐
* 잠재
  * 올스탯이 주스탯보다 뽑기 어려움
  * 올스탯 15퍼 + 주스탯 12퍼면 일반직업 주스탯 27퍼와 비슷함
  * 다만 위의 값은 이탈옵을 포함하고 있으므로 형평성을 위해 올스탯 15퍼 + 주스탯 9퍼로 설정해야 할 수도 있음
* 에디 (제안)
  * 공10 = 공10
  * 공20 = 공20
  * 유닠2줄 = 유닠 올스탯+공격력
  * 레전2줄 = 레전 올올
  * 레전3줄 = 레전 올올올
* 무기상수 & 직업상수
  * 직업상수는 제논의 속성이므로 현행코드 유지해도 괜찮음
* 놀장 vs 스타포스
  * 제논은 놀장 가능한 부위는 모두 놀장으로 강화하는 게 더 이득
  * 강화비용이 스타포스와 큰 차이 안날 정도의 스펙에만 적용해야 함

**Comment by icepeng** [comment]
closed by #696
