### ISSUE TITLE
GearedCharacter Template Formatting

### ISSUE THREAD

**Issue by oleneyl** [oleneyl/maplestory_dpm_calc#702]
- 파일 분리 기준

  - 설정 별로 파일을 분리하는 방향으로

- MODIFIER_FORMAT : 
   ```json
    {
        "stat_main":0,
        "stat_sub":0,
        "stat_sub2":0,

        "pstat_main":0,
        "pstat_sub":0,
        "pstat_sub2":0,
        
        "att":0,
        "cooltime_reduce":0,
        "armor_ignore":0,
        "pdamage":0,
        "boss_pdamage":0,
        "crit":0,
        "crit_damage":0,
        "pdamage_indep":0,
    }
   ```

- 아이템 설정 방식
  ```json
  keyword를 head, glove같은 키워드와
  공용 키워드는 acc, armor, weapon을 제시하여
  overriding되도록 하고
  assertion을 코드 안에서 처리하도록
  ```

- id
  - integer이나 string
  - integer이면 장비 id로 사용
  - string이면 해당 종류의 아이템을 가져와서 매칭
  - 없으면 목록에서 해당 아이템을 바로 가져옴

- addition=>(bonus), potential, add_potential
  - MODIFIER_FORMAT
  - bnous 판정 추가옵션 등급(attack_grade) : 무기류 공격력 추옵 계산을 위함

- 스타포스
  - star: 22
  - 음수는 놀장
  - 'surprise_bonus': 좋으신대로 구현(횟수, 확률)

- 강화 방식
  - 지금있는 방식 그대로
  - 대신 다양한 종류의 type을 제논, 데벤이 다능하게 support해주어야 함

- 보조무기
  - 보조무기, 보조무기(방패) 두 가지 지원하도록

- 기타 필드

  - arcane_symbol_force
  - authentic_symbol_force
  - pet_equip : integer(att)
  - pet_set : integer(att)
  - cash : MODIFIER_FORMAT
  - job_specific_item : MODIFIER_FORMAT
  - 제로 아이템 럭키주문서 종류
    zero_weapon_set_name

- 오버라이딩
  - 제로(보조무기, 카벨뚝)
  - 듀블(블레이드)

  - type : override, full
    - ```json
      head : {
          "id": "카오스 벨룸의 헬름"
      }
      ```
  - 제논
  - 데몬어벤져
    - rule을 설정하는 방식으로


- 리부트는?
  - 따로 템플릿을 나중에 만들것




- Loading configuration file ( HEAD FILE )

  - template.json 
    - ```json
      {
         "8000" : "8000.json",
         ...
      }
      ```

**Comment by OniOniOn-** [comment]
공용 키워드 미구현. (어차피 각각의 id를 설정해줘야 하기 때문에 의미가 있는지 모르겠음)
추옵 적용 시 "all_stat_rate"로 올스탯% 적용 가능.
주문서 적용 전 가능한 경우 황금 망치 자동 적용.
주문서 종류
 - "주문의 흔적 or 주흔": prob: int, stat: str
 - "매지컬": value: int(공격력)
 - "혼돈의 주문서 or 혼줌": option: MODIFIER
surprise_bonus: 확률(0~100 or None=0)

**Comment by icepeng** [comment]
closed by #696
