### ISSUE TITLE
섀도어 메익 타수 미적용 오류

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#73]
https://github.com/oleneyl/maplestory_dpm_calc/blob/933d6cd5c5cbbba48f9145e9482bab1f511aa380/dpmModule/jobs/shadower.py#L23

섀도어의 메소 익스플로전 점유율이 너무 낮다는 제보를 듣고 실험을 해보니 확실히 이상한 점이 있었습니다. 알고보니 `hit = 2 * stack`이 제대로 적용되지 않고 있었습니다. `dmg` 변수는 값을 건드리면 제대로 반영되는데 `hit` 변수는 터무니없는 값을 넣어도 결과가 똑같습니다. 타수 대신 데미지를 건드려서 원래 DPM을 추정해보니 최종 수치가 약 11.6% 정도 증가하는 것으로 나타났습니다. 한번 확인해주시면 감사하겠습니다.

이것과는 별개로, 쉐도우 파트너의 타격으로 떨어지는 동전이 반영되지 않고 있길래 수정 후 PR에 올렸습니다.

**Comment by oleneyl** [comment]
문제점 확인했습니다. core.ResultObject를 직접 액세스 하는 경우 damage에 타격수를 곱해서 입력해야 하는 오류였습니다.

#7fab78c
