### ISSUE TITLE
jobs/contrib.py의 create_auxilary_attack

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#76]
이거 쉐도우 파트너류 스킬용 함수 아닌가요? 듀블, 섀도어에 쓰인 함수랑 너무 비슷하게 생겨서요

**Comment by oleneyl** [comment]
오 그렇네요..언제 이런걸 만들었었지
이것으로 대체 가능할 것 같네요. 축뢰에 사용되고 있습니다.

**Comment by cheese98** [comment]
나중에 시간나면 한번 활용해보겠습니다. 지금은 영 시간이 안나네요.

**Comment by icepeng** [comment]
적용 완료됨
