### ISSUE TITLE
아델 관련 제보

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#77]
아델 이번에 계산 통계 내주신 건 감사합니다.
근데 수정하실 부분이 좀 많이 보여서 문의 드릴려고 해요. 적어만 놓을게요 일단.

1. 하이퍼 스킬에서 트리거-보스 킬러<-이거 안찍어요. 지금 저 보스 킬러를 다들 노빌리티-실드 리인포스로 바꾸는 게 정석이예요.

2. 크리에이션 평균 4자루 칼도 힘들어요. 보스에서 오더도 지금 4자루 유지가 간당간당해서 크리에이션 3자루라고 봐도 손색이 없어요.

3. 2번의 연장선으로 오더 칼 개수 5 안돼요. 3 나오면 많이 뽑은 거 같아요.

4. 크리에이션 최종뎀 효과 삭제됐어요. 저 코멘트 없애주셔도 됩니다.

5. 크리에이션 너프 이후로 딜 점유율 4% 내외 많아도 5% 나와요.

6. 오더가 허수아비 기준 딜 점유율 20~22%대고 디바이드는 10~11% 나와요. 실전 들어가면 오더 14% 디바이드 8%대로 급락하고 인피니트가 20~23% 정도 나와요. 아델톡방에 있는 62층에게도 확인해본 사항이예요.

7. 아델 지금 2중 4코가 아니라 2중 5코로 메타가 바뀌었습니다. 임페일/레조넌스/마커 코어 강화해요.

8. 밸패가 적용이 안되어 있는 것 같아요. 이걸로 언플이 너무 많아서 해당 기준이 밸패 전인 거 적어주셔야 할 거 같아요.

지난번 문의주셨던 분께서 추가로 보내주셨습니다. 제가 아델캐릭이 없어 확인해보지 못했으므로 시간을 두고 검증해봐야 할 것 같습니다.

**Comment by oleneyl** [comment]
#88 
1, 2, 3, 4 까지 수정되었습니다. 크리에이션 점유율은 8%, 디바이드가 20%인게 불일치 요인인데 이건 자료를 좀 더 받아봐야 될 것 같습니다.

**Comment by oleneyl** [comment]
다른 아델분께 딜 사이클 피드백을 확인받는 중입니다. 우선은 새로 issue를 만들고, 해당 이슈는 닫겠습니다.
