### ISSUE TITLE
KMST 1.2.117 issue

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#789]
DPM표에 직간접적 영향을 미치는 스킬들만 정리
* [패닉] : 액션 딜레이가 기존 대비 10% 감소되고 공격 범위가 기존 대비 35% 증가됩니다.
* [다크니스 오라] : 이펙트가 어둠과의 계약을 강화하는 컨셉으로 변경됩니다. 공격 범위가 기존 대비 30%, 종료 공격의 범위가 기존 대비 35% 증가되고 종료 공격의 데미지가 25레벨 기준 1275%에서 1325%로 증가됩니다.
* [미스트 이럽션] : 공격 발동 횟수가 4번에서 2번으로, 공격 횟수가 15번에서 10번으로 감소되고 데미지가 마스터 기준 45%에서 125%로 증가됩니다.
* [포이즌 체인] : 첫 공격의 데미지가 25레벨 기준 600%에서 500%로, 폭발 발동 횟수가 6번에서 5번로, 재사용 대기시간이 30초에서 25초로 감소됩니다.
* [라이트닝 스피어] : 데미지가 105%에서 150%로, 피니시 공격의 데미지가 350%에서 780%로 증가되고 최대 키다운 시간이 8초에서 3.6초로, 재사용 대기시간이 75초에서 60초로 감소됩니다.
* [썬더 브레이크] : 데미지가 25레벨 기준 1500%에서 1750%로 공격횟수가 8번에서 15번으로 증가되고 중첩해서 맞을 때마다 감소하는 최종 데미지가 5%에서 30%로 증가됩니다.
* [주피터 썬더] : 공격 횟수가 5번에서 8번으로, 재사용 대기시간이 75초에서 120초로 증가됩니다. 감전 중인 적에게는 번개 속성 공격의 최종 데미지가 12% 증가하는 기능이 추가됩니다.
* [디바인 퍼니시먼트] : 데미지가 25레벨 기준 350%에서 450%로 증가됩니다.
* [모탈 블로우] : 일정 횟수 공격 후 1번의 데미지가 증가하는 스킬에서 일정 시간 데미지가 증가하는 스킬로 변경됩니다.
* [아머 피어싱] : 직접 공격하는 스킬에 잔영의 시 액티브 효과가 추가되고 최종 데미지 증가량 최대 제한이 추가됩니다.
* [프리퍼레이션] : 액션 딜레이가 기존 대비 40% 감소됩니다.
* [애로우 레인] : 액션 딜레이가 기존 대비 37% 감소되고 공격 횟수가 8번에서 7번으로 감소되며 데미지가 25레벨 기준 1200%에서 1400%로 증가됩니다. 1명을 초과한 적마다 증가하는 공격 횟수의 최대치가 6번에서 8번으로 증가됩니다.
* [퀴버 풀버스트] : 액션 딜레이가 기존 대비 19% 감소됩니다.

**Comment by cheese98** [comment]
* [디스턴싱 센스] : 거리에 비례해 증가하는 최종 데미지가 4%에서 2%로, 최종 데미지 증가 최대치가 30%에서 12%로, 거리에 반비례해 증가하는 방어율 무시 증가량이 3%에서 2%로, 방어율 무시 증가 최대치가 20%에서 12%로 감소됩니다.
* [크로스보우 마스터리] : 최종 데미지가 마스터 기준 20% 증가하는 기능이 추가됩니다.
* [크로스보우 엑스퍼트] : 크리티컬 데미지 증가량이 마스터 기준 8%에서 15%로 증가됩니다.
* [어디셔널 볼트] : 디스턴싱 센스로 증가하는 능력치의 최대치가 증가하는 기능이 삭제됩니다. 최종 데미지가 마스터 기준 15% 증가하는 기능이 추가됩니다.
* [라스트맨 스탠딩] : 적이 1명 있다면 데미지가 증가하는 기능이 자기 주위에 다른 파티원이 없거나 스킬이 1명만 공격하면 데미지가 증가하는 기능으로 변경되고 최종 데미지 증가량이 마스터 기준 20%에서 15%로 감소됩니다.
* [위크니스 파인딩] : 최소 거리에서 증가하는 방어율 무시 증가량이 마스터 기준 10%에서 20%로 증가하고 거리에 비례해 증가하는 방어율 무시 증가량이 4%에서 3%로 감소됩니다.
* [트루 스나이핑] : 거리에 관계없이 디스턴싱 센스로 증가하는 모든 능력이 최대치로 적용되게 됩니다.
* [에인션트 가이던스] : 지속 중 렐릭 게이지를 채울 경우 지속시간이 연장되게 됩니다.
* [스로우 블래스팅] : 액티브 효과의 지속시간이 60초에서 90초로, 폭발 부적 개수가 45개에서 68개로, 재사용 대기시간이 120초에서 180초로 증가됩니다.
* [멸귀참영진] : 방어율 20% 무시 효과가 추가됩니다.
* [피스트 인레이지] : 액션 딜레이가 기존 대비 13% 감소됩니다.
* [크루 커맨더쉽] : 소환된 선원마다 다르게 증가하던 능력치가 선원이 1명이라도 소환되어 있으면 모두 증가하게 변경됩니다. 마스터 기준 크리티컬 확률 증가량이 15%에서 10%로 감소되고 HP와 MP 증가 기능은 삭제됩니다. 선원의 최종 데미지가 증가하지 않는 현상, 특정 조건에서 최대 숫자를 초과해 소환되는 현상이 수정됩니다.
* [스트레인지 봄] : 액션 딜레이가 기존 대비 16% 감소됩니다.
* [데스 트리거] : 25레벨 기준 데미지가 1150%에서 650%로, 공격 횟수가 11번에서 7번으로, 탄환 발사 간격 및 첫 발사까지의 딜레이가 기존 대비 50% 감소됩니다. 적을 공격한 탄환이 튕길 적이 없다면 허공에서 튕겨 이미 공격한 적을 다시 공격하게 되고 컨티뉴얼 에이밍이 적용된 적이 있다면 해당 적에게 우선하게 튕기게 됩니다. 불릿을 소모하지 않는 현상, 불릿 공격력이 적용되지 않는 현상이 수정됩니다.
* [몽키 웨이브] : 최고 출력 사용 시 버프 지속시간이 30초에서 60초로 증가됩니다.

**Comment by cheese98** [comment]
* [로얄 가드] : 한손검과 방패를 착용해야 사용할 수 있게 되고 액션 딜레이가 35% 감소됩니다.
* [소울 어썰트] : 액션 딜레이가 기존 대비 6% 감소됩니다.
* [샤이닝 크로스] : 액션 딜레이가 기존 대비 11% 감소됩니다.
* [클라우 솔라스] : 빛의 검이 추가 구현될 때 직접 공격하는 스킬을 사용해야 구현되게 됩니다. 로얄 가드 버프 중첩에 따른 공격 범위가 기존 대비 140%, 110%, 90%, 74%, 10% 증가됩니다.
* [소드 오브 소울 라이트] : 지속시간이 30초에서 35초로 증가되고 지속 중 스킬을 재사용 해 강력한 공격을 하는 라이트 포스레이를 1회 사용할 수 있는 기능이 추가됩니다.
* [라이트 오브 커리지] : 빛의 검을 생성하는 기능이 소드 오브 소울 라이트로 이동하고 용기의 빛 디버프 및 빛의 기둥이 삭제됩니다. 25레벨 기준 보호막 최대치가 260%에서 265%로, 지속시간이 10초에서 12초로 증가되고 액션 딜레이가 기존 대비 24% 감소됩니다.
* [트루 사이트] : 액션 딜레이가 기존 대비 33% 감소됩니다.
* [엘리시온] : 균열 폭발에 필요한 공격 횟수가 감소됩니다. 엘리시온 종료 시 폭발하지 못한 균열은 즉시 폭발하게 되나 데미지가 감소합니다.
* [소울 이클립스] : 액션 딜레이가 기존 대비 55% 감소되고 솔루나 디바이드를 공중 및 특정 스킬 사용 중 사용할 수 있게 됩니다.
* [약점 분석] : 크리티컬 데미지 증가량이 마스터 기준 15%에서 20%로 증가됩니다.
* [블레이징 익스팅션] : 액션 딜레이가 35% 감소됩니다.
* 키다운 중 시그너스 팔랑크스의 방향을 전환할 수 있게 됩니다.
* [엘리멘트 : 다크니스] : 최종 데미지가 마스터 기준 15% 증가하는 패시브 기능이 추가됩니다.
* [쉐도우 점프] : (중략) 공중에서 사용한 스킬의 최종 데미지가 증가하는 기능이 삭제됩니다.
* [쉐도우 바이트] : 25레벨 기준 재사용 대기시간이 20초에서 15초로 감소되고 버프 지속시간이 17초에서 20초로, 쓰러뜨린 적 당 증가하는 최종 데미지가 1%에서 2%로, 보스 몬스터 공격 시 증가하는 최종 데미지가 14%에서 16%로, 최종 데미지 증가 최대치가 15%에서 18%로 증가됩니다.
* [래피드 스로우] : 래피드 스로우로 다크 사이트가 해제되지 않게 되고 최소 지속시간이 2.7초에서 1.8초로, 최대 지속시간이 4초에서 3초로 감소됩니다. 데미지가 25레벨 기준 850%에서 950%로, 공격 횟수가 4번에서 5번으로 증가됩니다.
* [신뇌합일] : 재사용 대기시간 중 일정 시간마다 공격 적중 시 번개 1개가 발동되는 패시브 효과가 추가됩니다. 패시브 효과는 액티브 효과와 함께 발동되지 않습니다.
* [창뇌연격] : 마지막 연계와 함께 발동하는 거대 번개가 3개 발동하게 됩니다.

**Comment by cheese98** [comment]
* [아드레날린 부스트] : 버프 프리저가 적용되게 됩니다. 콤보 1000 도달 시 즉시 발동되지 않고 일정 시간 콤보가 유지되며 그동안 아드레날린 부스트 액티베이트를 사용해야 발동하게 됩니다. 일정 시간 안에 발동하지 않으면 콤보가 감소됩니다.
* [드래곤 퓨리] : 마력 증가에 필요한 최소 마력이 30%에서 15%로 감소됩니다.
* [얼티밋 드라이브] : 데미지가 마스터 기준 125%에서 140%로 증가됩니다.
* [마크 오브 팬텀] : 탤런트 오브 팬텀시프로 사용하는 공격 스킬 적중 시에도 괴도의 증표를 획득할 수 있게 됩니다.
* [약점 간파] : 크리티컬 데미지 증가량이 마스터 기준 20%에서 25%로 증가됩니다.
* [스펠 마스터리] : 마스터 기준 데미지 15%, 크리티컬 확률 15%가 증가하는 기능이 추가됩니다.
* [라이프 타이달] : 비율에 따라 데미지 혹은 크리티컬 확률이 증가하는 기능이 삭제되고 적은 비율이 일정시간마다 회복되는 기능이 추가됩니다.

**Comment by cheese98** [comment]
* [데빌 크라이] : 액션 딜레이가 기존 대비 21% 감소됩니다.
* [블루 블러드] : 액션 딜레이가 기존 대비 26% 감소됩니다.
* [데몬 어웨이크닝] : 액션 딜레이가 기존 대비 21% 감소됩니다.
* [아머 브레이크] : 액션 딜레이가 기존 대비 9% 감소됩니다.
* [데몬 프렌지] : 데몬 프렌지로는 HP가 최대 HP의 30%까지만 감소하게 됩니다. 해당 HP 이하에서는 회복 제한도 받지 않습니다. 최종 데미지 증가 기준치가 25레벨 기준 3%에서 2%로 감소되고 최종 데미지가 최대 35%까지 증가하게 됩니다.
* [레버넌트] : 사용 중 치명적인 상태이상에 걸리지 않게 되고 25레벨 기준 재사용 대기시간이 300초에서 240초로, 지속시간이 35초에서 30초로, 스킬 종료 후 받는 기본 피해량이 최대 HP의 5%에서 1%로 감소됩니다.
* [리프트 프레스] : 리프트 매그넘으로 연계할 수 없게 됩니다. 적을 잡을 때 데미지가 마스터 기준 140%에서 250%로 증가되고 공격 횟수가 2번에서 1번으로 감소됩니다. 밀어낼 때 데미지가 마스터 기준 140%에서 250%로, 공격 횟수가 1번에서 4번으로 증가되고 공격할 수 있는 최대 적 수가 15명에서 8명으로 감소됩니다. 액션 딜레이가 기존 대비 29% 감소됩니다.
* [리프트 매그넘] : 스킬이 삭제됩니다.
* [매그넘 캐논] : 리프트 매그넘 대신 추가되는 신규 스킬로 건틀렛 리볼버에 내장된 캐논을 사용해 불릿을 전방으로 발사합니다. 리프트 프레스와 스킬 레벨을 공유합니다.
* [쇼크 웨이브 펀치] : 공격 범위가 기존 대비 70%, 충격파의 공격 범위가 기존 대비 9% 증가됩니다.
*  [슈퍼 인듀어런스] : 리프트 프레스와 매그넘 캐논의 데미지가 증가하는 기능이 추가되고 리프트 매그넘의 데미지가 증가하는 기능이 삭제됩니다.
* [인듀어런스 트레이닝Ⅱ] : 매그넘 캐논의 데미지가 증가하는 기능이 추가됩니다.
* [건틀렛 엑스퍼트] : 마스터 기준 크리티컬 데미지 증가량이 15%에서 20%로, 보스 몬스터 공격 시 데미지 증가량이 15%에서 20%로 증가됩니다.
* [하이퍼 매그넘 펀치] : 차지 중 스턴 상태이상에 걸리지 않게 되고 재사용 대기시간이 150초에서 120초 감소됩니다.
* [버닝 브레이커] : 아래 방향키를 누르며 키다운을 종료하면 돌진하지 않고 제자리에서 공격이 발동되는 기능이 추가됩니다.
* [다크 라이트닝] : 검은 징표의 지속시간이 5초에서 10초로 증가되고 자신에게만 적용되게 됩니다.
* [어비셜 라이트닝] : 지속 중 다크 라이트닝 대신 칠흑의 번개가 발동하는 기능이 삭제되고 명계의 통로 사이를 텔레포트 할 때도 다크 라이트닝이 발동하게 됩니다. 다크 라이트닝이 발동될 때 및 검은 징표의 공격이 발동될 때 배틀메이지 주변에 명계의 번개가 떨어지는 기능, 지속 중 검은 징표의 공격이 수회 발동해야 검은 징표가 소비되는 기능이 추가됩니다. 명계의 통로 이펙트 크기가 기존 대비 45%로 감소됩니다.
* [서먼 재규어] : 어나더 바이트의 지속시간이 8초에서 15초로 증가됩니다.
* [서먼 재규어-쿨타임 리듀스] : 재사용 대기시간 감소량이 10%에서 20%로 증가됩니다.
* [재규어 맥시멈] : 재사용 대기시간이 150초에서 120초로, 무적 시간이 25레벨 기준 12초에서 10초로 감소됩니다.
* [와일드 발칸 Type X] : 최대 키다운 시간이 8.5초에서 7.2초로, 데미지가 25레벨 기준 950%에서 900%로 감소 공격 횟수가 4번에서 5번으로 증가됩니다. 키다운 중 MP가 1000 미만이 되면 스킬이 종료되는 현상, 사용 시 소비한 MP가 자동으로 회복되는 현상이 수정됩니다.
* [블레이드 댄싱] : 공격이 발생하기 전 및 스킬 종료 시의 액션 딜레이가 기존 대비 16% 감소됩니다.
* [오파츠 코드] : 액션 딜레이가 기존 대비 39% 감소됩니다.
* [컨파인 인탱글] : 액션 딜레이가 기존 대비 46% 감소됩니다.
* [메가 스매셔] : 기본 공격 시간이 8초에서 10초로 증가되고 차지를 통해 증가하는 공격 시간이 25레벨 기준 7초에서 5초로, 재사용 대기시간이 180초에서 165초로 감소됩니다. 재사용 대기시간이 공격 시작 시 적용되게 되고 스턴 중 키다운 해제 시 스턴을 취소하며 공격하는 현상이 수정됩니다.
* [마그네틱 필드] : 자기장 코일이 1개도 설치되어 있지 않을 때 아래 방향키와 함께 사용하여 3개의 자기장 코일을 한 번에 설치하는 기능이 추가됩니다.

**Comment by cheese98** [comment]
* [윌 오브 소드] : 검이 날아갈 때의 액션 딜레이가 파이널 피규레이션 중에는 기존 대비 60% 감소되어 일반 상태와 동일한 딜레이로 적용됩니다.
* [윌 오브 소드 : 스트라이크] : 검이 날아갈 때의 액션 딜레이가 파이널 피규레이션 중에는 기존 대비 60% 감소되어 일반 상태와 동일한 딜레이로 적용됩니다.
* [[처형] 체인 시클] : 마무리 공격의 데미지가 마스터 기준 200%에서 220%로 증가되고 첫 공격 이후 포제션을 사용하면 마무리 일격이 발동되지 않는 현상이 수정됩니다.
* [[처형] 포이즌 니들] : 첫 공격의 데미지가 마스터 기준 235%에서 250%로 증가되고 스킬 UI에서 더블 클릭으로 사용할 수 없는 현상이 수정됩니다.
* [그라인딩Ⅱ] : 팬텀 블레이드의 데미지 증가량이 마스터 기준 75%p에서 35%p로 감소됩니다.
* [프로페셔널 에이전트] : 재사용 대기시간이 200초에서 180초로 감소되고 공격이 발동되는 몬스터가 1명이라면 공격 횟수가 2배로 적용되는 현상이 수정됩니다.
* [마스코트 패밀리어] : 매지컬 버블을 트윙클 스타 혹은 매지컬 벌룬을 사용했을 때 획득하게 됩니다.
* [태도 마스터리] : 최종 데미지 5% 증가 기능이 추가됩니다.
* [대검 마스터리] : 최종 데미지 5% 증가 기능 추가되고 공격 속도 증가량이 2단계에서 3단계로 증가됩니다.

**Comment by cheese98** [comment]
* [싸이코 브레이크] : 공격받은 적 1명 당 증가하는 최종 데미지가 1%에서 2%로 증가되고 최종 데미지 증가 최대치가 20%에서 15%로, 액션 딜레이가 기존 대비 12% 감소됩니다.
* [각성] : 최종 데미지 증가량이 마스터 기준 25%에서 30%로 증가됩니다.
* [두루마리 도력] : 이전에 사용했던 천지인 속성과 다른 속성 스킬을 사용하면 해당 스킬의 최종 데미지가 5% 증가하는 기능이 추가됩니다.
* [둔갑 천근석] : 파초풍 : 천, 파초풍 : 실, 멸화염 : 천, 멸화염 : 실에서 연계할 때 조금 더 부드럽게 연계할 수 있게 됩니다.
* [고급 부채 숙련] : 최종 데미지 증가량이 마스터 기준 35%에서 25%로 감소됩니다.
* [선기 : 극대 분신난무] : 분신의 수가 12개에서 10개로 감소됩니다.

**Comment by icepeng** [comment]
* [퀵 드로우] : 지속 중 퀵 드로우를 소모하지 않는 스킬의 최종 데미지가 증가하는 현상이 수정됩니다.
