### ISSUE TITLE
캡틴 퀵드로우

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#79]
설명에는 미적용이라고 나와있는데 딜사이클에 포함되어 있는 것 같아서 여쭤봅니다. 어떤 매커니즘으로 작동되는 건가요?

그나저나 캡틴은 고스펙 참고자료가 정말 없네요... 인게임에서 고확으로 찾아봐야하나 싶습니다.

**Comment by oleneyl** [comment]
퀵드로우는 적용되고 있는 것으로 보입니다.

```python
        QuickDrawShutdownTrigger = QuickDraw.controller(core.infinite_time())

        for start, end in [
            [DeadEye, DeadEye]]:
            start.onBefore(QuickDraw)
            end.onAfter(QuickDrawShutdownTrigger)
```

데드아이 사용 직전에 퀵드로우를 사용하고, 사용 직후에 QuickDrawShutdownTrigger를 발동하여 퀵드로우를 종료시킵니다.
