### ISSUE TITLE
블래스터 직업의 애프터이미지 쇼크(패시브)와 관련한 문제

### ISSUE THREAD

**Issue by jaehwan1912** [oleneyl/maplestory_dpm_calc#801]
블래스터 직업의 DPM 산출 통계에서
애프터이미지 쇼크(패시브) 가 약 1.3607%의 점유율을 차지하는 것으로 나오는데
애프터이미지 쇼크 스킬의 패시브 효과의 발동조건은 

애프터이미지 쇼크의 재사용 대기시간 동안 건틀렛 리볼버를 이용한 직접 공격 적중 시 **주변의 공격받지 않은** 최대 7명의 적을

인 것으로 알고 있습니다.

애프터이미지 쇼크(패시브)가 DPM에 포함된 것이 오류인지,
아니면 특수한 조건 하에 애프터이미지 쇼크(패시브)가 DPM상 딜 상승의 여지가 있는 것인지에 대해 질문드립니다.

감사합니다.

**Comment by icepeng** [comment]
발동되지 않는게 맞습니다. 수정하겠습니다.
