### ISSUE TITLE
get_dpm 함수에 level 값을 넣을 수 없는것 같습니다

### ISSUE THREAD

**Issue by kchung1995** [oleneyl/maplestory_dpm_calc#829]
readme 에 있는 예시 코드에는
print(gen.get_dpm(ulevel = 7000, level = 240, weaponstat = [4,6]))
가 유니온 레벨 7000, 캐릭터 레벨 240, 무보엠 잠재 레전/유효6줄을 의미한다고 되어있는데,

get_dpm 함수에는 level 값을 받는 항목이 없는 것으로 보입니다.
실제로 적혀 있는 코드를 복붙해서 실행시켜 보면 unexpected argument 'level' 이라는 문구가 뜨네요.

**Comment by icepeng** [comment]
API가 변경되면서 readme가 업데이트 되지 않은 것으로 보입니다. level 인자가 삭제되었고, spec_name으로 대체되었습니다. 현재 지원되는 spec_name은 "4500", "6000", "7000", "8000", "8500"이 있으며, 기본적으로 ulevel과 1:1로 대응됩니다.

**Comment by icepeng** [comment]
각 spec_name에 해당되는 스펙 상세는 dpmModule/character/configs 내의 yaml 파일에서 확인할 수 있습니다.

**Comment by oleneyl** [comment]
아이고..조속히해결하겠습니다.

**Comment by oleneyl** [comment]
#831 로 수정하였습니다. Readme의 예제 코드 둘 모두 작동 확인했습니다. @kchung1995
