### ISSUE TITLE
제로 무기 옵션 오류제보 (루나서버 '천병원'님)

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#83]
[원문](https://gall.dcinside.com/board/view/?id=maplestory&no=11286781)

현재 코드에는 라피스와 라즐리의 모든 옵션이 동시에 적용되지만 실제로는 보조무기의 공격력이 적용되지 않습니다.

즉, 무기 공격력이 2배로 적용되는 오류가 있습니다.

제보자분께서 직접 확인해보신 결과 무기 공격력 차이와 대체로 일치한다고 합니다. 

제로도 보조무기에 예외처리를 할 필요가 있어보입니다.

**Comment by oleneyl** [comment]
해당 이슈는 DPM 계산 코드 내에서 작용하는 문제점은 아니며, 웹 사이트 자체 프로그램의 이슈인 것으로 확인되었습니다.
dpm 계산과정에는 악영향을 주지 않습니다.

**Comment by cheese98** [comment]
답변 감사드립니다.
