### ISSUE TITLE
카데나 제보 (크로아 서버 '맛있는라면님'님)

### ISSUE THREAD

**Issue by cheese98** [oleneyl/maplestory_dpm_calc#89]
[제보자 프로필](https://maple.gg/u/%EB%A7%9B%EC%9E%88%EB%8A%94%EB%9D%BC%EB%A9%B4%EB%8B%98)
[원문 링크](https://gall.dcinside.com/board/view/?id=maplestory&no=11378681)

1) ~~테이크다운 필요없음~~

2) 쓸오더 써야함(카데나는 쓸오더효율 압도적으로좋음)

3) ~~오드넌스 뎀퍼20보공20 빼야함~~

4) ~~배트 2, 3타 최종뎀 빼야함~~

5) 메일사용주기가? 느려지는 타격수 계산되어있나 이상적인건 4초마다

6) ~~상태이상 6개 다 적용된거맞나? 베놈버스트 지속시간이 처음10초이후 아예 빠져있음~~

7) 딜사이클 내가쓰는게 더 셈 - 이건 나중에 제보자분께 다시 물어보겠습니다

(제보자분과는 별개로, 카데나 어빌이 재사용 대기시간 초기화인데 아직 제대로 구현이 안 되어 있습니다. 이게 완전히 구현되기 전까지는 별도의 설명을 붙일 필요가 있어보입니다.)

----

그리고 이 DPM표에 대해 이야기를 나눌 공개적인 커뮤니티가 딱히 없는 것 같은데, 단풍 마이너 갤러리 같은 곳에서 문의를 받아도 될까요? 인구도 별로 없고 로그인 없이도 글 작성이 가능한 곳이라서 적합해 보입니다. 물론 신뢰도를 위해 본캐 인증된 사람의 문의만 받을 거고요.

**Comment by oleneyl** [comment]
- 7을 확인해주시면 딜 사이클 반영해보도록 하겠습니다. 
- 네 괜찮습니다. 오픈 프로젝트이니 어디서든 언급하셔도 상관없을 것 같습니다.

**Comment by oleneyl** [comment]
1, 3, 4 반영 완료

**Comment by icepeng** [comment]
6도 적용되었습니다.

**Comment by icepeng** [comment]
메일스트럼은 3단계의 공격속도를 가집니다. 메일스트럼 1,2,3 각각 만들어두고 onAfter으로 붙이면 될 것 같습니다. 여기에 4초마다 재사용 조건을 어떻게 작성할지가 어렵네요.

단순하게 하려면 4초 약 32타로 측정되는데, 4초지속 32타 소환수로 취급해도 큰 문제는 없어보입니다.

**Comment by icepeng** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/pull/329
