### ISSUE TITLE
dpm 연산에 관해

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#93]
* 메르세데스 쿨감 적용이 일부 직업의 일부 스킬에만 되어있습니다
  * 히어로의 인스팅트에는 적용되어 있으나, 메카닉의 전탄발사에는 적용되지 않고 있습니다
  * 대부분의 직업의 스킬에 red 설정이 들어가지 않고 있는데, red의 default를 True로 잡고, 일부 하이퍼스킬에만 False로 명시하는 것이 코드 작성하기 더 편할 것으로 예상합니다

* 모든 직업 공통으로 480초어치 시뮬레이션을 하고있는데, 직업별 극딜 쿨에 따라 저평가와 고평가가 이루어지고 있습니다
  * 특히 히어로는 240초 주기의 인스팅트가 메르쿨감을 적용받아 시뮬레이션 내에 3번 사용되고 있어 과대평가가 이루어집니다
  * 메르 쿨감이 적용된 각 직업별 극딜기 쿨타임의 배수로 시뮬레이션 시간을 따로 설정해야 한다고 생각합니다

* dpm은 본래 무한한 시간만큼 때린다고 가정하고, `deal/time`을 적분하는 느낌으로 계산하는 수치로 알고 있습니다
  * 카데나, 블래스터 등등... 스택형 패시브들은 처음부터 풀스택으로 놓고 계산하는게 맞다고 생각합니다
  * 스택이 한번 쌓이고 떨어질 일이 없는 경우는 스택 변화량을 추적할 필요가 없어 코드가 더 간단해집니다
  * 이미 작성된 코드들을 전부 고치기 힘들다면 시뮬레이션 시간을 왕창 늘리면 오차가 0에 수렴하는데, 서버 부하가 우려됩니다

**Comment by oleneyl** [comment]
- 메르세데스 쿨감 효과의 default는 조속히 변경하도록 하겠습니다.
- 시뮬레이션 시간은 서버 사이드에서는 변경 가능합니다. 직업별로 극딜 주기를 정리할 수 있다면 해당 사항을 반영할 수는 있을 것 같습니다.
- 스택형 스킬의 경우 일부 스킬은 처리가 되어 있고, 일부 스킬은 처리가 안 되어 있어서 확인이 필요합니다.

**Comment by cheese98** [comment]
메르세데스, 제로, 스트라이커는 풀연계를 기준으로 하고 있습니다. 나머지는 따로 확인해볼 필요가 있습니다.
