### ISSUE TITLE
dpm 계산 기준에 관해

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#95]
dpm 계산에 있어 사용한 기준을 명확히 할 필요가 있다고 생각합니다. 예를 들자면 허수아비 사이즈 보스를 타격하는지, 보스와 캐릭터의 레벨은 어떻게 되는지, 보스의 방어율을 어떻게 되는지 등등... 사이트에도, 문서에도 명확히 정리된 자료가 없습니다.

시뮬레이션 환경에 따라 dpm이 크게 달라질 요소는 다음과 같습니다.

* 캐논슈터의 BFG 캐논볼은 50회 충돌로 되어있으나, 허수아비로 전분을 하면 27회 충돌만 나옵니다. 이는 유니온 8천기준 캐논슈터가 3등에서 13등까지 내려가는 차이를 만듭니다.
* 썬콜의 썬더 브레이크 또한 8타 모두 들어가는 것으로 계산되고 있으며, 허수아비 기준 2타만 적용하면 dpm이 크게 내려갑니다. 유니온 8천 기준 25등에서 37등까지 내려갑니다.

저는 장기적으로는 dpm을 두가지로 나누는게 좋다고 생각합니다. 캐릭터의 포텐셜을 최대로 뽑아낸 지금 상태의 dpm과 맵 중앙의 허수아비를 타격하는 환경에서의 dpm 각각을 제시해야 한다고 생각합니다.

야구에서 출루율만 보는것도, 장타율만 보는것도 틀린 판단을 유발합니다. 선수의 가치를 한가지 방향으로만 판단하는 것은 불가능하기 때문입니다. dpm이라는 자료 또한 단 하나의 수치만으로는 충분한 정보를 제공하기 힘들다고 생각합니다. 현재 구현된 dpm은 모든 직업의 ceiling만을 알려주며, average를 알려주지 않습니다. 이는 이론상의 최대치만 높은 직업에 있어 큰 왜곡을 일으키게 됩니다. 반대로 average만을 알려주면 몇몇 직업의 최대 포텐셜을 알려줄 수 없게 됩니다. 결국 두 수치 모두 제시하고 해석은 사용자에게 맡기는 방법이 최선입니다.

지금 구상중인 방법은 다음과 같습니다. 코드상에서 각 직업별로 generate 메소드에서 스킬 정의와 딜사이클 그래프 정의가 합쳐져있는데, 이를 스킬 목록을 반환하는 메소드와 딜사이클 그래프를 정의하는 추상 메소드로 분리하고, 이를 상속받아 딜사이클만 변경 가능하도록 할 수 있어보입니다.

여기서 한발짝 더 나아가면, 스킬 목록을 API로 노출해서 프런트에 뿌려주고, 이를 토대로 사용자가 딜사이클을 작성하면 다시 서버에서 시뮬레이션 결과를 돌려주는 방식으로도 할 수 있습니다. 여기까지 구현되려면 굉장히 멀어보이지만... 가장 이상적인 도착점이라고 생각합니다.

* 현재 기준 dpm 계산의 전제를 문서, 프런트에 명시
* 최소한의 코드 변경으로 다양한 조건을 연출 가능하도록 코드 구조 개선
* (정말 언젠간) 프런트에서 딜사이클을 작성해 연산 요청 가능한 시스템 개발

**Comment by icepeng** [comment]
글이 길어지면서 이상해졌는데...

각 직업별로 조건 제시는 잘 되어있으나, 왜 조건이 그렇게 설정되었는가에 대한 일관적인 기준이 있어야 한다는 의미로 제기한 이슈입니다.

**Comment by oleneyl** [comment]
- 제가 개발하던 당시의 기준은 허수아비 기준 타격이었습니다. 
- 조건부 옵션을 인자로 받아올 수 있는 기능을 추가하는 방식으로 해결할 수 있는 문제인 것 같습니다.
- 딜 사이클에 대해 말씀해 주셨는데, 딜 사이클의 경우 get_ruleset() 메서드에 연산 규칙정의하도록 되어 있습니다. 즉, generate() 메서드에서 스킬들 간의 상호작용(ex. 파이널어택은 딜 사이클에 무관하게 공격스킬 발동 후 발동) 을 정의하고, get_ruleset()에 정의된 rule에 따라(ex. 극딜을 함께 사용) 이 부분에서 어떤 스킬을 함께 사용할지, 어떤 스킬과 어떤 스킬을 함께 사용하지 말지를 정의하도록 되어 있습니다. 다만 해당 기능을 실제로 적용하기 시작한 지는 얼마 되지 않아 아직 혼재되어 있습니다.
ruleset 관련해서 해당 부분을 문서화할 필요가 있겠네요.

- dpm 계산의 전제조건을 문서화 하는것은 괜찮은 것 같습니다. 이부분은 코드에 주석으로 명시하고, 프런트 단에서 주석값을 읽어와서 전시하면 될 것 같습니다.

- 추가로, 프런트 단에서 딜 사이클을 작성하는 안을 고려해보았었으나 UI가 마땅히 생각나지 않아 중단해둔 상태입니다.

**Comment by icepeng** [comment]
허수아비 기준 타격이라면 코코볼 27회, 썬브 2회로 되어야 한다고 생각합니다. 듀블의 블레이드 토네이도는 최대 1+8타까지 나오는데, 1+5타로 되어있기 때문에 통일성이 있어야 될 것 같습니다.
