### ISSUE TITLE
Rules 문서화

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#99]
`get_ruleset()`에서 사용 가능한 Rule은 다음과 같습니다.

* ConditionRule
  * 두 GraphElement A,B에 대해, check_function에 B 인스턴스가 들어옴. check_function이 True를 리턴하면 A를 사용.
  * False를 리턴하는 동안은 state_element는 절대 가동되지 않는건가요?
* UniquenessRule
  * 제일 기본적이고 필수적인 Rule입니다. 주어진 Element가 on 상태가 아니면 사용을 금지합니다.
    이 Rule이 적용되지 않을 경우 스킬 쿨타임이 무시됩니다.
  * readme에 이렇게 되어있는데, on상태면 사용을 금지하는게 맞는것 같습니다.
* ConcurrentRunRule
  * 두 GraphElement A,B에 대해, B가 A가 사용중일 때만 사용하도록 강제합니다. 극딜기를 함께 사용하도록
    할 때 유용합니다. 라고 readme에 작성되어 있습니다.
  * 코드를 보면 오히려 B가 사용중일때 A를 맞춰서 사용하는 것으로 보입니다.
* ReservationRule
  * 두 GraphElement A,B에 대해, B가 A가 사용가능할 때만 사용하도록 강제합니다. 극딜기를 함께 사용하도록
    할 때 유용합니다.
  * ConcurrentRunRule에서 A, B 순서를 바꾼것과 어떤 차이가 생기나요?
* SynchronizeRule
  * 인피니티 끝물에 극딜기 맞춰 사용할 때 쓰는데, direction을 1로 할때 동작이 어떻게 되는 지 모르겠습니다.
  * ConcurrentRunRule에 time offset을 추가한 것이라고 생각하면 되나요?
* MutualRule
  * 두 GraphElement A,B에 대해, 둘이 함께 사용될 수 없도록 강제합니다.
  * 둘 간의 우선순위는 어떻게 정해지나요? B가 사용가능할 때는 A를 사용할 수 없는것이 실제 동작인 것 같습니다.
* InactiveRule
  * 두 GraphElement A,B에 대해, B가 사용중이 아닐때만 A를 사용하도록 합니다.
* DisableRule
  * GraphElement 하나를 사용할 수 없도록 합니다.

`ConcurrentRunRule,` `SynchronizeRule`, `ReservationRule`간의 차이가 무엇인지 직관적으로 알기가 힘든 점이 있습니다.

`MutualRule, InactiveRule`도 마찬가지입니다. Rule간의 차이점과 각각 언제 사용하는지에 초점을 두고 문서를 보완할 필요가 느껴집니다.

**Comment by icepeng** [comment]
추가로, 적용한 Rule이 의도한 대로 적용되고 있는지 확인하기가 힘든 점이 있습니다. 프런트의 "상세 DPM" 페이지에 있는 버프 가동률 plot을 dpm_calc에서도 바로 확인할 수 있으면 딜사이클 계산에 큰 도움이 될 것 같습니다.

**Comment by oleneyl** [comment]
- 모든 Rule은, 다음과 같이 작동합니다.
  - get_related_element()로 받아온 element들은 실행되기 전에
  - check() 함수의 검사를 통과하지 못하면 실행될 수 없습니다.

- ConditionRule
  - 네 맞습니다.

- UniquenessRule, ConcurrentRunRule
  - 변경하도록 하겠습니다

- ConcurrentRule은 B가 `사용되고있을때`,  ReservationRule은, B를 `쓸수있을때` 사용합니다.
  - ConcurrentRule에서, A는 B가 켜져있다면 사용됩니다.
  - ReservationRule에서, A는 B를 쓸 수 있다면 사용됩니다.
  - 다음 상황에서는 ConcurrentRule을 사용해야만 합니다.
    - 90초 극딜기를 두 번 돌리고, 그중 하나에 150초 극딜기를 맞추려 할 때.
  - 다음 상황에서는 ReservationRule을 사용해야만 합니다.
    - 90초 극딜기를 150초 극딜기에 맞춰서, 150초를 기다리게 하려 할 때.

- SynchronizeRule
  - 말씀하신대로, 극딜기를 쓰고 특정 시간이 남았을때 다른 스킬을 쓰게하려고 사용합니다. ConcurrentRule의 연장이라고 보셔도 됩니다.
  - direction이 뒤집히면, 특정 시간 `이상` 남았을때 다른 스킬을 쓰게됩니다. 

- MutualRule
  - 모든 Condition은 뒤에오는 요소가 제약조건을 형성합니다. B를 사용가능하지 않을때만 A를 씁니다.

Rule은 문서화해서 commit하도록 하겠습니다.

**Comment by oleneyl** [comment]
문서화 완료.
